README.md
It should point at the new repository.
=> Correct git URL in README

app/views/index.html
The old link was broken, update this link.
=> Update link to docs from within the app

docs/creating-routes.md, docs/deploying.md, package.json, server.js
This is now running on express 4.13.3.
I've added the relevant middleware modules (see http://expressjs.com/guide/migrating-4.html#changes for more details) to retain functionality as is.
=> Upgraded to Express 4

server.js
Images referenced in Elements will now display in the Prototype Kit
=> Elements icons now display in the kit

app/assets/sass/application.scss, app/assets/sass/patterns.scss, app/views/examples/confirmation.html
Adding confirmation page to examples, with a new Sass folder for design patterns
=> Add confirmation page

app/assets/javascripts/details.polyfill.js
This updates the details summary to match PR #97 from GOV.UK elements -
Fixes for the details summary polyfill.
Only set tabindex on summary elements and display styling on content boxes when the details element is not native to the browser.
This also fixes a bug where the arrow isn’t in the open position if open=“open” is set on a details element.
This also includes some small modifications to use 'use strict', single quotes and strict equality.
This fixes issue #52.
=> Update the details summary polyfill

app/assets/sass/elements/_forms.scss
Reverts alphagov/govuk_prototype_kit#62
=> Revert e1a9d826eed82671870d76f1c850fc464bda98a3

app/assets/sass/application.scss, app/views/examples/index.html, app/views/examples/start-page.html
Add start page example, link to it from the index page and add missing related link styles.
=> Redo add start page

app/assets/sass/elements/_forms.scss
Amend the border for form controls
- this is now 2px wide and a darker grey
Also adjust the spacing for paragraphs in-between radio buttons or
checkboxes.
=> Update govuk elements form styles

app/views/examples/elements/radio-buttons-checkboxes.html
=> Add missing class of form control

app/views/examples/index.html, app/views/examples/question-page.html
Add an example question page using date of birth as the example question
=> Add question page

package.json, server.js
Add body-parser so people can read data out of POSTs
=> Add body-parser for parsing POSTs

app/routes.js, app/views/examples/elements/forms.html, app/views/examples/elements/grid-layout.html, app/views/examples/elements/radio-buttons-checkboxes.html, app/views/examples/elements/toggled-content.html, app/views/examples/elements/typography.html, app/views/examples/index.html, app/views/examples/template-data.html, app/views/includes/breadcrumb_examples.html, app/views/index.html
Added breadcrumbs and reformatted home page.
=> Update guidance pages

lib/template-config.js
=> Remove the link to the govuk help page about cookies

.travis.yml, CONTRIBUTING.md, create-release-tag.sh, jenkins.sh
1. Add jenkins.sh
2. Update contribution guidelines
Include section on semantic versioning.
This will also need a job in Jenkins to execute it / push the version (there's one for GOV.UK elements). 
Would you be best to set this up? @dsingleton / @alexmuller.
Once that job exists, that fixes #80.
=> Add Jenkins task to create a new tag and update contributing guidelines

app/views/examples/check-your-answers-page.html, app/views/examples/index.html, app/views/examples/template-partial-areas.html, app/views/index.html
- Use soft tabs with a two space indent
- Trim trailing whitespace
=> Adjust whitespace and indentation

app/views/examples/template-data.html
- fix typo
- add .code class for better formatting
- change 'check out' line to simpler English
=> Update template data page

Gruntfile.js
I found I was having to close down the node server and restart it manually each time I made changes to any .json files. I have added .json files to the files that nodemon watches for changes so it restarts the server automatically.
=> Amended Gruntfile.js to watch for changes to Json files

.travis.yml, Gruntfile.js
Create a test grunt task, to check that the app runs.
Use travis to run this task.
If this task succeeds, check to see if the version file has been updated.
=> Add test grunt task and update travis

package.json
=> Remove node-sass from package.json as grunt-sass includes it

lib/utils.js, start.js
This pull request improves the experience where the `node_modules` folder is missing.
Changes:
* Check for presence of the `node_modules` folder. Show error if not present.
A future PR could be to actually do `npm install` for the user.
=> Add warning if  folder missing or module missing

README.md
The download link now links to the v2.0.0 Zip.
Short note added to the top of the readme.
=> Update readme with details of new release

.travis.yml, create-release-tag.sh
- Move the create release tag script to after_success
- Add -v to help identify where the create-release-tag script is failing
=> Amend travis yml

app/views/examples/index.html, app/views/examples/start-page.html, app/views/includes/breadcrumb_examples.html
role=“breadcrumbs” is no longer a valid ARIA role, remove this.
cc. @fofr.
=> Remove invalid ARIA role

docs/guides/setting-up-git.md
=> Change smart quotes to straight quotes

README.md, docs/guides/using-verify.md
written after consulting the verify team on how they'd like people to contact them about this
=> add guidance page for using verify prototype

docs/guides/setting-up-git.md
Fixes a need identified in issue #174.
=> Add a link to install Git

package.json
- Fix anchor-buttons.js to trigger a native click event, also rename to
shimLinksWithButtonRole.js to explain what it does
- Add tests for shimLinksWithButtonRole ([PR
#310](https://github.com/alphagov/govuk_frontend_toolkit/pull/310))
- Add Department for International Trade organisation ([PR
#308](https://github.com/alphagov/govuk_frontend_toolkit/pull/308))
=> Use version 4.16.1 of the govuk_frontend_toolkit

package.json
https://raw.githubusercontent.com/alphagov/govuk_frontend_toolkit/master/CHANGELOG.md
- Add GOVUK.ShowHideContent JavaScript to support showing and hiding
content, toggled by radio buttons and checkboxes ([PR
#315](https://github.com/alphagov/govuk_frontend_toolkit/pull/315)).
- SelectionButtons will add a class to the label with the type of the
child input ([PR
#317](https://github.com/alphagov/govuk_frontend_toolkit/pull/317))
=> Use version 4.18.0 of the govuk_frontend_toolkit

lib/govuk_template_unbranded.html
I've done the work, but is there a build step that does this?
=> Update the cache busting value to the latest template version number

.travis.yml, update-release-branch.sh
- Add an encrypted authentication key for Github.
- Add a new scripts file to check a tag exists, if it does - it should check out the tag matching the version in the version.txt file, create a new branch from this tag and push this new branch "latest-release" to GitHub.
=> Update latest release branch

.travis.yml
=> Get travis to encrypt the GitHub token

app/assets/sass/application.scss, app/views/examples/elements/grid-layout.html, package.json
- Update govuk-elements-sass to v2.0.0
- Define a path to assets, for use with the file-url function
- Update the grid layout example page text and and show a full width column using the .column-full class.
cc. @robinwhittleton.
=> Bump govuk elements sass to 2.0.0

.travis.yml
This updates the environment variable in the config to enable
deployment via Travis CI.
=> Replace encrypted GitHub token

package.json
This release includes the [custom radio button and checkbox styles](http://govuk-elements.herokuapp.com/form-elements/example-radios-checkboxes/).
https://github.com/alphagov/govuk_elements/blob/master/CHANGELOG.md#220
Screenshot:
=> Update govuk-elements-sass to 2.2.0

app/assets/sass/unbranded.scss, package.json
https://raw.githubusercontent.com/alphagov/govuk_frontend_toolkit/master/CHANGELOG.md
- Fix role="button" click shim ([PR
#347](https://github.com/alphagov/govuk_frontend_toolkit/pull/347))
- Make font variables lowercase ([PR
#348](https://github.com/alphagov/govuk_frontend_toolkit/pull/348))
- Update selection button documentation ([PR
#350](https://github.com/alphagov/govuk_frontend_toolkit/pull/350))
=> Update govuk_frontend_toolkit to 5.0.1

docs/views/examples/question-page.html
So it links back to the tutorials and examples landing page
=> Update ‘Back’ link URL

server.js
app.locals is the right way to set variables that are the same for all users, this fixes #217
=> Use app.locals instead of app.use

docs/documentation/publishing-on-heroku.md
This fixes #230 - you need to first set up Git before setting up Heroku
=> Add Git step to Heroku guide

gulp/sass.js
init was being called after the sass was being compiled - it needs to be called before
=> fix css sourcemaps

docs/documentation/creating-routes.md, docs/documentation/making-pages.md, docs/views/examples/branching.html
Based on Issue - https://github.com/alphagov/govuk_prototype_kit/issues/342
=> Removing links to route.js / updating example in branching.html

app/config.js, app/routes.js, docs/documentation_routes.js, lib/core_filters.js, lib/utils.js, server.js, start.js
Mainly:
- use the proposed [GDS headings for Node dependency blocks](https://github.com/maxcbc/gds-way/blob/5edb13b78541e7131da383916fcdacd228986a9c/source/manuals/programming-languages/nodejs/style-guide.html.md.erb)
- correcting typos
- making all comments sentence case (start with a capital letter)
- making some comments clearer
- standardising spacing (no line between a comment for a block and the block itself)
=> Clean up typos, formatting, etc

docs/documentation/updating-the-kit.md
Need to also copy over the config.js file in order to upgrade the kit. Without it, npm start won't work
=> Update for those not using the command line

docs/documentation/install/developer-install-instructions.md, docs/documentation/install/requirements.md, package.json
See https://github.com/alphagov/govuk_prototype_kit/issues/459
=> Update docs for node 8 LTS

docs/documentation/install/install-the-kit.md, docs/views/install.html, docs/views/tutorials-and-examples.html
We are having problems tracking download numbers, this might fix it
[Trello card](https://trello.com/c/MfmxdKwX/693-update-the-tracking-for-prototype-kit-beta-website-download-file-click-external-links)
=> Add data attributes to fix tracking

CHANGELOG.md, docs/views/index.html
Cherry-picks https://github.com/alphagov/govuk-prototype-kit-private-beta/pull/59
Closes https://github.com/alphagov/govuk_prototype_kit/issues/514
=> Add design system message to home page

CHANGELOG.md, docs/views/index.html
Also fixes some alignment issues
=> Update docs/index page to include same information as private beta

docs/views/examples/start-page.html
=> fix typo on start page

CHANGELOG.md, app/views/layout.html, docs/views/layout.html
=> Import missing component macros

package.json
Frontend release notes:
https://github.com/alphagov/govuk-frontend/releases/tag/v1.1.0
=> Update govuk frontend 1.1.1

docs/views/examples/start-page.html
As seen in this PR: https://github.com/alphagov/govuk-frontend/pull/807
=> Simplify start page

docs/documentation/using-verify.md
Product page URL update and email address updated
=> Updating deprecated support email address

docs/documentation/using-notify.md, docs/views/tutorials-and-examples.html
Code block styling and adding the link to the guidance from the Tutorials and Guidance page
Fixes: https://github.com/alphagov/govuk-prototype-kit/issues/622
=> Tidy up guidance on using GOV.UK Notify

package.json
This closes #618.
I couldn't find any uses of arguments in the installation/usage guides. I also couldn't find the dependency being included in this project.
Projects depending on this project should still be checked of course. I'm not aware of the breadth or complexity of this search.
I know that it's a small PR but I hope this helps!
=> Removed minimist dependency

__tests__/spec/force-https-redirect.js
This PR helps increase our code coverage and ensure that when we refactor that we do not break any existing functionality.
Trello Card: https://trello.com/c/BSsGdn5o
=> Add tests for force-https-redirect feature

README.md
Reverts alphagov/govuk-prototype-kit#646
We have got enough results that we've decided to stop promoting this.
https://trello.com/c/aGO2estC/1630-remove-survey-promotion-from-repositories
=> Revert "Add note about frontend survey to README"

CHANGELOG.md, docs/documentation_routes.js, gulp/sass.js, lib/utils.js, package.json
Updates from 11.0.1 to 12.0.1
https://standardjs.com/changelog.html#1200---2018-08-28
=> update Standard to 12.0.1

CHANGELOG.md, app/views/layout.html, package.json
Allows use of new components Accordion and Summary List
=> Update to GOV.UK Frontend version 2.5.0

CONTRIBUTING.md
Update the release documentation to be more accurate and easier to follow
=> Updates release docs

package.json
This fixes #691 (most of the low severity security vulnerabilities)
=> Upgrade jest to ^24.0.01

docs/views/examples/pass-data/vehicle-check-answers.html
Needs an additional 1/3 class on the key to fit the wording in one line on desktop 
Addresses #694
=> Use summary list component in 'Pass data' example

CHANGELOG.md, app/assets/sass/patterns/_task-list.scss, docs/views/templates/task-list.html
=> Update task list focus state

CHANGELOG.md
This pull requests updates the changelog with the release notes for v9.0.0 (unreleased). 
The same content will be used in the GitHub release notes.
It's been reviewed for factual accuracy, and 2i'd for style by another technical writer.
Following review and before publication we need to copy to the GitHub release note.
=> Update with v9.0.0 (unreleased) changelog

CHANGELOG.md, __tests__/spec/sanity-checks.js, app/assets/sass/application.scss, app/assets/sass/patterns/_step-by-step-navigation.scss, app/assets/sass/patterns/_task-list.scss, app/assets/sass/unbranded.scss, app/views/layout.html, app/views/layout_unbranded.html, docs/assets/sass/docs.scss, docs/documentation/tips-and-tricks.md, docs/documentation/using-notify.md, docs/views/examples/branching/index.html, docs/views/examples/pass-data/vehicle-features.html, docs/views/examples/pass-data/vehicle-registration.html, docs/views/examples/pass-data/vehicle-type.html, docs/views/includes/scripts.html, docs/views/layout.html, docs/views/layout_unbranded.html, docs/views/templates/check-your-answers.html, docs/views/templates/confirmation.html, docs/views/templates/question.html, docs/views/templates/start-with-step-by-step.html, docs/views/templates/start.html, docs/views/templates/task-list.html, lib/extensions/extensions.js, lib/extensions/extensions.test.js, package.json
See https://github.com/alphagov/govuk-prototype-kit/releases/tag/v9.0.0 for details
=> Merge v9.0.0 (GOV.UK Frontend v3.0.0 ) branch into master

.github/issue_template.md, .github/pull_request_template.md
Reverts alphagov/govuk-prototype-kit#792
=> Remove issue and pull request templates

docs/documentation/make-first-prototype/make-first-prototype.md
Added new section to first page of tutorial to allow users to feedback about it or get some help.
=> Add feedback section to first page of step-by-step tutorial

docs/documentation/make-first-prototype/start.md, docs/views/tutorials-and-examples.html
This commit updates the url for the first page in the tutorial to 'start'
=> Update the url for the first page in the tutorial

package.json
=> Update to GOV.UK Frontend v3.5.0

docs/documentation/make-first-prototype/let-user-change-answers.md
Been checking through this ahead of kit training next week. The example here wasn't up to date with latest frontend and had a smart quote in it that broke the page a bit. I remember it coming up last time. Have updated it, would be great to update by Thursday!
=> Fix incorrect example

docs/documentation/make-first-prototype/show-users-answers.md
We use `how-many-balls` everywhere, except here.
=> Fix inconsistent data key

CHANGELOG.md, package.json
=> Update to GOV.UK Frontend v3.6.0

docs/views/examples/pass-data/index.html
Thanks to @philswan for flagging this in #883.
=> Add missing comma to code example

package.json
=> Update to GOV.UK Frontend v3.7.0

docs/documentation/install/run-the-kit.md, docs/documentation/updating-the-kit.md, docs/views/tutorials-and-examples.html
This improves our Updating the Prototype Kit documentation, as we know from support that users encounter issues when they try to update the Prototype Kit.
=> Improve 'Updating the kit'

package.json
=> Update GOV.UK Frontend to v3.8.0

package.json
Closes https://github.com/alphagov/govuk-prototype-kit/issues/923
=> Update GOV.UK Frontend to 3.9.0

package.json
=> Update marked to fix security issue

docs/documentation/install/run-the-kit.md
- clarify that if you're following the installation guide, you will already be in the right folder
- link to the tutorial
- some general clean up, use 'the terminal' consistently
=> update 'Run the kit'

CHANGELOG.md
Fixes https://github.com/alphagov/govuk-prototype-kit/issues/958
=> Add release notes for Prototype Kit v9.11.0

docs/documentation/make-first-prototype/link-pages-together.md
Includes:
- small updates to clarify language
- more explanation of links vs forms
- correct instances of 'link' to 'button'
=> update 'link pages together'

docs/documentation/using-verify.md, docs/views/tutorials-and-examples.html
Verify is not accepting new services
=> Remove Verify page

CHANGELOG.md, package.json
See https://github.com/alphagov/govuk-prototype-kit/pull/925
=> Upgrade notify client to version 5.1.0

docs/documentation/updating-the-kit.md
The unordered list needs to be indented to be a child of Step 4.
This changes the compiled HTML from:
```
<ol>...</ol>
<ul>...</ul>
<ol start="5">...</ol>
```
to 
```
<ol>
...
<li>
<ul>...</ul>
</li>
...
</ol>
```
=> Fix nested list on update page

docs/documentation/accessibility.md, docs/views/layout.html
Accessibility statement for GOV.UK Prototype Kit documentation website
=> Create accessibility page for Prototype Kit

CHANGELOG.md
Just noticed we've swapped the packages in this CHANGELOG entry.
=> Fix typo in PR title

docs/documentation/updating-the-kit.md
Amended instructions for updating prototypes to v12.0.0 following release.
=> Updating instructions to v12.0.0

docs/documentation/install/requirements.md
Edit Git Bash download instructions to make it clear they are for Window's users and what will be downloaded by an install.
=> Amend Git Bash instructions

docs/documentation/install/developer-install-instructions.md
Fixes [#930](https://github.com/alphagov/govuk-prototype-kit/issues/930).
=> Add kit download link to dev install guide

docs/views/examples/pass-data/index.html
=> Use idPrefix to be consistent with design system

package.json
Having your tests fail to run because of linter issues is annoying ;)
=> Change npm test to run linter at end

internal_docs/releasing.md
Update in step 10 to reflect that description should be copied from Google Doc, not Changelog
=> Update release notes to reflect what we do

CHANGELOG.md
Remove multiple H1 headings and make heading structure consistent with that
=> Fix heading hierarchy

.github/workflows/run-tests.yaml, .github/workflows/test-heroku.yaml
This might help speed up PR checks.
=> Cache npm packages and Cypress binaries in CI workflows

__tests__/spec/start.js, __tests__/spec/update-script.js, __tests__/spec/utils.js, lib/build/check-files.js, package.json, start.js
=> Fix message about node modules folder

__tests__/spec/utils.js
You can now use mkReleaseArchiveSync to test changes in the working tree (for tracked files).
=> Improve test util mkReleaseArchiveSync

__tests__/spec/start.js, lib/build/check-files.js, package.json, start.js
nicer experience on older version of npm - no stack trace
fixes #1365
=> revert to exit(0)

package-lock.json, package.json
Bumps browser-sync and async to close security warnings.
=> Bump async

package-lock.json
Updates browserslist database using
npx browserslist@latest --update-db
This is only used by jest, so updating doesn't affect users, but I was getting annoying messages to update caniuse-lite every time I ran the tests 🙄
=> Bump caniuse-lite

.github/workflows/run-tests.yaml, .npmrc, __tests__/spec/install.js
=> Make npm install not install dev dependencies  by default on npm@6

README.md
=> Remove note from README about optional dependencies

.gitattributes, .github/workflows/lint.yaml, .github/workflows/test-heroku.yaml, .github/workflows/test.yaml, .gitignore, CODEOWNERS, app.json
Grab-bag PR of fixes for some small internal snags I've noticed.
=> Do a spring clean 🧹 

cypress/integration/1-watch-files/watch-custom-styles.cypress.js, cypress/integration/1-watch-files/watch-styles.cypress.js
=> Integration test for custom sass changes

cypress/integration/1-watch-files/watch-routes.cypress.js
The hard coded domain of http://localhost:3000 is not required or desirable in this test
=> Full path not required in view test

cypress/fixtures/views/checkbox-test.html, cypress/integration/2-page-component-tests/checkboxes.cypress.js
These tests will make sure the "_unchecked" option is set when submitting a page whether or not a checkbox has been clicked.
=> Cypress tests for checkboxes

cypress/plugins/index.js
Use fs.promises in the cypress plugin where possible.
=> Use fs-promises where possible in Cypress

cypress/fixtures/views/step-by-step-navigation.html, cypress/integration/3-link-page-tests/link-page-utils.js, cypress/integration/4-step-by-step-tests/step-by-step-journey.cypress.js, cypress/integration/utils.js
Cypress tests for step by step ui toggling steps
- Create integration tests for step by step
- Refactor to reuse delete and copy file functionality as a utility
=> Cypress Step by step tests

cypress/integration/1-watch-files/watch-config.cypress.js, cypress/integration/1-watch-files/watch-custom-styles.cypress.js, cypress/integration/1-watch-files/watch-images.cypress.js, cypress/integration/1-watch-files/watch-routes.cypress.js, cypress/integration/1-watch-files/watch-styles.cypress.js, cypress/integration/1-watch-files/watch-views.cypress.js, cypress/integration/2-page-component-tests/checkboxes.cypress.js, cypress/integration/3-link-page-tests/branching-journey.cypress.js, cypress/integration/3-link-page-tests/change-answers.cypress.js, cypress/integration/3-link-page-tests/simple-journey.cypress.js, cypress/integration/4-step-by-step-tests/step-by-step-journey.cypress.js
See: https://github.com/alphagov/govuk-prototype-kit/issues/1437
Solved by waiting for the application to restart after each test setup.
=> Fix cypress failures caused by timeouts on slow machine

lib/extensions/extensions.js, package.json
I just noticed that not all JavaScript files were being linted... this PR fixes that.
=> Fix linting

cypress/integration/3-link-page-tests/link-index-to-start.cypress.js, cypress/integration/3-link-page-tests/link-page-utils.js
Cypress test to test the following within the tutorial:
https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/link-index-page-start-page
=> Link your index page to your start page

app/assets/javascripts/application.js
Make the document on ready handler name more descriptive and scoped.
Resolves https://github.com/alphagov/govuk-prototype-kit/pull/1481#discussion_r932212324.
=> Rename and scope document ready handler

.github/workflows/test.yaml, __tests__/spec/build.js, __tests__/spec/sanity-checks.js, lib/build/generate-assets, lib/build/tasks.js
Adding these now because it would be helpful when working on #1481.
=> Add tests for generateAssets

lib/build/tasks.js
It was possibly added accidentally
=> Remove the watch task logging

cypress/integration/4-step-by-step-tests/step-by-step-journey.cypress.js
Reuse cypress tests for the "step by step navigation template" to test the "start step by step template"
=> Integration tests for start step by step

__tests__/spec/sanity-checks.js, __tests__/spec/update-script.js, docs/documentation_routes.js, update.sh
We want to have the update script work with 12.2.0, so we backport changes we've made in the main branch.
=> Backport changes to update script to 12.x support branch

CHANGELOG.md
Fixes #1538.
I accidentally messed up and the changelog didn't get updated to have the correct version of GOV.UK Frontend (4.3.1).
=> Update changelog for v12 support branch

bin/cli, cypress/fixtures/extensions/extension-bar/package-lock.json, cypress/fixtures/extensions/extension-foo/package-lock.json, package-lock.json, package.json, prototype-starter/.gitignore, prototype-starter/npmrc
Do not copy files that do not exist
=> Make prototype kit cli work outside kit

bin/cli, cypress/fixtures/extensions/extension-bar/package-lock.json, cypress/fixtures/extensions/extension-foo/package-lock.json, package.json, prototype-starter/npmrc
Generate both the .gitignore and .npmrc files within the install cli.
=> Remove gitignore from prototype starter

cypress/e2e/6-management-tests/change-service-name.cypress.js, lib/middleware/authentication/authentication.js, lib/middleware/authentication/authentication.test.js, lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/clear-data-success.njk, lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/clear-data.njk, lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/layout.njk, lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/password.njk, lib/nunjucks/govuk-prototype-kit/layouts/govuk-branded.html, lib/routes/prototype-admin-routes.js, package.json
=> Clear data and password pages

bin/cli, bin/utils/argvParser.js, bin/utils/argvParser.spec.js, package.json
We tried to use the interface and it wasn't working, it didn't have any tests around it so I've pulled out the part that caused this problem (the part with the most complexity) into a util which is tested.
=> Better cli argument parsing

govuk-prototype-kit.config.json, lib/build/tasks.js, lib/routes/prototype-admin-routes.js
I've gone through the interface with @joelanman and we decided that some updates would be beneficial.  These are the updates.
=> Update plugin interface

.github/workflows/test.yaml, __tests__/util/index.js, cypress/e2e/5-extension-tests/install-extension-test.cypress.js, cypress/e2e/6-management-tests/install-available-plugin.cypress.js, cypress/e2e/utils.js, cypress/fixtures/extensions/extension-baz/filters.js, cypress/fixtures/extensions/extension-baz/govuk-prototype-kit.config.json, cypress/fixtures/extensions/extension-baz/package.json, cypress/fixtures/extensions/extension-baz/sass/baz.scss, cypress/fixtures/extensions/extension-baz/scripts/baz.js, cypress/fixtures/extensions/extension-baz/views/baz.njk, cypress/plugins/index.js, cypress/scripts/run-starter-prototype.js, lib/build/tasks.js, lib/extensions/extensions.js
The application will detect the install, update, and uninstall of a plug-in.
The plug-in cypress tests have been updated to test the above.
=> Install plugins without restart

package.json, prototype-starter/app/filters.js, prototype-starter/app/routes.js
When linting, ignore files in prototype starter
=> Remove eslint from prototype starter

lib/migrator/fileHelpers.js, lib/migrator/index.js, lib/migrator/logger.js
Log migration actions to a migrate.log log file
=> Add logging to migrate process

lib/config.js, lib/migrator/index.js
Migrate config.js to config.json
=> Migrate config file

__tests__/fixtures/test-prototype/.gitignore, __tests__/fixtures/test-prototype/app/assets/javascripts/application.js, __tests__/fixtures/test-prototype/app/assets/sass/application.scss, __tests__/fixtures/test-prototype/app/config.js, __tests__/fixtures/test-prototype/app/filters.js, __tests__/fixtures/test-prototype/app/routes.js, __tests__/fixtures/test-prototype/app/views/layout.html, __tests__/spec/migrate.js, lib/migrator/migrationSteps.js, package.json
Test a simple migration from version 11 to version 13
=> Test simple migrate

CHANGELOG.md
=> Add new head blocks to changelog

bin/cli, package-lock.json
Fixes #1680.
I forgot to return the promise.
=> Fix gitignore migration

CHANGELOG.md
This was missed from PR #1478.
=> Update changelog to include jQuery changes

bin/cli
=> Add usage data config file to usage prototype gitignore

package.json
Releasing a second beta to npm to make internal testing easier.
=> Release 0.0.1-beta.2

package-lock.json, package.json
=> Release 0.0.1-beta.3

bin/cli
This is useful for debugging when using npx.
=> Add version command

lib/migrator/index.js
=> Add jQuery to packages to install when migrating existing prototypes

lib/migrator/index.js
=> Add step-by-step plugin to packages to install when migrating prototypes

__tests__/spec/migrate.js, lib/migrator/index.js, lib/migrator/migrationSteps.js, lib/migrator/migrationSteps.spec.js, lib/migrator/migrator.spec.js, lib/migrator/reporter.js
See: https://github.com/alphagov/govuk-prototype-kit/issues/1729
- Some refactoring was required to retrieve the result of each step.
- Additional reporting for each file and directory successfully deleted.
- Suppress reporting of attempting to delete directories or files that don't exist
=> Update content of migration script output

lib/routes/prototype-admin-routes.js
Retrieve plugins from known-plugins.json
=> Fix plugin latest release versions

CHANGELOG.md, __tests__/spec/migrate.js, prototype-starter/app/routes.js
Fixed the link to the routes guidance
=> Fix link to docs in routes.js

internal_docs/releasing.md
Fixes a few inaccuracies/unclear parts about our docs on how to do a release.
=> Fix releasing internal docs

cypress/e2e/dev/4-step-by-step-tests/step-by-step-journey.cypress.js, cypress/e2e/dev/6-management-tests/create-new-page-from-template.cypress.js, cypress/e2e/dev/6-management-tests/preview-template-view.cypress.js, cypress/e2e/step-by-step-utils.js, cypress/e2e/utils.js, lib/routes/prototype-admin-routes.js, lib/utils.js, server.js
See: https://github.com/alphagov/govuk-prototype-kit/issues/1763
Make sure the javascript from available extensions are loaded in the view
=> Fix previewing templates with javascript in management pages

CHANGELOG.md
I should have flagged this up in review, fixing now.
=> Update changelog with fix from #1804

CHANGELOG.md, __tests__/spec/build.js, __tests__/spec/errors.js, __tests__/spec/force-https-redirect.js, __tests__/spec/sanity-checks.js, lib/config.js, lib/config.test.js, lib/routes/prototype-admin-routes.js, listen-on-port.js, package.json, server.js
Fixes #1807.
See commit messages for more details.
=> Stop express complaining if error occurs after res has been sent

cypress.config.js, cypress/events/index.js
See https://github.com/alphagov/govuk-prototype-kit/issues/1808
=> Rename cypress plugins as cypress events

CHANGELOG.md, __tests__/spec/migrate.js, prototype-starter/app/views/layouts/main.html
Just updating a broken link that @frankieroberto helpfully spotted!
=> Update broken link to layouts guidance

cypress/e2e/dev/6-management-tests/clear-data-page.cypress.js, cypress/e2e/utils.js
See: [Add tests for clear data page](https://github.com/alphagov/govuk-prototype-kit/issues/1610)
- Acceptence tests created to prove data can be added and cleared successfully
=> Test clear data page

cypress/e2e/dev/2-page-component-tests/checkboxes.cypress.js, cypress/e2e/dev/4-step-by-step-tests/step-by-step-journey.cypress.js, cypress/e2e/plugins/0-plugins-tests/install-available-plugin.cypress.js, npm-shrinkwrap.json, package.json
- [Release announcement](https://www.cypress.io/blog/2022/12/06/announcing-cypress-12/)
- [Release notes](https://docs.cypress.io/guides/references/changelog#12-2-0)
- [Changelog](https://docs.cypress.io/guides/references/changelog)
=> Upgrade cypress to version 12

bin/cli, lib/build.js, lib/dev-server.js
Make the build file a little more manageable.
=> Split dev server code from build code

lib/session.js
See: [Slow page load times in version 13](https://github.com/alphagov/govuk-prototype-kit/issues/1843)
=> Speed up performance by removing data encryption

CHANGELOG.md, npm-shrinkwrap.json, package.json
- When creating a prototype, the kit now makes an initial Git commit for you. That saves you time, and makes a separation between the initial prototype files and any changes you make yourself. If you do not want the kit to do this, you can add --no-version-control to the create command.
- You can now install, update and uninstall plugins in the Manage your prototype section, without having to use the terminal.
- Fixes to issues where the kit wouldn't run properly with square brackets or spaces in the folder path.
- Improvements to the migration process
- Stop unnecessary warnings about the session file store
- Improvements to validation when creating pages from templates
- Fixed slow performance issues when running online
=> Release 13.1.0

bin/cli, bin/utils/argv-parser.spec.js, bin/utils/index.js
Also cleaning up version handling and logging the installer location when using `--verbose` (this will be helpful for debugging).
=> Not showing progress reports for older installers.

CHANGELOG.md, internal_docs/releasing/releasing.md, npm-shrinkwrap.json, package.json
- When you create a prototype, there is now clearer and more helpful messaging to tell you what's happening and what to do next.
- If you have a prototype running and start another one, the kit will prompt whether you want to run both or not. If you say no it will now quit properly without you having to press ctrl c.
- Faster to create prototypes.
=> Preparing for release 13.2.0

bin/cli
This is the fix for https://github.com/alphagov/govuk-prototype-kit/issues/1920
=> Not displaying output for older installers.

CHANGELOG.md, npm-shrinkwrap.json, package.json
- Cleaning up creation messages for users who have an older installer (v13.1.0 and before)
=> Preparing for release 13.2.1

CHANGELOG.md, bin/cli, npm-shrinkwrap.json, package.json
- Displaying creation messages correctly
=> Release 13.2.2

cypress/e2e/dev/4-step-by-step-tests/step-by-step-journey.cypress.js, cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-test.cypress.js, cypress/e2e/plugins/1-available-plugins-tests/available-plugins.cypress.js, cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js, cypress/e2e/plugins/1-available-plugins-tests/install-common-templates-plugin-from-templates-page.cypress.js, cypress/e2e/plugins/1-available-plugins-tests/preview-template-view.cypress.js, cypress/e2e/plugins/2-prototype-kit-plugin-tests/prevent-uninstalling-kit-from-ui.cypress.js, cypress/e2e/plugins/plugin-utils.js, cypress/e2e/utils.js, cypress/events/index.js, lib/assets/javascripts/manage-prototype/manage-plugins.js, lib/manage-prototype-handlers.js
Plugin Acceptance tests now pass consistently every time
=> Fix plugin tests

CHANGELOG.md
Added changlog feature for: [Make notifications node client available](https://github.com/alphagov/govuk-prototype-kit/pull/1962)
=> Add notify client plugin availability to change log 

CHANGELOG.md
see: [Auto update when settings created and removed](https://github.com/alphagov/govuk-prototype-kit/pull/1988)
Add missing change log for above
Also removed 13.3.1 heading as this hasn't been released as yet.
=> Add change log entry for settings creation fix

lib/plugins/plugins.js
- added dwp to known words to format
it worked - yaay!
=> Capitalisation of DWP

CHANGELOG.md, lib/nunjucks/nunjucksLoader.js
See https://github.com/alphagov/govuk-prototype-kit/issues/1719 and https://github.com/alphagov/govuk-prototype-kit/pull/2035
=> Update change log for njk extension support

__tests__/fixtures/mockNunjucksIncludes/govuk/template.njk, __tests__/spec/errors.js, lib/nunjucks/views/error-handling/page-not-found.njk, lib/nunjucks/views/error-handling/server-error.njk
I've fixed up the tests, there are a couple of things that need discussing, particularly questioning whether this should be using `mkPrototype` to create an instance of the prototype rather than firing requests at `server.js` out of context.
=> Error pages update

internal_docs/releasing/releasing.md
- rewrote step 6
- corrected link at the end
- added more detail to step 3
=> A couple improvements to release instructions

CHANGELOG.md, lib/manage-prototype-handlers.js, lib/manage-prototype-handlers.test.js, lib/nunjucks/views/manage-prototype/layout.njk, lib/nunjucks/views/manage-prototype/template-install.njk, lib/nunjucks/views/manage-prototype/template-post-install.njk
Fix for https://github.com/alphagov/govuk-prototype-kit/issues/1952
=> Updating page titles for template pages.

CHANGELOG.md, npm-shrinkwrap.json, package.json
Plugin authors can now use scripts with type module (an experimental change - please get in touch if you want support using this)
Accessibility fixes including better page titles when making pages from templates, and a more accessible terminal message.
The process to migrate old prototypes to v13 now handles custom javascript and filters better.
=> Preparing for release 13.6.0

migrator/upgrade-steps.spec.js
Some of Natalie's test were lost when this functionality was merged, this adds them back.
=> Add Natalie's migration tests

CHANGELOG.md, lib/session-file-store.js, lib/session-file-store.test.js, lib/session.js
- Added our own implementation of session file store
- wrote unit tests
=> 2130 create our own file store

CHANGELOG.md, lib/usage-data.js
Make change and make sure functionality still works
=> Replace chalk with ansi-colors as it is installed as a dependency

lib/utils/utils.test.js, npm-shrinkwrap.json, package.json
- Test changed to use our internal file store
- Uninstalled old session-file-store package
=> Remove old session file store dependency

__tests__/fixtures/mockPlugins/invalid-plugin/govuk-prototype-kit.config.json, __tests__/spec/plugin-validator.js, lib/plugins/plugin-validator.js
- adding case for nunjucksMacros to the validator
=> Issue 2235 nunjucks macros validation error

CHANGELOG.md, known-plugins.json
- added validator bug fix to change log
- removed home-office plugin from available plugins list
=> Preparing for patch release

CHANGELOG.md, npm-shrinkwrap.json, package.json
- fixing validator bug
- removing home-office plugin
=> preparing for release 13.9.1

CHANGELOG.md, __tests__/spec/migrate.js, prototype-starter/app/filters.js
See: [Add comments to the starter filters.js file](https://github.com/alphagov/govuk-prototype-kit/issues/2252)
=> Add comments to the prototype-starter filters file

internal_docs/releasing/releasing.md, package.json, scripts/prepare-release, scripts/utils/create-release-branch
https://github.com/alphagov/govuk-prototype-kit/issues/1279
This handles everything up to (and including) the creation of the pull request.  I created a draft PR using this script https://github.com/alphagov/govuk-prototype-kit/pull/2272 so that we can view and refine the output easily.
=> Automated first part of release.

scripts/utils/create-release-pr
Slight bug with the review count check.
=> Correcting the reviewer count check

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2264: Add back to templates link](https://github.com/alphagov/govuk-prototype-kit/pull/2264)
- [#2270: Fix corrupt session files issue](https://github.com/alphagov/govuk-prototype-kit/pull/2270)
=> Preparing for release 13.12.0 (automated)

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2303: Update high vulnerability node modules](https://github.com/alphagov/govuk-prototype-kit/pull/2303)
=> Preparing for release 13.12.2 (automated).

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2305: Build the enhanced plugin page](https://github.com/alphagov/govuk-prototype-kit/pull/2305)
- [#2314: Plugin validator allows the user to specify unknown keys](https://github.com/alphagov/govuk-prototype-kit/pull/2314)
=> Preparing for release 13.13.0 (automated).

CHANGELOG.md
Add missing entry in change log for PR: https://github.com/alphagov/govuk-prototype-kit/pull/2336
=> Add change log from PR2366

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2364: Fix plugin update detection](https://github.com/alphagov/govuk-prototype-kit/pull/2364)
=> Preparing for release 13.13.6 (automated).

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2370: Support no internet connection](https://github.com/alphagov/govuk-prototype-kit/pull/2370)
=> Preparing for release 13.14.1 (automated).

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2369: Support multiple passwords](https://github.com/alphagov/govuk-prototype-kit/pull/2369)
=> Preparing for release 13.15.0 (automated).

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2378: Add filters and functions when the environment is ready](https://github.com/alphagov/govuk-prototype-kit/pull/2378)
=> Preparing for release 13.15.2 (automated).

CHANGELOG.md, lib/manage-prototype-handlers.js, lib/manage-prototype-handlers.test.js
Only installed packages that are plugins should be in the list of installed plugins
=> Only display packages that are plugins

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2384: Add format items filter to core filters](https://github.com/alphagov/govuk-prototype-kit/pull/2384)
- [#2382: Make any npm module a plugin via a proxy plugin config](https://github.com/alphagov/govuk-prototype-kit/pull/2382)
=> Preparing for release 13.16.0 (automated).

CHANGELOG.md, lib/manage-prototype-handlers.js, lib/manage-prototype-handlers.test.js
Proposed fix for #2424
The added test fails before this fix and passes after this fix
=> #2424: Fix open redirect vuln in login page

npm-shrinkwrap.json, package.json
=> Update govuk-frontend to 5.11.0

npm-shrinkwrap.json
Some fairly nasty critical vulns existed in https://github.com/advisories/GHSA-fjxv-7rqg-78g4                                                                                                                            
Also fixes this along the way https://github.com/advisories/GHSA-76c9-3jph-rj3q
=> Fix vulnerabilities by `npm audit fix`

CHANGELOG.md, npm-shrinkwrap.json, package.json
- [#2452: Update manage prototype header](https://github.com/alphagov/govuk-prototype-kit/pull/2452)
- [#2451: Apply new brand to new prototypes](https://github.com/alphagov/govuk-prototype-kit/pull/2451)
=> Preparing for release 13.18.0 (automated).
