alphagov/govuk-prototype-kit

- package.json
By default Brew installs Node 0.12 which doesn't work with the version of Node SASS being used, which is only compatible with versions up to 0.10.
This commit updates the version of Grunt SASS to [0.18.0](https://github.com/sindresorhus/grunt-sass/releases/tag/v0.18.0), which incorporates Node SASS version [2.0.0](https://github.com/sass/node-sass/releases/tag/v2.0.0), which _is_ compatible with Node 0.12.
> Update Grunt SASS for compatibility with Node 0.12

- app/assets/sass/elements/_buttons.scss
- app/assets/sass/elements/_forms.scss
These changes are the same as those in a PR for GOV.UK elements: https://github.com/alphagov/govuk_elements/pull/63/files
For smaller screens, buttons are now full width.
Button styles are removed from the _forms.scss file.
@timpaul @tombye
> Make buttons full width for smaller screens

- app/views/examples/template-partial-areas.html
- lib/template-config.js
- package.json
- Add `homepage_url` for overriding the href for the header logo link
("https://www.gov.uk" by default)
- Add `global_header_text` for overriding the header logo text
("GOV.UK" by default)
Here is the PR on the govuk template for context: https://github.com/alphagov/govuk_template/pull/148 
- Removed deprecated grid layout mixins:
alphagov/govuk_template#129
> Bump govuk template to 0.13.0

- package.json
- Track download links using events not pageviews
- Add two analytics plugins for download and external link tracking
- Update typography mixins to be mobile first (PR #157)
- Update Accessible Media Player to remove dependency on $.browser (PR
#206)
- Add support for sending the `page` option to
`GOVUK.analytics.trackEvent` (PR #203)
> Update govuk frontend toolkit to 4.2.1

- app/assets/sass/elements.scss
- app/assets/sass/elements/_breadcrumb.scss
- app/assets/sass/elements/_buttons.scss
- app/assets/sass/elements/_details.scss
- app/assets/sass/elements/_elements-typography.scss
- app/assets/sass/elements/_forms.scss
- app/assets/sass/elements/_helpers.scss
- app/assets/sass/elements/_icons.scss
- app/assets/sass/elements/_layout.scss
- app/assets/sass/elements/_lists.scss
- app/assets/sass/elements/_panels.scss
- app/assets/sass/elements/_tables.scss
- app/assets/sass/elements/forms/_form-block-labels.scss
- app/assets/sass/elements/forms/_form-date.scss
- app/assets/sass/elements/forms/_form-validation.scss
- app/views/examples/elements/forms.html
- app/views/examples/elements/grid-layout.html
- app/views/examples/elements/typography.html
To make this easier to keep up-to-date in the future - update each partial to match those here:
https://github.com/alphagov/govuk_elements/tree/master/public/sass/elements
This moves @import statements for any GOV.UK front end toolkit dependencies from the top of the elements.scss file to the top of each partial.
The main changes here are:
- addition of breadcrumb partial
- use of $focus-colour variable
- error message styles
- numeric tabular data styles
- larger radio button and checkbox inputs
Back links are also renamed.
> Update govuk elements scss files

- lib/template-config.js
- package.json
Update [the {{ mustache }} version of the govuk template](https://github.com/alphagov/govuk_template_mustache) from 0.13.0 to 0.15.0, this includes the following changes: 
- Fix copyright logo in Ruby version
- Add print specific logo styles
- Fix jumping logo on hover
- Drop Windows Safari font printing workaround as the font is no longer
used in print
- Update the logo to print black-on-white instead of white-on-black
- Stop copyright entity being escaped in Jinja template
- Update Crown Copyright link to new URL
- Update the font-files and move woffs into CSS
- All user-visible text in the template can now be overridden. Some
template languages which don't support default values (such as plain
mustache) will therefore lose that text and require you to handle
supplying the default.
Also …
> Update govuk template mustache to 0.15.1

- app/assets/sass/application.scss
Since we’re encouraging cutting and pasting from elements for
prototyping, update this classname to match the one used in the GOV.UK
elements phase banner snippet.
> Update phase banner and tag classnames

- lib/template-engine.js
As suggested by @joelanman in comments of #10 
'os.platform' didnt work in if statement, but 'process.platform' did
> #10 fix page layout in Windows

- start.js
The existing clean-up process made some flawed
assumptions which resulted in the following error
when ctrl-c was pressed:
```
Fatal error: ENOENT: no such file or directory, open '/Users/../govuk_prototype_kit/.start.pid'
```
This command spawns 3 child processes:
- a grunt watch task
- nodemon
- the `node server.js` command spawned by nodemon
The existing approach made an assumption that the
SIGINT event would only be called for the parent
process when, in fact, it was called for each
process (4 in total). The code that ran needed the
`.start.pid` file to exist so only worked the
first time, after which it had been removed.
This approach instead kills each process called by
SIGINT within the scope of that process instead of
relying on a reference external to that scope.
Note: This fix is …
> Alter process clean-up to not use pid file

- README.md
Following a discussion on the prototype-kit Slack channel, add instructions on how to run multiple instances of a prototype on your local machine.
> Add instructions for running multiple local instances

- app/assets/sass/elements.scss
- app/assets/sass/elements/_components.scss
- app/assets/sass/elements/_details.scss
- app/assets/sass/elements/_panels.scss
Adjust spacing for idented panels.
Add .govuk prefixed box styles - to be used for transaction end pages.
If this can be merged before #35, that PR can use the `.govuk-box-highlight` styles for the transaction end page.
Also, there is an example of the transaction end page here:
http://govuk-elements.herokuapp.com/colour/#examples
@rivalee, @joelanman, @timpaul.
> Update govuk elements

- app/assets/javascripts/application.js
- app/assets/javascripts/govuk/selection-buttons.js
- app/views/examples/elements/radio-buttons-checkboxes.html
- app/views/examples/index.html
- app/views/includes/elements_scripts.html
- app/views/includes/scripts.html
This adds selected and focused states to the parent label wrapping a
radio button or checkbox.
Create an example page for radio buttons and checkboxes to show how this works.
Link to the example page from the index page.
> Add selection buttons js from the front end toolkit

- app/views/examples/elements/forms.html
- app/views/examples/elements/grid-layout.html
- app/views/examples/elements/typography.html
- app/views/includes/elements_head.html
- app/views/includes/scripts.html
This PR expects that #57 has been merged first. 
All example pages now use the same layout template, header and scripts includes.
The details summary polyfill is moved to the scripts include, so will be available to all templates.
> Set example pages to use the same template

- app/views/examples/confirmation.html
Two small changes: 
1. Removed service name H1 following discussion on Slack, as the emphasis on this page should not be on the service title (at least not as an H1)
2. Added a feedback link: "What did you think of this service? (takes 30 seconds)"
> Remove H1, add survey link

- app/assets/sass/elements/_forms.scss
Amend the border for form controls
- this is now 2px wide and a darker grey
Also adjust the spacing for paragraphs in-between radio buttons or
checkboxes.
cc. @rivalee.
> Update govuk elements form styles

- app/assets/javascripts/application.js
- app/views/examples/elements/toggled-content.html
- app/views/examples/index.html
This PR adds the the js for toggling content from govuk elements.
The label of the checkbox or radio button (for which the additional content should be shown) must have a data-target attribute, which is the same as the ID of the hidden content. 
An example page demonstrates how this works. Screenshot below.
This fixes #51.
> Add js for toggled content

- app/views/examples/index.html
- Add a grid row wrapper
- Place content in a 2/3 width grid column
Also trim trailing whitespace and use a two-space indent.
Before:
After:
> Add grid layout wrappers to the example page

- lib/template-config.js
Add a default cookie message to layout.html to match what GOV.UK uses. Rather than a blank blue bar on first load, users will now see a cookie message.
Before:
After:
> Add default cookie message from GOV.UK to layout.html

- CHANGELOG.md
- README.md
- app/views/examples/index.html
- app/views/index.html
- docs/README.md
- docs/making-pages.md
- docs/principles.md
- docs/writing-css.md
For consistency, use the phrase 'prototype kit' instead of 'prototyping kit' or 'prototyping app'.
> Change 'prototyping' to 'prototype'

- docs/deploying.md
- lib/utils.js
- package.json
- server.js
This pr provides a more helpful error message if users have not set a username or password on production.
Changes:
* Display error message if username or password not set in production (rather than exiting)
* Move to `basic-auth` rather than `basic-auth-connect` which is depreciated.
* Add config var to let users enable or disable auth
* Update docs.
fixes #91
> Improve authentication guidance and error messaging

- README.md
- package.json
I got caught out when running a prototype app as I expected `npm start` to work - but `start` defaults to running `server.js`.
This project has a `server.js`, so there's no error - but the grunt part is skipped and the asset build never runs.
I figure it should be safe to add this config into the `package.json` so no-one gets caught out by this in the future - the existing `node start.js` still works as before.
> Use npm start as the standard way to run the app

- docs/deploying.md
This improves the docs for the case where a user has more than one heroku remote and will need to specify it when setting config vars.
Fixes #110
> Improve docs for case where there are multiple remotes

- app/config.js
- app/views/includes/propositional_navigation.html
- app/views/index.html
- server.js
Copied from #97:
This PR creates a new config.js file for storing configuration that users may want to edit.
Currently, users can edit:
Service name - used in the header
Port
Whether auth is enabled or not.
NB - I've not mentioned the config file in any docs - not sure where it would go. However, the default service name points the user at the location of the file to edit.
> Create config file that stores prototype configuration

- app/assets/sass/application.scss
- app/views/includes/phase_banner_alpha.html
- app/views/includes/phase_banner_beta.html
This PR adds two new includes for the alpha and beta phase banners, [using the snippets provided as examples by govuk elements, seen here](http://govuk-elements.herokuapp.com/alpha-beta-banners/).
> Add phase banner includes

- .travis.yml
Automatically deploy the app to Heroku using Travis after a successful
build.
cc. @timpaul, @tombye, @joelanman.
> Use Travis to deploy master to Heroku

- package.json
The changes to govuk elements in #124, require the the most recent version of the govuk frontend toolkit - as the breadcrumb styles were moved to a new mixin in `design-patterns/breadcrumbs`.
From the GOV.UK frontend toolkit's changelog.
- Add breadcrumb styles, separator images and documentation (PR #236)
- Add fallback image for the back link (PR #235)
- Find and auto-start JavaScript modules from markup:
`data-module="module-name"`(PR #227)
- Add helpers partial for functions
- Add px to em function and documentation
- Allow javascript error tracking to be filtered to avoid noise from
plugins
> Bump the govuk frontend toolkit to 4.6.0

- .gitignore
For those that might be using [tmuxp](http://tmuxp.readthedocs.org/en/latest/) and want to include the config dotfile in the project directory.
> Adds tmuxp config files to the gitignore

- package.json
This allows any version of node greater than, or 4.0.0
This fixes #139.
> Fix warning for npm engine

- app/config.js
- app/views/layout.html
- server.js
This PR adds a default cookie message to `config.js`. We added this a while back but it seems to have disappeared.
Before:
After:
> Add default cookie message

- create-release-tag.sh
There's no other way to get the correct branch name.
> Use TRAVIS_BRANCH when running in travis-ci

- .travis.yml
- lib/govuk_template.html
- package.json
- Update the govuk template to 0.16.4
- Remove napa as a dependecy
From the [GOV.UK template](https://github.com/alphagov/govuk_template) changelog.md
```
- Fix publish the Jinja version of the template with a `package.json`
for those
consuming it with NPM
- make the Django version of the template into a proper Python package
- publish the Jinja version of the template with a `package.json` for
those
consuming it with NPM
- more static assets added to `assets.precompile` to improve
compatibility with apps running rails > 4.2.5
- Fix colour of logo when in `:active` state
```
> Update the GOV.UK template and remove napa as a dependency

- .gitignore
- lib/utils.js
- start.js
fix port restart issue #148
when a new port is automatically chosen, it's stored in a file: `/port.tmp`
when the kit restarts on a file change, it looks for the port here first
when the kit is closed (`ctrl+c`) the `port.tmp` file is deleted.
> fix port restart issue

- docs/install/install-the-kit.md
- docs/install/run-the-kit.md
Three minor corrections:
* Fix typo in guidance
* Add note that `WARN`s in npm install are ok.
* Force new window on the link to the prototype.
> Minor documentation update

- lib/utils.js
previously it could be a string, and when PortScanner does `port + 50` it would do a string addition (300050)
> always convert port to Number

- app/views/layout.html
- server.js
This pr adds two things:
* Insert a comment in to the html of the `layout.html` view identifying the kit and version
* Log a message to the console at run time identifying the kit and warning users not to use it for production.
NB: I'm using the version number from package.json - I think this gets updated automatically?
> Have kit self-identify as being the GOV.UK Prototype kit

- docs/install/introduction.md
The link wasn't working without the .md suffix.
> Fix link to developer install instructions

- docs/guides/publishing-on-heroku.md
- lib/utils.js
> Fix broken url and typo

- server.js
Prototypes should never be indexed by search engines. 
This serves PR does two things:
* Serves a `robots.txt` file that disallows search index indexing.
* Sets `X-Robots-Tag` to `noindex`. This should stop pages getting indexed if they're being linked to by an indexed page.
Fixes #166 
Note: I've tested the robots file, but unsure how to test the `X-Robots-Tag`. It appears in the headers, but haven't found a tool that will verify it's actually doing what it should.
> Stop prototypes being indexed by search engines.

- server.js
This PR redirects urls that end in `.html` or `.htm` to the same url with the extension removed.
This should improve the situation where a user sees a path / filename somewhere else and attempts to visit that in the browser.
Fixes #102
> Redirect .html and .htm if in url path

- app/views/examples/start-page.html
This is causing the repetition of the .bold-xsmall link, which is breaking the OGL logo in the footer.
Adding the missing `>` fixes #167.
> Fix closing </span> element

- package.json
- Allow New Transport font stack to be overridden by apps using
$toolkit-font-stack and $toolkit-font-stack-tabular
This will mean there's a much nicer way to override New Transport for the "Unbranded" layout.
> Bump govuk frontend toolkit to 4.10.0

- docs/writing-css.md
I've removed a lot of technical information about node-sass which is mostly out of date. This means the useful stuff about what sass is, and how to edit `application.scss` is clearer
> Edit sass docs for clarity

- app/config.js
- app/views/examples/start-page.html
- app/views/index.html
- lib/utils.js
- server.js
This redirects requests to https. 
Heroku has SSL built in, so for most prototypes, things should work as normal, except with SSL.
Note: I think this is a breaking change, since it requires production servers to have HTTPs set up.
> Force SSL on production

- README.md
- docs/guides/publishing-on-heroku.md
change security guidance to make username and password mandatory - to prevent members of the public finding prototypes and thinking they're real services
> Security guidance

- docs/guides/publishing-on-heroku.md
Make windows heroku instructions clearer, and move them to where you're more likely to need them.
Relates to this issue: https://github.com/heroku/cli/issues/84
> Windows heroku login instructions

- app/filters.js
- lib/core_filters.js
- server.js
Clean PR to merge the basic functionality of adding custom filters to the nunjucks template engine used by the gov.uk prototyping kit.
```lib/core_filters.js``` is where I propose any future filters we want to include within the kit live. Which could be for example @edwardhorsford's proposed [standard date filter](https://github.com/alphagov/govuk_prototype_kit/issues/170)
```app/filters.js``` is where bespoke filters for each instance of the kit would live (where users will add their own filters).
cc: @joelanman
> Adds custom 'filters' to the nunjucks templating engine

- lib/utils.js
- package.json
- server.js
This PR is to replace #144 and #149 but still in response to issue #84.
After discussion with @joelanman I've reverted to adding a callback to the `findAvailablePort` function and then start browser-sync in server.js (or not if in 'production'). I've also incorporated Joe's updated browser-sync config options into this new PR.
(Only tested on MacOSX 10.11.4 so far though)
> Adding browser-sync to the prototyping kit.

- package.json
- Increase button padding to match padding from GOV.UK elements (PR
#275).
If you have UI which depends on the padding set by the button mixin in
the frontend toolkit and this is not overridden by button padding set
by GOV.UK elements, this change will affect it.
- Remove the GDS-Logo font-face definition (PR #272)
- Move the @viewport statements to govuk_template (PR #272). 
**If you upgrade to this version of govuk_frontend_toolkit and you’re also using
[govuk_template you’ll need to upgrade that to at least 0.17.2](https://github.com/alphagov/govuk_prototype_kit/pull/206) to
maintain compatibility with desktop IE10 in snap mode.**
> Bump the govuk frontend toolkit to 4.12.0

- package.json
Use release 1.2.0 of the govuk-elements-sass package.
> Use release 1.2.0 of the govuk-elements-sass package

- Gruntfile.js
- package.json
Remove the mustache version of the govuk_template, this isn't required in addition to the Jinja package.
This fixes #198.
> Remove the mustache version of govuk template

- docs/install/requirements.md
The latest version of Node will change frequently. Rather than having to update this documentation every time it changes, we can just explain that the kit works with any version since 4.3.0.
> Remove references to "latest version" of Node

- docs/README.md
- docs/session.md
- package.json
- server.js
this is basic functionality that provides some value, and is good groundwork for providing an auto-data-passing solution later on
> add session support

- package.json
The Jinja version of the GOV.UK template is now published to npm,
update package.json.
> Use the govuk template jinja npm package

- package.json
- Make headings block-level by default. If you are styling elements you
want to be inline with heading includes, you’ll need to explicitly make
them inline in your CSS.
> Use version 4.13.0 of the govuk frontend toolkit

- package.json
- Fix tabular number sizing in Firefox ([PR
#301](https://github.com/alphagov/govuk_frontend_toolkit/pull/301))
- Allow use of multiple GA customDimensionIndex. See [this
section](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/
docs/javascript.md#using-google-custom-dimensions-with-your-own-statisti
cal-model) of the documentation for more information.
- Configurable duration (in days) for AB Test cookie. See [this
section](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/
docs/javascript.md#multivariate-test-framework) of the documentation
for more information.
- Allow base scripts to run within a module loader. See [this
PR](https://github.com/alphagov/govuk_frontend_toolkit/pull/290) for
more information. …
> Bump govuk frontend toolkit to 4.14.1

- package.json
[0.18.0](https://raw.githubusercontent.com/alphagov/govuk_template/master/CHANGELOG.md)
- Publish the Jinja version of the template to NPM
- Update HTML5 Shiv to the latest version
- Remove an errant font loader script that was only being used for IE8
> Bump govuk template to 0.18.0

- package.json
Use version [4.15.0](https://github.com/alphagov/govuk_frontend_toolkit/commit/620c7
fdb1eca75cfb7a8c076cafcf50852a85008) of the GOV.UK frontend toolkit.
- Add support for Google Analytics fieldsObject
- anchor-buttons.js: normalise keyboard behaviour between buttons and
links with a button role
> Bump govuk frontend toolkit to 4.15.0

- docs/updating-the-kit.md
Adds documentation for upgrading kits via the command line with git. Thoughts? Please check and proof read.
> Adds documentation for upgrading the kit via the command line

- app/views/index.html
We already log this version to the console when the app is run and it is included in a comment
at the bottom of each page. 
Add the release version above the title on the index page.
This will also make it easy to see that the [kit when deployed to Heroku is up to date](http://govuk-prototype-kit.herokuapp.com/).
This fixes #121.
> Show the current release version on the index page

- package.json
https://github.com/alphagov/govuk_template/blob/master/CHANGELOG.md
Remove gov.uk prefix from relative links when printing (PR #234)
Fix a .visually-hidden bug on GOV.UK (PR #177)
> Bump govuk_template_jinja to 0.18.1

- .travis.yml
- CONTRIBUTING.md
- Gruntfile.js
- README.md
- app/assets/javascripts/application.js
- app/assets/javascripts/details.polyfill.js
- app/assets/javascripts/govuk/selection-buttons.js
- app/assets/javascripts/jquery-1.11.3.js
- app/config.js
- app/filters.js
- app/routes.js
- docs/linting.md
- lib/core_filters.js
- lib/utils.js
- package.json
- server.js
- start.js
Depends on:
This PR is an open discussion on the topic of using a JavaScript linting tool across our codebases.
I throw my hat in the ring by suggesting [standard](https://github.com/feross/standard) and demonstrating with this PR how an implementation would work for a node project.
Code was automatically converted using https://github.com/maxogden/standard-format.
We already have [govuk-lint](https://github.com/alphagov/govuk-lint) whose responsibility it is to handle linting concerns, and I'd love to hear what our thoughts are on relying on that instead.
> [RFC] Lint codebase using standard

- app/assets/javascripts/application.js
- app/views/includes/scripts.html
Include a script from the govuk frontend toolkit to shim anchors with
`role="button"` to be 'clicked' via the space key.
For context, here is the PR adding this script to the govuk_frontend_toolkit.
https://github.com/alphagov/govuk_frontend_toolkit/pull/297
> Include the shim-links-with-button-role.js script from the govuk_frontend_toolkit

- package.json
- Fix error in IE - remove trailing comma from shimLinksWithButtonRole
JavaScript ([PR
#323](https://github.com/alphagov/govuk_frontend_toolkit/pull/323)).
> Use version 4.18.1 of the govuk_frontend_toolkit

- package.json
- Degrade gracefully when external JS can’t be loaded ([PR
#248](https://github.com/alphagov/govuk_template/pull/248))
> Bump govuk_template_jinja to 0.18.2

- package.json
- Remove unnecessary print font fallback that causes regression
downstream ([PR
#328](https://github.com/alphagov/govuk_frontend_toolkit/pull/328))
> Update the govuk_frontend_toolkit to 4.18.2

- package.json
Logo fixes: Fix logo breaking layout when increasing font size, fix
invalid or non-standard CSS and remove obsolete CSS around logo, adjust
logo dimensions slightly (PR #237)
> Bump govuk_template to 0.18.3

- Gruntfile.js
The generated css will now include source comments which show where in 
your sass files each css block comes from.
Also tidied up the options block:
- The `style` option is not supported by grunt-sass (`outputStyle` is the  correct option)
- `sourceMap` was misspelt and wasn’t generating the source maps
- The options have been arranged in alphabetical order to make it easier 
to read
Example source comments:
```css
/* line 18, govuk_modules/govuk_frontend_toolkit/stylesheets/_grid_layout.scss */
#content {
max-width: 960px;
margin: 0 15px;
}
@media (min-width: 641px) {
/* line 18, govuk_modules/govuk_frontend_toolkit/stylesheets/_grid_layout.scss */
#content {
margin: 0 30px;
}
}
```
> Make css output easier to debug

- update-release-branch.sh
This is failing as it was using --force-with-lease, instead force push the 'latest-release' branch.
> Force push the latest-release branch to GitHub

- docs/updating-the-kit.md
Updated the documentation to refer to the freshly created 'latest-release' branch. Addresses issue: [269](https://github.com/alphagov/govuk_prototype_kit/issues/269)
> Updated documentation - Updating via Git

- app/assets/javascripts/application.js
Add a warning that gets printed to the console on the client side about not using the kit for production.
I've set it to only show once per session (using sessionStorage). This should hopefully strike a balance between being visible enough and not being too annoying.
Based on suggestion from @nickcolley
> Add warning to console about prototype kit usage

- app/assets/sass/application.scss
- app/assets/sass/unbranded.scss
- app/views/layout_unbranded.html
Create a new stylesheet for the unbranded page and include this in the unbranded layout.
This way the $toolkit-font-stack variable can't affect any other files.
This fixes #256.
> Fix toolkit font stack overrides

- package.json
- For smaller screens (<768px) ensure that the
GOVUK.StickAtTopWhenScrolling JS "unsticks" the element which was
previously "stuck" (by removing both the class which sets fixed
positioning and the shim). ([PR
#329](https://github.com/alphagov/govuk_frontend_toolkit/pull/329))
> Bump govuk_frontend_toolkit to 4.18.3

- server.js
To match the vars above where this has been removed.
> Remove path.join(__dirname,) in server.js

- app/assets/javascripts/application.js
- app/views/includes/scripts.html
Remove the ShowHideContent function, instead replace with
GOVUK.ShowHideContent JS.
GOVUK.ShowHideContent was added to the [govuk_frontend_toolkit in v4.18.0](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/CHANGELOG.md#4180)
> Remove duplicate JS,  that now exists in the govuk_frontend_toolkit

- lib/govuk_template_unbranded.html
This removes a bunch of old workarounds from the head, and adds a fallback handler to the bottom of body.
Also, remove the default title as it’s branded.
> Update unbranded template to match latest

- lib/utils.js
The error page that's displayed when you don't provide a heroku username and password goes to a 404 page. This PR updates that link.
> Updating the link to the 'Publishing on Heroku' docs

- lib/utils.js
Fixes the link to guidance to setting username and password and instead links to the deployed docs on heroku.
> Fix broken link and link to deployed docs

- package.json
Bump govuk_frontend_toolkit to 4.18.4
https://raw.githubusercontent.com/alphagov/govuk_frontend_toolkit/master
/CHANGELOG.md
- Lint codebase using standard
- Add semicolons at the start of IIFE's
> Bump govuk frontend toolkit to 4.18.4

- update-release-branch.sh
If it does, don't update the latest-release branch.
Otherwise, if the version number has changed - update the latest release branch.
> Get Travis to check if the version number matches the tag number

- package.json
This release includes two breaking changes:
- Removal of external link styles and icons, if you are using the external-link-* mixins you will need to remove them from your codebase  ([PR #293](https://github.com/alphagov/govuk_frontend_toolkit/pull/293))
- Correct spelling of the 'accordion' icon, you will need to check for the incorrect spelling 'accordian' and update if you are using this icon ([PR #345](https://github.com/alphagov/govuk_frontend_toolkit/pull/345))
And two minor changes:
- Amend GOVUK.StickAtTopWhenScrolling to resize the sticky element and shim when the .js-sticky-resize class is set ([PR #343](https://github.com/alphagov/govuk_frontend_toolkit/pull/343))
- Allow custom options in GOVUK.analytics.trackPageview …
> Remove external links: bump govuk_frontend_toolkit to 5.0.0 and govuk_template to 0.19.0 and govuk_elements_sass to 2.1.0

- package.json
- start.js
This means:
- node_modules check runs correctly regardless of OS, because its done in Node
- gulp logs correctly
- we dont copy and paste lots of code from gulp in order for it to log correctly
- nothing else is broken (crosses fingers)
> Run gulp as child process with logging

- package.json
- start.js
child.spawn has problems on windows, the cross spawn npm package fixes these
> use cross-spawn to fix spawn on windows

- docs/documentation/install/developer-install-instructions.md
- docs/documentation/install/requirements.md
- package.json
6 is the new LTS version of Node - this PR updates package.json and the documentation
fixes #288
> Change node version from 4 to 6

- .travis.yml
- gulp/tasks.js
- package.json
- server.js
- test/mocha.opts
- test/spec/sanity-checks.js
based on @andymantell's PR (#292)
this moves the tests from Grunt to Gulp
> Basic sanity check test suite

- docs/README.md
The current readme is out of date and links to 404s.
Instead link to the documentation app.
> Update readme to point to docs app

- lib/utils.js
This can be seen when viewing the docs app locally:
`http://localhost:3000/docs`
```
file path is: /govuk_prototype_kit/docs/documentation/making-pages.md
file path is: /govuk_prototype_kit/docs/documentation/setting-up-git.md
```
This was added to debug the links to markdown files in the documentation app, remove these lines.
> Remove console log for the file path

- docs/documentation/updating-the-kit.md
- package.json
Closing #286 in favour of this PR.
This amends the changes made by @paulmsmith in #286 - Adds additional step to the documentation for users to run `npm install` as a first pass at fixing any post updating errors.
and makes the documentation consistent with the instructions given already in the docs app.
> Update "Updating the Kit" Documentation

- docs/views/includes/analytics.html
- docs/views/includes/head.html
- server.js
This pr amends #320 and works on #322 so that tracking code tied to the app. We don't want other users of the kit to use our tracking code - they should use their own if they want tracking.
Since tracking codes are deploy specific, it's better if it comes from environment.
This pr:
* Moves tracking snippet to an include
* Pulls a tracking code out of env
* Only sets tracking code if it exists
> Make analytics non-deploy specific

- docs/views/includes/head.html
- server.js
currently the google analytics code runs locally, which is not correct. This PR uses the promoMode variable to ensure it only runs when in promoMode (on heroku)
> Google analytics local fix - only run in promo mode

- app/views/includes/phase_banner_alpha.html
- app/views/includes/phase_banner_beta.html
- package.json
This makes the phase tag in the phase banner `$govuk-blue`.
As the phase banner is now the same for both alpha and beta banners,
change the phase banner includes to use the recommended class
`.phase-banner`.
(This will fail until the PR for govuk_elements bumping the version to 2.2.1 is merged).
> Bump govuk-elements-sass to 2.2.1

- .travis.yml
It looks like Travis is deploying the latest-release branch to Heroku.
Let’s move the script that checks for a version tag to after_deploy, in
the hope that it won’t interfere with the deployment of master to Heroku on a
successful build.
> Set travis to update the latest release branch after deployment

- package.json
- Increase skiplink colour contrast ([PR#263](https://github.com/alphagov/govuk_template/pull/263))
- Have focus outline appear outside of element rather than covering it
in Safari and Chrome ([PR#259](https://github.com/alphagov/govuk_template/pull/259))
> Bump govuk template to 0.19.2

- app/config.js
To match the change made to GOV.UK elements: https://github.com/alphagov/govuk_elements/pull/389 by @robinwhittleton.
> Remove the title attribute from the cookie message

- server.js
This solves the problem with prototypes asking for username/password twice.
The problem is caused by the ordering in the middleware. When a user types in the URL for a prototype like http://govuk-tagging.herokuapp.com they're asked for a username/password first (via `utils.basicAuth`).
After filling that in they'll be able to "proceed" to the next step, which redirects them to the `https://` version (via `utils.forceHttps`). Because the auth isn't shared between `http` and `https` version, they are not authenticated anymore and have to enter their username/password again.
Validated with http://test-prevent-double-auth.herokuapp.com/
```
@tijmenb ~/govuk/govuk_prototype_kit on prevent-double-auth $ curl -I http://govuk-tagging.herokuapp.com/
HTTP/1.1 401 Unauthorized
```
```
@tijmenb …
```
> Prevent asking users to authenticate twice

- test/spec/sanity-checks.js
It's worth testing for /docs as it's served by a different app, with its own template structure.
This would have caught the recent bug that broke the prototype kit site (99b145d61af)
> Add test for docs page

- server.js
> Allow search indexing in promo mode

- docs/documentation/install/introduction.md
this fixes #339, and another broken link on that page to the developer install instructions
> fix docs links

- docs/documentation/install/install-the-kit.md
> fix download link

- package.json
Currently when deploying the Gov UK prototype kit to AWS using their Linux node AMI with nodeJs `6.9.1` the [node-sass](https://github.com/dlmanning/gulp-sass/blob/218560fc06f6e94151fb5ec3a4e0e047415c14ed/package.json#L26) dependency of `gulp-sass` `v2.3.2` is incompatible with nodeJs 6 and Linux [node-sass/releases/tag/v3.4.2](https://github.com/sass/node-sass/releases/tag/v3.4.2)
To enable this to work we need to bump `gulp-sass` to `v3.0.0` that has [node-sass](https://github.com/dlmanning/gulp-sass/blob/0d2a2bffb679667b302259bce4d389c9d3dcd975/package.json#L26) `v4.0.0` which [is supported](https://github.com/sass/node-sass/releases/tag/v4.0.0) on Linux with nodeJs 6
> bump gulp-sass to increase node-sass dependency

- package.json
Update the govuk_frontend_toolkit to include the following changes:
- Update the alpha, beta and discovery colours to $govuk-blue to match
the updated phase banner ([PR #370](https://github.com/alphagov/govuk_frontend_toolkit/pull/370))
- Fix radio button show/hide behaviour when used outside a form ([PR #375](https://github.com/alphagov/govuk_frontend_toolkit/pull/375))
- Fix a "Stick at top when scrolling" component bug related to scroll
anchoring in Chrome 56+ ([PR #376](https://github.com/alphagov/govuk_frontend_toolkit/pull/376))
- Minor travis fixes ([PR #373](https://github.com/alphagov/govuk_frontend_toolkit/pull/373))
- Allow custom options when tracking events ([PR #365](https://github.com/alphagov/govuk_frontend_toolkit/pull/365))
- Change HMRC and DEFRA text colours for …
> Bump govuk_frontend_toolkit to 5.1.1

- app/config.js
- server.js
Every time I make a new prototype I have to keep deleting out the browser sync code. I've added an option to the config file to make disabling it much easier in future. It's left enabled by default so there is no change to the way the kit works out the box.
> Added config to turn off browser sync

- app/assets/javascripts/auto-store-data.js
- app/config.js
- app/views/includes/scripts.html
- app/views/layout.html
- docs/views/examples/pass-data/index.html
- docs/views/examples/pass-data/vehicle-check-answers.html
- docs/views/examples/pass-data/vehicle-features.html
- docs/views/examples/pass-data/vehicle-registration.html
- docs/views/examples/pass-data/vehicle-type.html
- docs/views/includes/scripts.html
- docs/views/layout.html
- docs/views/tutorials-and-examples.html
- lib/prototype-admin/clear-data.html
- lib/utils.js
- server.js
this updates #214 Auto data session 3 so it can be merged - copied from that PR:
This version of automatically storing and showing data across pages does not rely on macros, but instead using the `checked` function directly (see examples below). I'm not sure it's as user-friendly as the version with macros, but it may take a while to finalise our approach to macros.
This will make the kit automatically store all data from forms, for use later in your prototype.
For example if you have an input like this:
```
<input name="first-name">
```
You can put this on the next page, or any other page:
```
<p>Hello {{data['first-name']}}</p>
```
To populate a text field with the value a user entered is simple:
```
<input name="first-name" value="{{data['first-name']}}">
```
To set radios or …
> Auto data session 4

- docs/views/examples/template-content-page.html
- docs/views/examples/template-question-page-blank.html
- docs/views/tutorials-and-examples.html
Add two new template pages to the kit.
For links (back links, action urls, etc), I've gone with `href="/url/of/previous/page"`. Does this seem correct?
These templates work with #340 and start moving us towards using POSTs. That PR should probably get merged first.
A basic content page - useful for things like:
* eligible / ineligible pages
* 404 / error pages
Looks like:
A basic question page, containing:
* Heading
* Continue button
* Form element with POST method
Will be useful for people grabbing snippets from Elements.
Looks like:
> Add template pages for content and questions

- app/views/layout.html
add `page_scripts` and `scripts` blocks - to allow people to add new scripts, or replace all scripts, on a per-page basis
> add page_scripts block

- app/assets/javascripts/bind.js
- app/views/includes/scripts.html
- docs/views/includes/scripts.html
bind.js taken from govuk frontend toolkit. Condition added to use this file if the browser is IE 8 or less.
Fixes #348.
> Add IE 8 bind polyfill

- .gitignore
- lib/template.env
- package.json
- server.js
- start.js
Add a `.env` file for storing private data. 
This is created from a template - so the real `.env` doesn't get committed to git.
This will be useful for teams integrating with APIs - like Notify.
> Add .env file to support storing private data

- app/assets/sass/patterns/_check-your-answers.scss
- docs/views/examples/check-your-answers-page.html
This makes markup, styling and content improvements to the 'Check your answers' page.
The markup was changed from a table to a description list.
We initially tried multiple variants which all looked and behaved the same and tested all of them in various assistive technology for potential accessibility issues:
* table (but not the one that is currently in the prototype kit)
* description list (`dl`)
* list (`ul` or `ol`)
We found that they all work nearly equally well and all have pros and cons. The main reason for deciding to use a description list was that it seems to be the most semantic in this case (although the others are not unsemantic). Although description lists have varying support in screen readers, the context made it still easy enough to understand and navigate.
Please note, …
> Improvements to Check your answers page

- app/assets/javascripts/application.js
Safari in Private Browsing mode sets a session storage quota of 0 which means that attempts to write to it result in a QuotaExceededError being thrown, breaking JavaScript on the rest of the page.
The existing code is flawed in that it sets `prototypeWarning` to true but tests for 'false', so the warning is already shown on every page anyway.
As such, this simplifies it to remove the use of session storage entirely.
> Fix JS error in Safari’s Private Browsing mode

- app/assets/sass/patterns/_check-your-answers.scss
To ensure we support existing prototypes using the old check your
answers pattern - where using a table was recommended, add the styles
back in - but mark these as deprecated.
These were removed in #365.
As the new check-your-answers styles are namespaced using `.govuk-` these are opt-in, so we
can release without making a breaking change.
In future, we can remove `.check-your-answers`, the next time we make a
breaking change to the prototype kit.
> Support deprecated check-your-answers table styles

- LICENCE.txt
Also, it should include the title "The MIT License" so people can see what it is. See our guidance: https://github.com/alphagov/styleguides/blob/master/licensing.md
> Copyright should be Crown Copyright

- package.json
- Fix the Django package – ensure setuptools uses the MANIFEST.in by setting the include_package_data flag to True, and fix a broken download link ([PR #319](https://github.com/alphagov/govuk_template/pull/319)).
> fix(package): update govuk_template_jinja to version 0.22.3

- docs/documentation/install/requirements.md
Move to recommending users use Atom over Sublime text.
Reasons for the change:
- Atom is more fully featured out of the box
- Atom is free / does not nag.
I've done a search across the repo and we only mention recommending Sublime on this one page. The only other page that mentions Sublime gives instructions for linting with it, which I think is still a useful instruction to give.
> Recommend Atom over Sublime text

- .travis.yml
Automatic deploys are enabled in Heroku for this app, so this section can be removed from travis.yml.
Add a comment in Travis.yml where the deploy section is removed, to explain when the app is deployed.
> Remove the Heroku deploy provider from Travis

- .gitignore
- .npmrc
Currently after `npm install`, npm tells users that a package-lock file has been created and they should commit it. This functionality has caused problems for many people, including our own projects at GDS.
This PR disables package lock, so npm continues to function in the way it has in the past.
See more here: https://codeburst.io/disabling-package-lock-json-6be662f5b97d
> Disable package-lock.json

- .travis.yml
Stop testing against Node 4.0, and test against the latest LTS instead.
> Update testing matrix to test against latest LTS

- lib/utils.js
- server.js
1. Moves the `checked` function from server to utils
2. Uses `this.ctx` to access `data` instead of going via the session. This is a simpler approach and means we don't need to use middleware
> Refactor checked function into utils, remove need for middleware

- server.js
This code runs twice - once for all apps, then again in the check for `promoMode`. I've deleted the first instance.
https://github.com/alphagov/govuk_prototype_kit/blob/master/server.js#L174-L184
> De-duplicate code to stop search indexing

- docs/views/includes/tracking_body.html
- docs/views/includes/tracking_head.html
- docs/views/layout.html
- server.js
Adding Google Tag Manager as per Design System [Trello ticket](https://trello.com/c/47shVijF/404-implement-google-tag-manager-on-the-prototype-kit)
Follows current analytics implementation, gtm code added to heroku config vars
> Add Google tag manager tracking

- docs/views/includes/head.html
At the moment when you search for the kit online the description is not very useful.
This adds a meta tag to ensure a defined description is shown.
As part of https://trello.com/c/87WZ8ffS/212-fix-prototype-kit-description-in-google
> Add meta description for better descriptions in Google

- CHANGELOG.md
- docs/views/includes/analytics.html
- docs/views/includes/head.html
- server.js
This already is covered by Google Tag Manager
Closes #490
> Remove redundant Google Analytics

- docs/documentation/install/requirements.md
Improves our installation guidance.
* Clearer heading that relates to the content
* Mentions MSC as a route for GDS staff to get the software.
> Improve installation guidance on software required

- CHANGELOG.md
- docs/assets/sass/docs.scss
- docs/views/cookies.html
- docs/views/layout.html
- docs/views/privacy-policy.html
- server.js
This PR replicates the (already merged) Cookies and Privacy policy pages on the beta version of the prototype kit.
This change:
- Adds a cookies page
- Adds a privacy policy page
- Add links to cookies and privacy policy on the footer for the website (They will not appear in the footer for prototypes created with the kit)
- Creates a link to the cookies page in the cookie banner when in promo mode
In addition there are some docs specific styles for `table: fixed` and an override for `display: block` in order to style these pages in the same way as on the beta version of the kit and the design system.
> Add cookies and privacy policy pages

- CHANGELOG.md
- app/data/session-data-defaults.js
- docs/views/examples/pass-data/index.html
- lib/template.session-data-defaults.js
- lib/utils.js
- start.js
By @mikeshawdev
If provided, the app will try to merge data from a defaults file with data from the session. Defaults will only apply if there isn't a corresponding value already in the session, so data can be overridden within the prototype if necessary.
> Add default session data

- CHANGELOG.md
- docs/views/layout.html
- server.js
Adds a guard around Google Tag Manager script to prevent it from initialising,
for users who have indicated they do not want to be tracked.
Cherry picked from https://github.com/alphagov/govuk-prototype-kit-private-beta/pull/52
Closes https://github.com/alphagov/govuk_prototype_kit/issues/518
> Do not track users who have enabled 'DoNotTrack'

- CHANGELOG.md
- docs/assets/sass/docs.scss
Block code highlight is already in there, so just added inline-block highlight.
Fixes: https://github.com/alphagov/govuk_prototype_kit/issues/517
> Add inline-code-block styles

- CHANGELOG.md
- docs/views/tutorials-and-examples.html
`font-xsmall` > `govuk-body-s`
removed `class="text"`
> Update elements class to frontend on examples page

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- create-release.sh
- docs/documentation/install/install-the-kit.md
- docs/documentation/install/introduction.md
- docs/documentation/updating-the-kit.md
- lib/utils.js
For consistency, we are renaming the repository so want to avoid redirects.
> Update repo links from govuk_prototype_kit to govuk-prototype-kit

- docs/views/layout.html
- server.js
- changes `app.locals` to `res.locals` as Do not track is per request
- changes `false` to `False` in Nunjucks check as Nunjucks uses Python syntax
> Do not merge - Fix tracking

- docs/views/layout.html
Seems like the problem was just app.locals in the previous fix, not the syntax for false
> Fix tracking

- CHANGELOG.md
- package.json
This fixes an issue when deploying to CloudFoundry instances (such as GOV.UK PaaS) where the buildpack fails on the semver range:
```
-----> Nodejs Buildpack version 1.6.28
-----> Installing binaries
engines.node (package.json): >=8.9.1 <9.0
engines.npm (package.json): unspecified (use default)
**WARNING** Dangerous semver range (>) in engines.node. See: http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
**ERROR** Unable to install node: improper constraint: >=8.9.1 <9.0
Failed to compile droplet: Failed to run all supply scripts: exit status 14
```
Using `^8.9.1` instead which is semantically equivalent (any version greater than 8.9.1 but less than 9.0) allows the app to deploy successfully:
```
-----> Nodejs Buildpack version 1.6.28
-----> Installing binaries
engines.node …
```
> Specify node dependency using caret notation

- docs/views/index.html
- docs/views/layout.html
- Add data- tracking attributes to docs/index page
- Add data- tracking attributes to header navigation
Unfortunately at the moment we cannot pass data attributes to items, so we have to replace the Nunjucks macro with HTML.
Trello ticket: https://trello.com/c/PmXfI1BD/1156-add-data-attributes-for-tracking-to-prototype-kit-website
> Data tracking attributes to header navigation and docs homepage

- CHANGELOG.md
- docs/views/examples/pass-data/index.html
Passing of stored data to Nunjucks macros is something we've seen being asked about. 
This just adds the example code to the guidance, not replace the actual working example.
Addresses: #554 and #564
> Add example of passing data in Nunjucks macros

- CHANGELOG.md
- app/routes.js
- lib/utils.js
- server.js
This work has been pulled out of #553 as useful in its own right, and helps to prepare for that
- Use 'next' and middleware to handle errors, this is the [documented way to handle errors in Express](https://expressjs.com/en/guide/error-handling.html)
- Use console.error to output errors when rendering templates - these were previously hidden
- Serve the root index view with matchRoutes to be more consistent, no longer needs its own route
- Add missing content-type header to matchRoutes
> Improve error handling

- CHANGELOG.md
- docs/views/examples/template-question-page-blank.html
Link to the home page instead of the Question page pattern - people could need any of the components or patterns, not necessarily guidance on the Question page itself
> Update link from question page template to design system

- CHANGELOG.md
- app/views/layout.html
This change adds a line to the footer, which states the current version of the prototyping kit being used. Screenshot below.
This makes it clear to users which version of the kit is being used, as they don't need to check the console or source code for this information when using a prototype.
Resolves #455.
> Add kit version to footer

- CHANGELOG.md
- package.json
[GOV.UK Frontend v1.3.0 release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v1.3.0)
> Update GOV.UK Frontend to 1.3.0

- CHANGELOG.md
- server.js
Code in `route.js` may be looking for environment variables. If the environment variables aren’t loaded beforehand this will cause an exception.
I suspect this worked fine before https://github.com/alphagov/govuk-prototype-kit/commit/bbe15e8fa6d7ba75a7c09c0c5c2c0db7a2e55047#diff-78c12f5adc1848d13b1c6f07055d996e, which reordered the first lines in `server.js`.
This commit moves the loading of environment variables to before the requiring of any `routes.js` files.
> Load variables from .env before requiring routes

- CHANGELOG.md
- gulp/nodemon.js
Could be confusing why your changes aren’t having any effect.
Someone should probably test this before merging it 😬
cc @edwardhorsford
> Restart the app if environment variables change

- CHANGELOG.md
- docs/documentation/session.md
- docs/views/examples/pass-data/index.html
- lib/utils.js
- package.json
Hello!
We've got a service where we use the same nunjucks views to collect data for both claimants and optionally their partners.
E.g.
```html
<input name="claimant[field1]" value="Example 1">
<input name="claimant[field2]" value="Example 2">
<input name="claimant[field3]" value="Example 3">
<input name="partner[field1]" value="Example 1">
<input name="partner[field2]" value="Example 2">
<input name="partner[field3]" value="Example 3">
```
With this pull request `useAutoStoreData` will store the data correctly 👍 
```js
session: {
data: {
claimant: {
field1: 'Example 1',
field2: 'Example 2',
field3: 'Example 3'
},
partner: {
field1: 'Example 1',
field2: 'Example 2',
field3: 'Example 3'
}
}
}
```
i.e. Nicely grouped as `claimant` and `partner` as specified in the HTML.
We also regularly …
> Allow nested field values in session

- CHANGELOG.md
- app/config.js
- lib/utils.js
- package.json
- server.js
I'm currently working across two teams with long form journeys.
1. Enter lots and lots of form data
1. Reach the _Nth_ page in a journey
1. Edit a view or route
1. The prototype is restarted by nodemon
1. All typed in session data is now lost 😭 
I've added the following config:
```js
{
// Enable cookie-based session store (4KB limit, persists on restart)
useCookieSessionStore: 'false'
}
```
When set to `true` it swaps _express-session_ with  Mozilla _[client-sessions](https://www.npmjs.com/package/client-sessions)_ so retains compatibility with `req.session` and persists all session data in a cookie.
> Add config to allow permanent session in cookie

- CHANGELOG.md
- start.js
Previously the spawn command just took `gulp` as an argument, which worked when running the app via `npm start`. However, running `node start` would fail because it couldn't find `gulp`. It would look globally, whereas `npm start` would look locally. Referencing the path within `node_modules` directly means both commands can be used to start and run the app.
Resolves #393.
> Use path to gulp executable for spawn

- CHANGELOG.md
- package.json
Update GOV.UK Frontend dependency to the latest released version.
GOV.UK Frontend 2.0.0 is a breaking release. See [release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v2.0.0)
> Update GOV.UK Frontend to 2.0.0

- docs/views/index.html
Needs updating now that we have release version 8.
> Update wording on when Protoype Kit started using GOV.UK Frontend  instead of GOV.UK Elements

- CHANGELOG.md
- docs/views/layout.html
- package.json
- Update dependency
- Replace header plain HTML with a macro
> Update GOV.UK Frontend to v2.1.0

- CHANGELOG.md
- app/views/includes/head.html
- docs/views/includes/head.html
- docs/views/layout_unbranded.html
In GOV.UK Frontend components no longer have separate print stylesheet;
print styles are built into the component partials.
By setting media to all we allow those styles to apply in print situations.
Fixes: #604
Before: 
[before.pdf](https://github.com/alphagov/govuk-prototype-kit/files/2437168/before.pdf)
After: 
[after.pdf](https://github.com/alphagov/govuk-prototype-kit/files/2437170/after.pdf)
> Set stylesheet media to "all" to allow print styles

- docs/views/layout.html
[The relative link breaks on some pages](https://govuk-prototype-kit.herokuapp.com/docs/tutorials-and-examples). This PR makes it absolute.
> Fix About link in nav

- CHANGELOG.md
- app/views/layout.html
- package.json
- update to v2.2.0
- import the character-count component into app layout view
> Update GOV.UK Frontend to v2.2.0

- app.json
Required config to enable review apps on Heroku
Auto-generated by Heroku, but creating a pull request this way instead of auto-committing to master
As per https://devcenter.heroku.com/articles/github-integration-review-apps
Trello ticket: https://trello.com/c/XnrMzz0P/1512-setting-up-review-apps-on-the-prototype-kit
> Heroku review app config

- docs/views/tutorials-and-examples.html
Site previously referred to /docs/views/examples, which was incorrect, and confused me for a bit.
> Fix path for page templates in tutorials-and-examples

- CHANGELOG.md
- docs/documentation/using-notify.md
Adapted from: https://gist.github.com/quis/1136d255a5cdc47f4b72bc5bf234cf97
> Add Notify integration guidance

- CHANGELOG.md
- gulp/nodemon.js
Not everyone remembers (or knows about) the `npm install` guidance when updating here:
https://govuk-prototype-kit.herokuapp.com/docs/updating-the-kit
I've added a `crash` listener to Nodemon to output a little reminder:
Thought it might help 🙂
> Add npm install reminder on crash

- .gitattributes
Make use of `.gitattributes` file to list all files that we don't want to include in the ZIP users download
As per https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#_exporting_your_repository
Addresses: #519
> Setup exclusion list for the generated ZIP download

- CHANGELOG.md
- package.json
Latest released version.
Release notes here: https://github.com/alphagov/govuk-frontend/releases/tag/v2.3.0
> Update govuk-frontend to 2.3.0

- CHANGELOG.md
- app/assets/javascripts/step-by-step-navigation.js
- app/assets/sass/application.scss
- app/assets/sass/patterns/_step-by-step-navigation.scss
- docs/views/layout.html
- docs/views/templates/start-with-step-by-step.html
- docs/views/templates/step-by-step-navigation.html
- docs/views/tutorials-and-examples.html
This work adds a Step by step navigation page to the template pages in the Prototype Kit.
This means that a service can consider and prototype Step by step navigation as part of their service. It's a pattern we've found to be very successful and we'd like more teams to try it.
This is not an in-service pattern. Similar to Start pages, it would live on gov.uk publishing platform. If teams found a user need for it, they would need to work with the GOV.UK publishing team to get a page built or changed.
Since services should not be implementing this pattern themselves, this code is for prototyping, not production.
This is based on GOV.UK Publishing Components code, re-written for Nunjucks and GOV.UK Frontend
Original files:
- [JavaScript](https://github.com/alphagov/govuk_publishing_components …
> Add step by step navigation

- .gitattributes
Fix a typo, as the CONTRIBUTING.md file wan't excluded from the generated zip. 
File suffix isn't case-sensitive it seems
> Fix list of excluded styles

- docs/views/templates/question.html
In prototype kit training some users were confused by the fact that the closing tag was not on the same line as the opening tag – inconsistent with the paragraph tags in the same file.
> Move closing H1 tag onto the same line as the opening tag

- docs/documentation/using-notify.md
We’re now publishing our documentation using the tech docs tool, and hosting it at https://docs.notifications.service.gov.uk/node.html
> Link to new GOV.UK Notify documentation

- CHANGELOG.md
- app/assets/sass/unbranded.scss
- app/views/layout_unbranded.html
Enable [unbranded template](https://govuk-prototype-kit.herokuapp.com/docs/templates/blank-unbranded) to be easily usable in the app views.
Fixes: #602 
Example using the unbranded layout
> Make unbranded template available for use in app/views

- CONTRIBUTING.md
- README.md
- docs/views/about.html
I tried to follow the pattern we use in Design System https://design-system.service.gov.uk/#support
Trello ticket: https://trello.com/c/KTqAyEp8
Example: https://govuk-prototype-kit-pr-639.herokuapp.com/docs/about
> updates support details

- CHANGELOG.md
- docs/views/templates/start-with-step-by-step.html
- docs/views/templates/step-by-step-navigation.html
Link context (price) wasn't showing correctly previously
> Fix link context in step-by-step templates

- CHANGELOG.md
- gulp/nodemon.js
- package.json
Addresses the warning mentioned in issue #660 by replacing gulp-util with the two individual packages (ansi-color and fancy-logs) as recommended [here](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5).
Another great thing about removing gulp-utils is that it was pulling in 18 other dependencies. Ansi-color required no other dependencies and fancy-logs needs only 4 small dependencies.
> Remove gulp-util

- CHANGELOG.md
- package.json
It seems there is a problem with npm installing 'peer dependencies'
npm's warning says that we need to install this dependency ourselves.
We are getting this issue via `eslint`, via `standard`
The bug is tracked here:
https://github.com/eslint/eslint/issues/11018
> Add acorn dependency to fix npm warning

- CHANGELOG.md
- package.json
We dont really need it but its needed for Standard and gulp-sourcemaps.
#666 deploy failed because Heroku removes dev dependency by default.
> Add acorn to dependency to fix npm Warning

- docs/documentation/install/developer-install-instructions.md
- docs/documentation/install/requirements.md
- package.json
We tell people to get LTS, which has been 10 for a few months now. This updates the docs and package.json from 8 to 10.
Closes #661
> Update docs and package.json to Node 10 LTS

- .gitignore
- __tests__/spec/sanity-checks.js
- app/assets/sass/application.scss
- app/views/includes/head.html
- app/views/includes/scripts.html
- docs/documentation/extension-system.md
- docs/views/includes/scripts.html
- gulp/sass.js
- gulpfile.js
- lib/extensions/extensions.js
- lib/extensions/extensions.test.js
- lib/middleware/extensions/extensions.js
- package.json
- server.js
The implementation of the extension framework discussed in this proposal: https://github.com/alphagov/govuk-design-system-architecture/pull/9
> Extensions Framework

- docs/documentation/install/introduction.md
In the Prototype Kit documentation there's a reference to Slack if people get stuck during installation. But we don't include a link to the [#prototype-kit Slack channel](https://ukgovernmentdigital.slack.com/messages/C0647LW4R/convo/C41GC5UAY-1506957241.000096/). It'd be good to include this.
[This relates to Prototype Kit issue 685](https://github.com/alphagov/govuk-prototype-kit/issues/685)
> Add install guide Slack link

- CHANGELOG.md
- lib/usage_data.js
You can run the prototype toolkit in a way that does not accept input.
A basic example would be:
$ npm start | cat
If this is the first time you have run the prototype kit, the
application will hang as there is no way to respond to the question
about recording usage data. This means it is difficult to run the
prototype kit solely without user input.
This commit changes the behaviour of that prompt to only appear if the
user is running the command in a TTY context.
If the user is not running the prototype kit in a TTY, the prompt will
be skipped and the default action will occur as if the user had simply
hit return. In this case, it'll default to "no" and opt the user out of
usage data collection automatically.
A downside of this approach is that the user will not get asked again
if they …
> Only ask for usage permission if TTY

- .npmrc
- CHANGELOG.md
We have decide to avoid showing users of the prototype kit audit messages.
This is because a lot of the low level issues are not easy to fix, and will cause unnecessary worry.
We will prioritise the security alerts we recieve from GitHub's monitoring.
See https://github.com/alphagov/govuk-prototype-kit/issues/699 for the full discussion.
Resolves https://github.com/alphagov/govuk-prototype-kit/issues/699
> Turn off npm default auditing

- package.json
- Add smaller versions of radio buttons and checkboxes([PR #1125](https://github.com/alphagov/govuk-frontend/pull/1125))
- Prevent duplicate checkbox aria-describedby([PR #1265](https://github.com/alphagov/govuk-frontend/pull/1265))
https://github.com/alphagov/govuk-frontend/releases/tag/v2.10.0
> Bump govuk-frontend from v2.9.0 to v2.10.0

- .gitattributes
fixes #725
We should ignore `.travis.yml` and `__tests__` from the downloaded version of the kit as its unlikely that users would use the tests and they do no need our travis config file.
Test link: https://github.com/alphagov/govuk-prototype-kit/archive/ignore-files-zip.zip
> Ignore travis.yml and tests in downloadable zip file

- package.json
- Add new secondary and warning button variants
([PR #1207](https://github.com/alphagov/govuk-frontend/pull/1207))
- Add new govuk-shade and govuk-tint functions for creating shades and tints of
colours.
([PR #1207](https://github.com/alphagov/govuk-frontend/pull/1207))
- Add support for custom row classes on the summary list component (including support for some rows without action links)
([PR #1259](https://github.com/alphagov/govuk-frontend/pull/1259))
- Ensure fieldset never exceeds max-width
This fix ensures that both WebKit/Blink and Firefox are prevented from expanding their fieldset widths to the content's minimum size.
This was preventing `max-width: 100%` from being applied to select menus inside a fieldset.
See discussion in ["Reset your …
> Bump govuk-frontend from v2.10.0 to v2.11.0

- docs/views/examples/pass-data/index.html
This fixes a rendering issue on the pass data example page.
(Note the text getting larger after each of the two long examples)
> Correctly close <code> tags

- CHANGELOG.md
- app/assets/sass/unbranded.scss
As all the settings are `!default`, the expected way to override settings is to define them before doing the import.
Importing the settings _generally_ works, because we just end up redefining them before they get used. However, it does break some things – specifically, where settings rely on each other (such as the legacy mode settings, or $govuk-assets-path which is relied on by $govuk-images-path and $govuk-fonts-path).
This doesn't work correctly because e.g. $govuk-images-path gets defined before $govuk-assets-path gets overridden, which means it uses the _old_ assets path.
This caught out a user who was using this as a template, and was overriding $govuk-assets-path but not seeing the expected changes represented in $govuk-images-path.
> Remove unneeded settings import

- package.json
Update the Prototype Kit to include the latest release of GOV.UK Frontend
🆕 New features:
- Support custom attributes on summary list action links
You can now use the `attributes` macro option to add additional HTML attributes to summary list action links.
([PR #1372](https://github.com/alphagov/govuk-frontend/pull/1372))
- Support aria-describedby on all form fields
All form fields now support an initial `aria-describedby` value, populated before the optional hint and error message IDs are appended.
Useful when fields are described by errors or hints on parent fieldsets.
([PR #1347](https://github.com/alphagov/govuk-frontend/pull/1347))
🔧 Fixes:
- Update colour for MHCLG
Fixes the brand colour for MHCLG to their correct corporate "green" brand.
([PR …
> Bump govuk-frontend to v2.12.0

- CHANGELOG.md
- __tests__/spec/sanity-checks.js
- app/assets/sass/unbranded.scss
- package.json
The Prototype Kit is currently throwing a Sass error when trying to compile the unbranded stylesheet.
```
[10:36:10] Starting 'sass'...
Error in plugin "sass"
Message:
app/assets/sass/unbranded.scss
Error: Undefined variable: "$govuk-body-background-colour".
on line 7 of app/assets/sass/unbranded.scss
>> $govuk-canvas-background-colour: $govuk-body-background-colour;
---------------------------------^
[10:36:11] Finished 'sass' after 624 ms
```
In d901c7f we removed an import of govuk-frontend/settings/all because it caused issues for users overriding settings that relied on each other.
However, this broke the unbranded stylesheet as it refers to `$govuk-body-background-colour` which was then undefined.
Importing only the colour palette and applied colour settings solves this problem. We …
> Fix sass error

- __tests__/spec/sanity-checks.js
- app/assets/sass/application.scss
- app/assets/sass/patterns/_step-by-step-navigation.scss
- app/assets/sass/unbranded.scss
- app/views/layout.html
- app/views/layout_unbranded.html
- docs/assets/sass/docs.scss
- docs/documentation/tips-and-tricks.md
- docs/documentation/using-notify.md
- docs/views/examples/branching/index.html
- docs/views/examples/pass-data/vehicle-features.html
- docs/views/examples/pass-data/vehicle-registration.html
- docs/views/examples/pass-data/vehicle-type.html
- docs/views/includes/scripts.html
- docs/views/layout.html
- docs/views/layout_unbranded.html
- docs/views/templates/check-your-answers.html
- docs/views/templates/question.html
- docs/views/templates/start-with-step-by-step.html
- docs/views/templates/start.html
- lib/extensions/extensions.js
- lib/extensions/extensions.test.js
- package.json
This pull request establishes the base for the upcoming Prototype Kit 9.0 release which'll include GOV.UK Frontend 3.0.0.
I followed the release notes for 3.0.0 to do this pull request.
It has a pre-release installed which will be changed when we're ready to release this properly.
> Update to GOV.UK Frontend 3.0.0

- package.json
This updates the release to as close to what we will ship to users.
> Update GOV.UK Frontend 3.0.0 pre-release

- CHANGELOG.md
- app/views/layout.html
- docs/views/layout.html
- docs/views/templates/confirmation.html
- docs/views/templates/task-list.html
- package.json
This feature sets the vertical spacing for the main wrapper depending on what is put in the 'beforeContent' block.
This should simplify using the kit for users as for the majority of cases they will no longer need to think about when to use the large modifier.
Closes https://github.com/alphagov/govuk-prototype-kit/issues/771
> Layouts now have automatic vertical spacing on the main wrapper of the page by default

- package.json
We were previously using a pre-release version for testing.
> Update GOV.UK Frontend to v3.0.0

- package.json
Not a big deal since this is not published but makes support easier since this name comes up in the error logs.
> Rename package.json name to be clearer

- .github/issue_template.md
- .github/pull_request_template.md
Between 13-26 August, the GOV.UK Design System team is assisting with urgent and critical Brexit-related work being undertaken by GDS and will not be able to respond to support requests.
> Create issue and pull request templates

- docs/documentation/updating-the-kit.md
- docs/views/tutorials-and-examples.html
Since most users do not need to use this functionality,
we want to ensure people are not confused when updating.
Closes https://github.com/alphagov/govuk-prototype-kit/issues/779
> Move backwards compatibility into advanced usage

- CHANGELOG.md
- app/assets/sass/patterns/_step-by-step-navigation.scss
This pull requests updates the focus state styles for the step-by-step navigation component to use frontend v3.0
Fixes issue #755
> Update focus states on step-by-step navigation

- docs/documentation/install/developer-install-instructions.md
- docs/documentation/install/introduction.md
- docs/documentation/updating-the-kit.md
- docs/views/install.html
This pull request:
- adds an option to update your kit on the install page
- adds option to update from individual install guides
- adds release notes as part of the update guide
Fixes https://github.com/alphagov/govuk-prototype-kit/issues/784
> Simplify install links and include release notes

- docs/assets/sass/docs.scss
Prototype Kit docs pages aren't using the correct styling for code markdown in bullets.
This is how it looks at the moment on https://govuk-prototype-kit.herokuapp.com/docs/creating-routes. The code block and inline code are ok, but the bullets are missing the styling.
Nick and I worked on this pull request to update the CSS to (just about) match code formatting on the Design System pages.
> Fix code styling in bullets in Prototype Kit docs

- CHANGELOG.md
- server.js
We automatically ‘enable’ compatibility mode if the file `app/v6/routes.js` exists.
We currently do this by including it within a try/catch block, relying on the empty catch block handling the case where the file does not exist.
However this means that if any exception is encountered whilst requiring that file, we silently fail and do not enable compatibility mode.
This means that if e.g. a user’s v6 routes file includes a dependency which is not installed (which is likely if the user is trying to update their prototype, as doing so nukes any additional dependencies in their `package.json` file) then this error will not be reported and compatibility mode just won’t work.
Instead, we test for the presence of `app/v6/routes.js` – if it exists, then we require it. If any exception is …
> Prevent exceptions thrown from 'compatibility mode' routes from being silently caught, disabling compatibility mode

- docs/documentation/make-first-prototype/show-users-answers.md
Submitted as an issue through the prototype-kit channel
> I just wanted to let you know it looks like there is a mistake in the prototyping tutorial. On the 'Show the user's answers on your 'Check your answers' page' page, the instruction on 'show your answer to question 1' reads 'In the <dd> tag on the next line, change Sarah Philips to {{ data['how-many-balls’] }}.' The apostrophe after balls is not the right one. Just for those whose who are copy and pasting!
> Update data attribute code block to use the right quote mark

- docs/documentation/make-first-prototype/let-user-change-answers.md
Guidance was referencing the 'Confirmation' page when it should have been referencing 'Check your answers'.
> Change 'Confirmation' to 'Check your answers' page

- docs/documentation/make-first-prototype/let-user-change-answers.md
This PR updates the tutorial to replace the data attribute ```{{ data['name-of-trick'] }}``` with ```{{ data['most-impressive-trick'] }}```, as stated earlier in the tutorial.
Fixes #820
> Correct data attribute in kit tutorial

- docs/views/examples/branching/index.html
The `id` and `for` attribute for the 'No' option were not the same so the label was not applied correctly.
> Fix the branching example markup

- CHANGELOG.md
- app/assets/sass/unbranded-ie8.scss
- app/assets/sass/unbranded.scss
- app/views/layout_unbranded.html
- docs/views/layout_unbranded.html
Updates the unbranded template to extend the main layout, which allows users to use Prototype Kit specific patterns such as the task list and step-by-step patterns.
Closes https://github.com/alphagov/govuk-prototype-kit/issues/841
> Allow Kit specific patterns to be used with the unbranded template

- docs/views/includes/tracking_body.html
- docs/views/includes/tracking_head.html
- docs/views/layout.html
- server.js
Complying with ICO guidance around cookie consent we can’t set non-essential cookies without consent being granted. In the short term then we have to disable Google Analytics as it stores cookies.
We're going to update the relevant aspects of the cookie banner / privacy policy in an additional change.
We intend on reviewing our approach in the new year.
> Remove Google Analytics

- server.js
The variable to show the cookie banner was only set for the app server
not the documentationApp server.
> Fix cookie banner not showing on docs website

- docs/views/cookies.html
- docs/views/privacy-policy.html
This PR updates content in line with https://github.com/alphagov/govuk-prototype-kit/pull/843:
- updates privacy policy page
- updates cookie page
- add missing cookie on cookies page
- fixes incorrect table captions and style issues on cookie page
Content has been 2i'd.
Do not merge until:
- cookie banner has been fixed in https://github.com/alphagov/govuk-prototype-kit/pull/844
- developer has checked for factual accuracy
> Update privacy policy and cookies page

- docs/documentation/make-first-prototype/show-users-answers.md
This pr updates the content in the tutorial on removing users' data to be clear that using an incognito window or selecting the Clear data link
will do the same thing but not both are needed.
Fixes #810
> Update tutorial content on clearing users' data

- app/views/index.html
Some participants in the training were confused by the way the two different list items are indented. Indent them consistently so that it's clear what the markup is.
> Consistently indent docs links on homepage

- .travis.yml
As flagged in Travis' build config validation:
> root: deprecated key sudo (The key `sudo` has no effect anymore.)
> Remove sudo key from travis.yml

- CHANGELOG.md
- __tests__/spec/force-https-redirect.js
- app/assets/javascripts/step-by-step-nav.js
- docs/documentation_routes.js
- lib/extensions/extensions.test.js
- lib/middleware/authentication/authentication.test.js
- lib/utils.js
- package.json
- server.js
- start.js
Suggest reviewing commit-by-commit.
> Update various dependencies and fix linting offences

- docs/documentation/make-first-prototype/link-index-page-start-page.md
This removes the link to 'Creating routes' from [the end of the tutorial](https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/link-index-page-start-page), because the current linked page doesn't tell you how to redirect users based on their answers.
> Remove 'Redirect users...' link from the final tutorial page

- docs/documentation/install/install-the-kit.md
This adds a short section to [Install the kit](https://govuk-prototype-kit.herokuapp.com/docs/install/install-the-kit.md) to clarify that you need to add quotes if you're `cd`-ing to your prototype folder and one of the parent folders has spaces.
I've also taken the Mac/Windows code examples out of their own sections, to avoid having to repeat the new content twice (once for each section).
> Add guidance on cd-ing to folder names with spaces

- docs/documentation/install/install-the-kit.md
This fixes the 2 links in the 'Terminal basics' section of Install the kit that no longer go to tutorials.
I've also fixed a couple of nearby style issues.
> Fix terminal link plus minor style fixes

- docs/documentation/make-first-prototype/show-users-answers.md
This adds a step to [Show the user's answers on your 'Check your answers' page](https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/show-users-answers) in the tutorial, so that users can delete the remaining example answers from the template 'check your answers' page.
> Add step for deleting example answers

- docs/documentation/make-first-prototype/show-users-answers.md
We published the documentation changes in https://github.com/alphagov/govuk-prototype-kit/pull/895 without the changes from 2i. This updates the documentation with the style changes.
> Make changes from 2i to documentation change in #895

- docs/documentation/make-first-prototype/show-users-answers.md
I accidentally removed the 'next page' link from the 'Show the user's answers' page of the tutorial. This adds the link back in.
> Add link back in to the "show user's answers" tutorial page

- .travis.yml
- CHANGELOG.md
- lib/usage-data-prompt.txt
- lib/usage_data.js
- lib/utils.js
- package.json
- start.js
See individual commits for details.
Closes #898
> Add support for Node v14

- CHANGELOG.md
- app/assets/sass/patterns/_task-list.scss
- docs/views/templates/task-list.html
We're [updating the task list pattern in the Design System to make it clearer which tasks still need to be done][1].
This updates the template in the Prototype Kit so that it matches the examples used in the Design System.
[Preview the updated template](https://govuk-prototype-kit-pr-907.herokuapp.com/docs/templates/task-list).
Closes #904 
---
[1]: https://github.com/alphagov/govuk-design-system/pull/1250
> Update Task List template

- CHANGELOG.md
- lib/middleware/authentication/authentication.js
- lib/utils.js
- server.js
The Prototype kit _mostly_ works fine when running on glitch, but has an issue.
**When you run the prototype, no username and password is required.**
The kit is meant to require a username and password when run online, so that people don't accidentally come across the prototypes.
Glitch doesn't set NODE_ENV, so the kit incorrectly thinks it's running in a local environment. This pr checks an env var [glitch uses](https://support.glitch.com/t/detect-if-app-is-running-on-glitch/3120/2), and if so, sets env to `production`.
This exposes a second bug - that the kit tries to apply https, but gets caught in a redirection loop because glitch sends a [comma separated list](https://support.glitch.com/t/x-forwarded-proto-contains-multiple-protocols/17219) for `X-Forwarded-Proto`. The accepted fix …
> Fix security issue when running on Glitch

- docs/documentation/updating-the-kit.md
This updates the docs on [updating the Prototype Kit](https://govuk-prototype-kit.herokuapp.com/docs/updating-the-kit) with guidance on checking your package.json file if your prototype does not work after updating, and installing any missing packages.
Needs 2i before publishing.
> Add docs about checking package.json when updating

- docs/documentation/using-notify.md
Notify has renamed its ‘whitelist’ feature to ‘guest list’. This pull request updates the documentation in this repo accordingly.
The rationale for changing the terminology is detailed here: https://github.com/alphagov/notifications-admin/pull/3479
> Update GOV.UK Notify documentation to remove ‘whitelist‘

- app.json
The current Cedar-14 stack is end-of-life (EOL). After November 2, apps on Cedar-14 will continue to run, but may not build or receive security updates.
Changing the stack definition in app.json only changes the stack for new review apps. Once this has been tested, we’ll also need to change the stack for the current running ‘production’ app using the Heroku CLI or the Heroku Dashboard.
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
Part of #943
> Update Heroku stack to Heroku 18

- CHANGELOG.md
- gulp/copy-assets.js
Move the negative glob to exclude the sass directory after the broader ‘non-negative’ glob, as per the gulp documentation:
> Since globs are matched in array order, a negative glob must follow at least one non-negative glob in an array. The first finds a set of matches, then the negative glob removes a portion of those results. When excluding all files within a directory, you must add /** after the directory name, which the globbing library optimizes internally.
>
> – https://gulpjs.com/docs/en/getting-started/explaining-globs/#special-character--negative
The `{,/**/*}` expansion doesn’t seem to do anything versus including `${config.paths.assets}/**`, so simplify it to remove the expansion.
Fixes #932
> Fix sass files being copied to public directory

- CHANGELOG.md
- listen-on-port.js
I've discovered that Browser Sync ghost mode is the cause of a tricky and unpredictable set of issues I've had. It looks like it's not intended to be enabled in the kit, but due to a typo it was.
---
If you have multiple tabs open to the same page in the kit, the default browsersync settings will mirror clicks and changes across all of them. This means when you submit a form, that same request will happen twice.
This can cause bugs / unexpected behaviour - if your app has routes that make changes on the basis of form submissions, it can get in to an inconsistent state if routes are running multiple times.
This can easily be verified by putting a console log in the default `over-18` route - if you have two tabs open it'll log twice.
I reported on slack some months back an issue with routes …
> Fix typo that causes ghostMode to be accidentally enabled

- docs/documentation/install/install-the-kit.md
some updates based on training:
- use the same folder structure for Windows and MacOS: `~/Documents/prototypes`. It's difficult to see the home folder in either GUI
- reminder to make sure you use the same upper or lower case as the instructions
- clarification that you only need to run `npm install` the first time
- remove duplicate 'Install the kit' heading
> Update docs: 'Install the kit'

- docs/documentation_routes.js
- lib/utils.js
At the minute the tests hang when running on macOS:
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
If you run `jest —detectOpenHandles` this seems to suggest the issue is with sync-request:
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
●  PROCESSWRAP
at start (node_modules/sync-rpc/lib/index.js:33:13)
at sendMessage (node_modules/sync-rpc/lib/index.js:133:17)
at createClient (node_modules/sync-rpc/lib/index.js:173:27)
at Object.<anonymous> (node_modules/sync-request/lib/index.js:16:14)
```
`sync-request` is only used to fetch the latest version of the kit …
> Simplify download link logic

- CHANGELOG.md
- package.json
Updates `govuk-frontend` to the new release (`3.10.0`)
> Use govuk-frontend 3.10.0

- docs/documentation/make-first-prototype/create-pages.md
- docs/documentation/make-first-prototype/open-prototype-in-editor.md
- docs/documentation/make-first-prototype/start.md
- docs/views/tutorials-and-examples.html
- Move 'Open your prototype in your editor' to its own page, add the folder overview
- Move 'copying in Atom' instructions - people find it confusing in the abstract
- Explain config a bit more, fix wrong default service name
> Update 'Create Pages', add 'Open prototype in editor'

- app/views/layout.html
Import the notification banner so that users can include it in the prototype kit without needing to import it themselves, as [we tell them to do in the ‘Getting Started’ documentation in the Design System][1].
[1]: https://design-system.service.gov.uk/get-started/prototyping/#:~:text=When%20using%20Nunjucks%20macros%20in%20the%20Prototype%20Kit%20leave%20out%20the%20first%20line%20that%20starts%20with%20%7B%25%20from%20....
> Import the notification banner macro as part of the layout

- .travis.yml
Building in Mac OS now requires you to purchase credits. This is blocking our builds, so we're going to temporarily turn off Mac builds to get the latest release out.
Merging https://github.com/alphagov/govuk-prototype-kit/issues/952 is a more long-term fix for this problem, we'll do this asap once the release is out.
> Remove Mac build from Travis setup

- CHANGELOG.md
- package.json
Closes https://github.com/alphagov/govuk-prototype-kit/issues/969
> Update the prototype kit to use GOVUK Frontend v3.10.1

- CHANGELOG.md
- app/views/layout.html
Import the cookie banner so that users can include it in the prototype kit without needing to import it themselves, as we tell them to do in the [‘Getting Started’ documentation in the Design System](design-system.service.gov.uk/get-started/prototyping/#:~:text=When%20using%20Nunjucks%20macros%20in%20the%20Prototype%20Kit%20leave%20out%20the%20first%20line%20that%20starts%20with%20%7B%25%20from%20....)
> Import the cookie banner macro as part of the layout

- docs/documentation/make-first-prototype/show-users-answers.md
Updates the page 'Show the user’s answers on the ‘Check your answers’ page'
- uses typographic quotes and apostrophes
- removes the guidance on testing as users don't need it at this point - we could add a page in future about testing
- tells people what to do and then explains why - in research people would try and implement the explanations
- explains visually hidden text a bit more 
- adds full code example to check against what they've written
> Update tutorial - check answers

- package.json
Marked 1.2.0 had a security vulnerability which was [flagged by dependabot.](https://github.com/alphagov/govuk-prototype-kit/security/dependabot/package.json/marked/open) This was patched in v2.0.0.
This is a major update - I've run the tests and checked a few pages of the prototype kit locally and it seemed to work as expected.
> Update marked to v2.0.0

- CHANGELOG.md
- docs/documentation/install/requirements.md
- package.json
This upgrades the list of supported Node versions to include v15. This is useful as currently only version 15 is supported by Macs using the new M1 ARM chips (see https://github.com/nodejs/node/issues/36161).
I've been running it locally using version 15 fine, and have [upgraded our prototype](https://github.com/DFE-Digital/apply-for-teacher-training-prototype/pull/454) to node 15 running on Heroku.
> Allow Node 15 to be used

- CHANGELOG.md
- gulp/sass.js
- start.js
to fix issue #295 
- changes the Gulp log level to be quieter so errors stand out
- makes a blank application.css file if there are sass errors so the site looks broken to the user (simply removing the css file does not work with browserSync)
- if the user fixes the sass error, the site will automatically reload, as opposed to #977 which crashes and you have to restart the kit after fixing the sass
> Make sass errors clearer to the user

- docs/documentation/make-first-prototype/link-index-page-start-page.md
- docs/documentation/make-first-prototype/make-first-prototype.md
- docs/documentation/updating-the-kit.md
When reviewing #999 I was momentarily thrown by one of the links in the documentation going to the live version, rather than staying within the review app. This fixes that, and 2 other instances.
> Fix: make documentation links relative

- docs/views/index.html
We added a section telling people about the move from Elements to the Design System. I don't think that's necessary any more as its been a few years
> Remove 'new' section from home page as it is no longer new

- docs/documentation/install/requirements.md
This PR updates the Kit guidance to:
- explain that M1 Macs have issues running the Kit
- advise users to contact us if they need support
> Add info about M1 Macs to Kit install guidance

- .github/workflows/create-release-tag.yaml
- CONTRIBUTING.md
- docs/documentation/install/introduction.md
- docs/documentation/publishing-on-heroku-terminal.md
- docs/documentation/setting-up-git.md
- internal_docs/releasing.md
Part of #989.
Replace instances of "master" with "main" in preparation for the default branch renaming work
Many communities on GitHub are considering renaming the default branch name of their repository from master, as this terminology can be offensive. Statements and guidance have been published by Git [here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and GitHub [here](https://github.com/github/renaming).
New GitHub repositories use `main` as the name for the default branch, so it makes sense that we should follow this convention, as well as matching what other teams within GDS are doing so we are consistent.
We are renaming the default branch to `main`, we need to update documentation and tooling to reflect this.
> Rename default branch to `main`

- docs/documentation/updating-the-kit.md
Step 9 from steps on updating to the latest version is out of date, as `app/assets/scss/components` was removed in #983.
Users should not need to remove the `app/assets/scss/components` folder if they already have one, so we can just remove the step.
Closes #1022.
> Update updating the kit instructions

- internal_docs/deploys.md
We use a Heroku pipeline to automatically deploy to govuk-prototype-kit.herokuapp.com, and the pipeline is configured manually and not documented anywhere.
This commit adds documentation to the internal docs in this repo, so know where to look when there are issues, and what the configuration should be.
> Add internal documentation on deployments

- CHANGELOG.md
This PR is to tell users:
- they can [opt in to link styles](https://github.com/alphagov/govuk-frontend/pull/2183)
- about fixes to [make Sass errors clearer](https://github.com/alphagov/govuk-prototype-kit/pull/990) and [allow Node 15 to be used](https://github.com/alphagov/govuk-prototype-kit/pull/995)
> Add release notes for GOV.UK Prototype Kit v9.13.0

- app/assets/sass/application.scss
- app/assets/sass/patterns/_step-by-step-nav.scss
- docs/assets/sass/docs.scss
Closes https://github.com/alphagov/govuk-prototype-kit/issues/1012
**NOTE: This PR currently points at a pre-release of GOV.UK Frontend. This commit should be removed and replaced by a separate PR to bump GOV.UK Frontend to v3.12.0 before this PR is merged.**
Update the prototype kit to opt into the new link styles.
Update the step-by-step navigation template to make use of the new link styles.
The new link and hover styles will be opt-in until the next major release of GOV.UK Frontend. However, we'd like the prototype kit to take advantage of the new styles when 3.12.0 is released in order to present the most up-to-date version of GOV.UK Frontend.
> Update link styles

- CONTRIBUTING.md
- internal_docs/review-apps.md
Part of #1011.
This repo uses Heroku review apps, we should document how to use them and how they are configured.
Adds documentation for contributors and reviewers in the CONTRIBUTING doc and documentation for admins in the internal_docs folder.
Especially important is the username/password for each review app!
> Add documentation on review apps

- docs/views/tutorials-and-examples.html
Partly addresses [#1426](https://github.com/alphagov/govuk-design-system/issues/1426).
This PR updates the [Prototype Kit's 'Tutorials and page templates' page](https://govuk-prototype-kit.herokuapp.com/docs/tutorials-and-examples) to make it clear that:
- the pattern is only for use on GOV.UK 
- the pattern is only included in the Prototype Kit so users can prototype their journeys
- we do not actually provide the code for the pattern (unlike most of our other components and patterns)
> Update tutorials page about use of step-by-step

- docs/documentation_routes.js
the old redirect is wrong - it doesn't include the 'make-first-prototype' path, see this issue: 
https://github.com/alphagov/prototype-kit-training/issues/65
> fix 'add questions' redirect

- package.json
Closes https://github.com/alphagov/govuk-prototype-kit/issues/1034
You can now add a 'none' option to checkboxes. For example, 'None of the above' or 'None of these options apply to me'.
Use the 'none' option to [allow users to state that none of the checkboxes apply to them](https://design-system.service.gov.uk/components/checkboxes/#add-an-option-for-none-). Otherwise, users would have to work out that they should leave all the checkboxes unticked.
You can now also add an 'or' divider before the 'none' option. Use the 'or' divider to make the 'none' option more visible to users.
This was added in [pull request #2151: Add 'None of the above' and 'or' divider to checkboxes](https://github.com/alphagov/govuk-frontend/pull/2151). Thanks to …
> Update GOV.UK Frontend to 3.13.0

- CHANGELOG.md
- start.js
Run gulp using the node executable
GDS Managed devices cannot run anything that isn't installed via Self Service. This change runs node to run gulp indirectly so does not need permissions.
> Run Gulp using the Node executable to fix permissions problem

- CHANGELOG.md
This PR is to tell users about a fix that will enable them to run the Kit on GDS-managed devices. See [#1039](https://github.com/alphagov/govuk-prototype-kit/pull/1039).
> Add release notes for GOV.UK Prototype Kit 9.14.1

- docs/documentation/make-first-prototype/branching.md
Fixes issue #1040, by changing the example code as suggested.
I also found while following the documentation that step 1 was incorrect, as there is no file called `template-content-page.html`; this PR also updates step 1 to refer to `docs/views/templates/content.html`.
> Fix documentation bugs in branching page of tutorial

- docs/documentation/make-first-prototype/let-user-change-answers.md
Fixes typo spotted by user on page https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/let-user-change-answers (see Zendesk ticket https://govuk.zendesk.com/agent/tickets/4643784).
> Remove repeated 'the'

- docs/documentation/updating-the-kit.md
This change is for GDS users with a managed device who cannot run Gulp.
fixes #1048
> Document issue with Gulp

- CHANGELOG.md
- lib/utils.js
If the code generating `session-data-defaults` is fairly complex, spotting and fixing those errors is a common problem, and is more than fixing simple syntax issues.
This change still allows the app to run, but will show the original error in the console alongside the warning about loading the defaults. By showing the full error it also highlights where there's a problem – the single line "Could not load…" message can be easily missed in a busy log.
Showing the error in the log allows a developer to debug and fix the problem.
> Don’t swallow errors from session-data-defaults.js

- docs/documentation/install/install-the-kit.md
Fixes [#1065](https://github.com/alphagov/govuk-prototype-kit/issues/1065).
This PR adds content to [our 'Install the kit' page](https://govuk-prototype-kit.herokuapp.com/docs/install/install-the-kit.md#unzip-the-kit-and-move-it).
This new content tells users to install the kit on a local drive, not on a cloud-based drive. We've added this because a user told us they had permissions issues during a fresh kit-install. The issues occurred because the files were on iCloud instead of on the user's local drive.
> Add info about install location to install guide

- CHANGELOG.md
- package.json
Closes https://github.com/alphagov/govuk-prototype-kit/issues/1058
We’ve made fixes to GOV.UK Frontend in the following pull requests:
- [#2264: Improve focus state for radio and checkbox controls in forced colors mode (for example, Windows High Contrast Mode)](https://github.com/alphagov/govuk-frontend/pull/2264) – thanks to [@adamliptrot-oc](https://github.com/adamliptrot-oc) for reporting this issue
- [#2265: Do not remove focus outline from disabled link buttons in forced colors mode](https://github.com/alphagov/govuk-frontend/pull/2265)
- [#2273: Fix invisible footer on Open Government Licence logo in forced colors mode](https://github.com/alphagov/govuk-frontend/pull/2273) – thanks to [@oscarduignan](https://github.com/oscarduignan) for reporting this issue
- [#2277: Fix invisible …
> Update GOV.UK Frontend to 3.13.1

- CHANGELOG.md
Closes [#1057](https://github.com/alphagov/govuk-prototype-kit/issues/1057).
> Add release notes for Kit v9.14.2 release

- docs/documentation/publishing-on-heroku.md
Fixes [#1072](https://github.com/alphagov/govuk-prototype-kit/issues/1072).
This PR updates the alt text in 2 screenshots on our [Publishing on Heroku page](https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku).
The previous alt text did not match the text displayed in either screenshot. This inconsistency might have confused users of assistive tech, because different words were used to describe the same thing.
> Align image alt text with image contents

- docs/views/about.html
- docs/views/tutorials-and-examples.html
Fixes [#1074](https://github.com/alphagov/govuk-prototype-kit/issues/1074).
This PR adds new link-text to our [About](https://govuk-prototype-kit.herokuapp.com/docs/about) and [Tutorials and examples](https://govuk-prototype-kit.herokuapp.com/docs/tutorials-and-examples) pages.
We've added this text because, currently, we have instances of the same link-text (like "start page") pointing to different places. For example, depending on where the link-text displays, either to the [start pages guidance](https://design-system.service.gov.uk/patterns/start-pages/) or to the [page template](https://govuk-prototype-kit.herokuapp.com/docs/templates/start). So, this PR adds text to clarify where we're directing users.
> Differentiate link text in About and Tutorial docs

- docs/documentation/adding-css-javascript-and-images.md
- docs/views/tutorials-and-examples.html
Fixes [#1042](https://github.com/alphagov/govuk-prototype-kit/issues/1042).
This PR adds the word 'PDFs' to the doc title 'Adding CSS, JavaScript and Images' and the doc's first paragraph. 
It also updates the link-text for the doc title in the [Tutorials and examples (table of contents) homepage](https://govuk-prototype-kit.herokuapp.com/docs/tutorials-and-examples).
We've made these changes because several users have struggled to find our guidance on downloadable files.
> Add PDFs to title and content of Basic usage doc

- package.json
Greenkeeper [ceased operations in 2020](https://twitter.com/greenkeeperio/status/1268228650593386496), and the bot's last PR on this repo was #505 in May 2018.
It doesn't look like we need the `greenkeeper` property in package.json, which was added to prevent the bot from bumping `nunjucks` above v2 (https://github.com/alphagov/govuk-prototype-kit/pull/392/commits/1373ae884c4eaf49c9d638890565cd5da2ed1e40).
> Remove greenkeeper from package.json

- docs/documentation/make-first-prototype/show-users-answers.md
- docs/views/templates/check-your-answers.html
This PR replaces the word 'notification' with 'application'  in examples on our:
- [Show user's answers page](https://github.com/alphagov/govuk-prototype-kit/blob/main/docs/documentation/make-first-prototype/show-users-answers.md)
- [Check your answers page](https://github.com/alphagov/govuk-prototype-kit/blob/main/docs/views/templates/check-your-answers.html)
> Fix wording in examples of user applications

- docs/documentation/make-first-prototype/use-components.md
Fixes [#1090](https://github.com/alphagov/govuk-prototype-kit/issues/1090).
This PR replaces a redundant link in our ['Use components from the Design System' page](https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/use-components).
The old link pointed to a 'Stacked radios' section in the [Design System's radios guidance](https://design-system.service.gov.uk/components/radios/). However, this section no longer exists.
The new link points to [the guidance's 'Inline radios' section](https://design-system.service.gov.uk/components/radios/#inline-radios).
> Replace redundant link with link to inline radios

- docs/documentation/install/requirements.md
Fixes [#1089](https://github.com/alphagov/govuk-prototype-kit/issues/1089).
This PR updates some link text on our [requirements page](https://govuk-prototype-kit.herokuapp.com/docs/install/requirements.md) to make it clear:
- which link is for Mac/Windows users
- which link is for Linux users
> Add explicit link text about Nodejs

- CHANGELOG.md
- app/views/layout.html
"Support links" isn't very clear. "Footer links" is a bit more agnostic.
Fixes #1102
> Change visually hidden footer title

- CHANGELOG.md
- docs/views/templates/check-your-answers.html
- docs/views/templates/content.html
- docs/views/templates/question.html
In most cases, the back button should simply go back to the referring page, so we can use `window.history`.
Closes #494
There is a small potential issue when hovering on the link, as browsers will display the `href` property in the status bar, which in this case is just some javascript (as shown in the image below).
I'm not sure how much of an issue this is for prototyping.
> Replace back link placeholder URLs with javascript

- README.md
Partly addresses [#1692](https://github.com/alphagov/govuk-design-system/issues/1692).
This PR updates the [repo README](https://github.com/alphagov/govuk-prototype-kit/blob/main/README.md) with info and link text for our [security policy](https://github.com/alphagov/govuk-design-system/security/policy).
Hopefully this will make the security policy more visible to researchers who want to report vulnerabilities.
> Link Prototype Kit repo README to security policy

- CHANGELOG.md
Fixes [#1096](https://github.com/alphagov/govuk-prototype-kit/issues/1096).
This PR adds release notes that detail these additions to the Kit:
- [pull request #1076: Update to Node.js v14.17.6 when using Node Version Manager](https://github.com/alphagov/govuk-prototype-kit/pull/1076)
- [pull request #1103: Replace back link placeholder URLs with JavaScript](https://github.com/alphagov/govuk-prototype-kit/pull/1103)
- [pull request #1104: Change visually hidden footer title](https://github.com/alphagov/govuk-prototype-kit/pull/1104)
We're asking users to update Node because of a [GitHub-reported security vulnerability](https://github.blog/2021-09-08-github-security-update-vulnerabilities-tar-npmcli-arborist/).
We're also telling users that we've:
- added JavaScript for back links, to make …
> Add release notes for GOV.UK Prototype Kit v 9.15.0

- docs/documentation/make-first-prototype/use-components.md
Fixes [#1090](https://github.com/alphagov/govuk-prototype-kit/issues/1090).
This PR updates some link text in our ['Use components from the Design System' tutorial](https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/use-components).
The previous link incorrectly directed users to the 'Inline radios' section, if they wanted to add radios to question 1. Instead, this update directs them to use the first example on the [radios component page](https://design-system.service.gov.uk/components/radios/).
> Update link text in use-components tutorial

- package.json
Bumps a load of less critical libraries to the latest versions, squashing a whole load of errors.
I've read through the release notes for each, the only breaking changes are dropping support for older versions of Node (including v10).
- Bump marked from 2.1.3 to 3.0.8
- Bump dotenv from 8.2.0 to 10.0.0
- Bump del from 5.1.0 to 6.0.0
- Bump inquirer from 7.1.0 to 8.2.0
- Bump inquirer from 7.3.3 to 8.2.0
- Bump supertest from 4.0.2 to 6.1.6
- Bump acorn from 7.4.1 to 8.5.0
- Bump gulp-sourcemaps from 2.6.5 to 3.0.0
> Bump outdated libraries

- .github/workflows/run-tests.yaml
Now that we have a package-lock file, we should use `npm ci` over `npm install` in automated environments, because:
- it's significantly faster
- if dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead of updating the package lock
- it will never write to package.json or any of the package-locks: installs are essentially frozen
See https://docs.npmjs.com/cli/v7/commands/npm-ci for more information.
> Use npm ci to install dependencies

- docs/documentation/install/run-the-kit.md
Fixes [#1146](https://github.com/alphagov/govuk-prototype-kit/issues/1146).
This PR updates our [install instructions](https://govuk-prototype-kit.herokuapp.com/docs/install/run-the-kit.md). This is so users will know that, after they run `npm start`, they'll get a question about submitting data for analytics.
> Add info about analytics prompt to install guide

- .npmrc
We re-enabled npm audit to check what came up when we added a package-lock file. We don't want users to get these warnings, so this disables npm audit again.
We can always test locally by removing this flag.
> Disable npm audit

- docs/documentation/updating-the-kit.md
- make sure dotfiles are shown before starting the process
- fix instructions to say 'files and folders' instead of just 'folders'
- refer to 'govuk-prototype-kit folder' instead of 'unzipped folder'
> Fix Update guide to make sure dotfiles are copied

- internal_docs/releasing.md
We've decided to encourage users to use a lockfile. We've also already changed the npm audit configuration.
> Remove line about considering removing package lockfile

- README.md
Partly addresses [#2396](https://github.com/alphagov/govuk-frontend/issues/2396).
This PR updates the [govuk-prototype-kit README](https://github.com/alphagov/govuk-prototype-kit/blob/main/README.md), so users will know:
- the repo is open, and not monitored outside of office hours
- how to report inappropriate content
We're adding this info because of a [recent security-incident](https://docs.google.com/document/d/1-VZcvII1g9oKFi00JsiuvLE-Y0iAl-qmPeaYLzn6Fmg/edit#).
This PR also adds redirect links to Slack channels, so users without the app will receive download-prompts.
> Tell users how to report inappropriate content

- docs/documentation/updating-the-kit.md
- Move content about contacting the Prototype Kit team to the top of the page to make it easier for users to find it (which has resulted in a change to the H1)
- Clarify instructions after step 16 to distinguish them as a separate point
> Update the Prototype Kit and contact

- .gitattributes
- __tests__/spec/update-script.js
- update.sh
We want to make it easier for users to update existing prototypes to use the latest code from GitHub; the current method is entirely manual and difficult for even developers to follow.
This is especially important for the (currently unreleased) changes to add a package lockfile; for existing installations to be able to use a package lockfile some hidden files need to be updated, which is difficult to do manually.
This commit adds a small bash script to simplify some (but not all) of the steps required to update an existing prototype. It covers steps 1, 2, 4, and 5 (not 3) in the existing process [[1]]. The hypothesis is that it will be easier for users to run the script than do these steps manually, and easier to write a script that is robust and can do these steps without breaking. Note …
> Add bash script `update.sh` to simplify updating existing prototypes

- internal_docs/releasing.md
without this step, the released package-lock.json will be out of sync with the package.json
> release notes - add npm install step to update package-lock.json

- CHANGELOG.md
- lib/utils.js
- lib/utils.test.js
- package-lock.json
- package.json
keypather is a bit unloved and Dependabot complains about it. We can replace it with the `_.get` function from lodash [[1]]. This also saves a little bit of disk space, as we have to install lodash loads anyway.
This PR checks that everything is a-okay by adding some small tests for `checked`, which uses keypather, and then doing the switch.
[1]: https://lodash.com/docs/4.17.15#get
> Replace keypather with lodash.get

- __tests__/spec/sanity-checks.js
- docs/documentation_routes.js
We want to be able to tell users to run
> curl -L https://govuk-prototype-kit.herokuapp.com/docs/update.sh | bash
> Add route to get update script

- docs/documentation/using-notify.md
Small change to keep consistent with the pattern at https://design-system.service.gov.uk/patterns/email-addresses/
Changes input type to email, and adds `spellcheck="false" autocomplete="email"`.
Closes #1115
> Use Design System email pattern

- docs/documentation/updating-the-kit.md
This guidance provides instruction on how to update to v11 of the Prototype Kit. It has been user tested.
> Guidance for updating to v11 of Prototype Kit

- CHANGELOG.md
Update Prototype Kit CHANGELOG with release notes for v12.0.0
> Prototype Kit release notes for v12.0.0

- CHANGELOG.md
- docs/views/examples/pass-data/vehicle-features.html
- docs/views/templates/start-with-step-by-step.html
- docs/views/templates/start.html
- package-lock.json
- package.json
This uses the govuk-frontend v4 pre-release.
I've gone through the CHANGELOG for v4: https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md and there were only a couple of minor things that needed updating.
We can merge this when we have replaced the pre-release with the actual release.
Closes #1063 
* The kit doesn't have any accordions. The step by step navigation uses its own styles and scripts to function.
* No use of the `govuk-main-wrapper` mixins
* No use of the `$govuk-border-width-form-element-error` variable
* The kit _does_ have summary lists, but none of them have an empty actions span
* The kit doesn't use `navigationClasses` on the header
* The kit doesn't include conditionally revealed content (other than on the step by step, which handles that itself)
* There …
> Update the GOV.UK Prototype Kit to use GOV.UK Frontend v4.0.0

- .github/workflows/run-tests.yaml
- __tests__/spec/update-script.js
Previously we were relying on VERSION.txt for the name of the latest release, however this doesn't work in scenarios where we have changed the version number in preperation but have not yet made the release, as we found recently (see issue #1205).
This PR reinstates the test and fixes it so that it won't fail in future.
Instead we get the latest release version using the GitHub API [[1]].
Closes #1205.
[1]: https://github.com/alphagov/govuk-prototype-kit/issues/1205#issuecomment-995706280
---
I tested this locally by updating `VERSION.txt` and running the tests.
> Fix update script test for `fetch` when releasing a new version

- .github/workflows/create-release-tag.yaml
Following best practise, grant the `GITHUB_TOKEN` only the required permissions. The create release tag needs to be able to:
- create the tag for the version ([POST /repos/{owner}/{repo}/git/refs][1])
- update the latest-release tag ([PATCH /repos/{owner}/{repo}/git/refs/{ref}][2])
According to GitHub's documentation, [write access on 'contents' is what is required to be able to do these two actions][3].
Using this approach also allows us to change the default permissions for workflows to 'Read repository contents' only.
[1]: https://docs.github.com/en/rest/reference/git#create-a-reference
[2]: https://docs.github.com/en/rest/reference/git#update-a-reference
[3]: https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
> Set granular token permissions for GitHub Actions

- gulp/sass.js
- package-lock.json
- package.json
We're only using `gulp-sourcemaps` to add sourcemaps to our stylesheets, and not doing anything fancy with it.
As of `gulp` v4, sourcemap support is [built directly into the `src()` and `dest()` functions](https://gulpjs.com/docs/en/api/dest/#sourcemaps).
So we can replace `gulp-sourcemaps` with `gulp`'s built-in support.
I've diffed the resulting files locally and they're exactly the same except the built in version uses the string `utf-8` instead of `utf8`.
- `gulp-sourcemaps` is not a dev dependency in the kit, so users may be making use of it in their own prototypes.
- This fixes a dependabot security advisory regarding `postcss`, which is a dependency of `gulp-sourcemaps`: https://github.com/advisories/GHSA-566m-qj78-rww5
> Remove gulp-sourcemaps dependency

- lib/utils.js
- package-lock.json
- package.json
We have a [security advisory for `marked`](https://github.com/alphagov/govuk-prototype-kit/security/dependabot/package-lock.json/marked/open) v3.0.8 that can be resolved by bumping to the latest version.
This involves a breaking change to v4.0.10, however, it appears the only things that have changed are to do with how `marked` is imported or used in a script tag, so simply updating our require statement is enough to keep everything hunky dory.
> Bump marked to 4.0.10

- docs/documentation/updating-the-kit.md
Fixes [#1193](https://github.com/alphagov/govuk-prototype-kit/issues/1193).
Updates our ['Updating the Kit' doc](https://govuk-prototype-kit.herokuapp.com/docs/updating-the-kit) to remind users to get the latest version of the Kit for security patches and new features.
> Tell users to get latest version of kit

- docs/assets/sass/docs.scss
- docs/documentation/backwards-compatibility.md
- docs/documentation/github-desktop.md
- docs/documentation/install/run-the-kit.md
- docs/documentation/make-first-prototype/start.md
- docs/documentation/make-first-prototype/use-components-2.md
- docs/documentation/make-first-prototype/use-components.md
- docs/documentation/publishing-on-heroku.md
Closes #1232.
---
Note that this PR adds `<figcaption>` elements to some images, as semantic captions. See page 'How to run the kit' for an example. We apply an additional CSS reset to remove margins from `<figure>` elements that are usually applied by browser stylesheets.
> Update alt-text / captions for images

- internal_docs/releasing.md
Fixes [#1163](https://github.com/alphagov/govuk-prototype-kit/issues/1163).
This PR aligns the Kit's release doc with the Design System's release docs.
> Add step about updating changelog to release doc

- .gitignore
Remove the trailing `*` from the directory ignores, as it means something slightly different.
While you might think `node_modules/*` and `node_modules/` should mean the same thing thing, the gitignore manual page [[1]] suggests that `node_modules/*` matches the `node_modules` directory, and only the first level of subdirectory. I can't see that this makes a difference for the official git client in practice, although there is a lot of discussion about it on StackOverflow [[2]]. In a recent user support session I did see some unknown third party software treat the two differently - although I wasn't able to reproduce it.
Regardless, its clear that the "more correct" thing to do is have `node_modules/` without a star, and that is also commonly used best practice, (for instance see the …
> Fix node_modules folder ignore directive

- docs/assets/sass/docs.scss
- docs/views/examples/override-service-name.html
- docs/views/examples/pass-data/index.html
- lib/utils.js
- lib/utils.test.js
Fixes #1075 
Using the GOV.UK Design System [`example`](https://github.com/alphagov/govuk-design-system/blob/main/src/stylesheets/components/_example.scss) as a basis:
Adds a `tabindex` attribute to code samples in order to make them focusable, so keyboard-only users can scroll to see all the text with the `<code>` element. This includes more obvious focus styling.
Additionally, uses `govuk-frontend` font styles to ensure font size resizes when the browser text size is set larger.
It'd be possible to more closely follow the Design System's code examples, but the `example` macro relies on the existence of separate example files and is wrapped up with a tab system to allow viewing both HTML and Nunjucks. That all seemed like a separate thing to consider vs just fixing the accessibility …
> Fix code sample accessibility issues

- docs/documentation/github-desktop.md
change 'github or github desktop' to 'github and github desktop'
it's a guide that covers use of both, not one or the other
> change 'or' to 'and'

- CONTRIBUTING.md
Fixes [#1092](https://github.com/alphagov/govuk-prototype-kit/issues/1092).
Removes 'Versioning' section from our ['Contributing' doc](https://github.com/alphagov/govuk-prototype-kit/blob/main/CONTRIBUTING.md).
Contributors should not be doing any versioning. It's something we do ourselves during releases, and our [release doc](https://github.com/alphagov/govuk-prototype-kit/blob/main/internal_docs/releasing.md) already covers it.
> Remove redundant content from contributing doc

- docs/views/tutorials-and-examples.html
Update the link to the new [Start using a service](https://design-system.service.gov.uk/patterns/start-using-a-service/) pattern page, which replaces the Start page pattern.
> Update link to start pages pattern on Tutorials page 

- .gitignore
- CHANGELOG.md
- lib/middleware/authentication/authentication.js
- lib/middleware/authentication/authentication.test.js
- lib/prototype-admin-routes.js
- lib/prototype-admin/password.html
- lib/utils.js
- package-lock.json
- package.json
- server.js
[Browsers no longer always support basic auth](https://github.com/alphagov/govuk-prototype-kit/issues/1019) so this PR replaces it with:
- middleware to check `req.session.authentication` is the current encrypted password
- if not, redirect to a new `prototype-admin/password` page
- a route to check the `password` POSTed from the page matches the `PASSWORD` set in the environment
- if so, set `req.session.authentication` to the current encrypted password
- redirect back to the page initially requested
to test this branch, run:
```
NODE_ENV=production USE_HTTPS=false PASSWORD=test npm start
```
Screenshot:
> Replace basic auth with a custom authentication process

- docs/documentation/publishing-on-heroku-terminal.md
- docs/documentation/publishing-on-heroku.md
**Do not merge until [#1182](https://github.com/alphagov/govuk-prototype-kit/pull/1182) is released**
This PR updates 2 docs:
- [Publish on the web (Heroku)](https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku)
- [Publish on the web (Heroku) from the terminal](https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku-terminal)
We're removing and relocating content that tells users they need to set a username when publishing the Kit online. In fact, they now only need to set a password. This is because we're introducing a custom authentication process, as browsers no longer always support basic auth.
Some users on old versions may still need the help content about usernames. So we've kept that available under the updated content about passwords.
> Update Heroku docs to reflect custom auth process

- update.sh
fixes #1286 
Copies layout-unbranded.html - this is needed for the new password page to work and was changed during v9.
Also updated the grep test so it works for v9
Note that Step by step pattern is still broken if updating from v9 - this PR does not fix that
> Fix update script to work with all v9 versions

- __tests__/spec/update-script.js
- update.sh
fixes #1291 
This matches the [previously documented process](https://github.com/alphagov/govuk-prototype-kit/blob/v11.0.0/docs/documentation/updating-the-kit.md)
Users on support are losing their custom patterns
Also improves the comment to be clearer
> Don't delete patterns, only copy new ones

- CHANGELOG.md
- app/config.js
- lib/middleware/authentication/authentication.js
- lib/utils.js
- lib/utils.test.js
- listen-on-port.js
- server.js
Fixes #1302.
[Browsersync](browsersync.io) and [Glitch](glitch.com) don't work well together. Currently when on Glitch, Browsersync runs, and for reasons I don't understand this stops the authentication working (you can never log in).
As a fix/workaround, this PR changes `listen-on-port.js` to not use Browsersync if the prototype is running on Glitch. I think this shouldn't be a problem for users, because using Browsersync with Glitch doesn't make much sense (it won't work, and Glitch auto-relaods for you anyway).
With this PR I've tried to follow the maxim of 'leave the code better than you found it', so the way I've approached the fix is to take the logic of determining whether we're running on Glitch, and whether we're running on production, and make a function in utils, with tests, …
> Fix authentication on Glitch

- .github/workflows/run-tests.yaml
- .npmrc
- README.md
- package-lock.json
- package.json
Fixes https://github.com/alphagov/govuk-prototype-kit/issues/1128.
Users of the prototype kit do not need to install dev dependencies such as Jest or StandardJS [[1]]. Currently, because we distribute the kit as a complete Node project rather than as a package, they are installing them by default.
This commit restructures a few things to make sure that dev dependencies are not installed unless explicitly requested. Unfortunately, the way we need to to do this is a little convoluted.
The npm CLI does allow specifying that devDependencies should not be installed by adding a config variable to the `.nvmrc` file [[2]]; however, if the directive `omit=dev` is given, which is what we want, the NODE_ENV environment variable will also always be set to `production`, which is definitely not what we …
> Do not install dev dependencies by default

- .gitattributes
We have some unit tests which are saved as `.test.js` files next to the implementation being tested. These are currently included in our release archives, but they don't need to be. They won't be of interest to users.
This commit adds an ignore pattern to the gitattributes file, so that in future these files won't be present at all.
--- 
You can test this by downloading the archive for this branch at https://github.com/alphagov/govuk-prototype-kit/tree/ldeb-dont-ship-test-js and inspecting the contents.
> Remove Node.js unit test files from release archive

- .github/workflows/run-tests.yaml
I've been getting a lot of test suite failures recently because of timeouts. Increase limit to 15 minutes.
> Increase CI test timeout

- CHANGELOG.md
- package-lock.json
- package.json
closes https://github.com/alphagov/govuk-prototype-kit/issues/1323
I can't see anything in the Frontend release notes that we need to update in the kit
> Update to GOV.UK Frontend 4.1.0

- lib/utils.js
- lib/utils.test.js
This PR resolves issue: https://github.com/alphagov/govuk-prototype-kit/issues/1215
Changes:
- Remove all occurrences of "_unchecked" within a checkbox value array
- Create unit tests to test the above 
- Add additional unit tests to test the rest of the auto store functionality.
> Fix _unchecked falsey value on check your answers page

- __tests__/spec/release-archive.js
This was merged after we had removed gulp, so was looking for the wrong things. Fix it to look for build scripts instead.
> Fix release archive test

- cypress.json
- cypress/config.js
- cypress/integration/1-watch-files/watch-images.cypress.js
- cypress/integration/1-watch-files/watch-views.cypress.js
- cypress/integration/utils.js
- cypress/plugins/index.js
Using baseUrl defined in cypress.json lets us easily override it with a command line argument or environment variable:
https://docs.cypress.io/guides/references/configuration
When using `baseUrl`, the server part of the url needs to be omitted from `cy.visit`.
> Use Cypress config variable baseUrl instead of hostName

- .github/workflows/run-tests.yaml
- __tests__/spec/sanity-checks.js
- lib/build/tasks.js
- lib/utils.js
- start.js
See: https://github.com/alphagov/govuk-prototype-kit/issues/1340
Changes:
- Fix generate assets sanity tests to allow for the generation of /public/assets/application.css
- Only start watching the /public/assets folder when the application.css file has been generated
- Prevent nodemon from watching the /cypress folder
- Clean up start file
> Fix generate assets tests failure on macos

- .github/workflows/run-tests.yaml
- .github/workflows/test-heroku.yaml
Change the GitHub Actions workflows to run only once against a pull request or push, rather than twice for pull requests (which trigger both the pull request event and the push event). This should help speed up the checks, as well as hopefully also reduce the chance of the test servers being overloaded and making our tests flaky again.
---
Note that this means that now pushes to a branch other than main which don't have a pull request will not result in a test, so if you want GitHub to test your changes, you will need to create a (draft) PR.
> Reduce number of tests running for a pull request

- docs/documentation/publishing-on-heroku.md
Remove the notice about Heroku, as the GitHub integration has been re-enabled (see https://status.heroku.com/incidents/2413).
Reverts alphagov/govuk-prototype-kit#1300
> Revert "Notice to users about Heroku issue"

- .github/workflows/lint.yaml
- .github/workflows/run-tests.yaml
This makes it easier to see on GitHub when the linter is causing tests to fail, but the tests themselves are passing.
> Run linter in seperate PR check

- __tests__/spec/start.js
- lib/build/dev-server.js
- lib/build/tasks.js
Fixes #1355.
Currently when the app crashes for whatever reason, in the terminal a message about `colour.cyan(...) is not a function` appears, when what should be appearing is a message suggesting that the user run `npm install` to make sure all modules are present.
This PR also adds a test to ensure this regression doesn't happen again. Writing the tests was a real odyssey, although you wouldn't know it from the code I committed in the end... ask me about it sometime!
> Fix message about colour when the app crashes

- lib/extensions/extensions.test.js
- package.json
See Issue: https://github.com/alphagov/govuk-prototype-kit/issues/1154
- Replace test runner jest-jasmine2 with jest-circus
- Replace deprecated ".and.callFake" with ".mockImplementation"
> Fix tests to work with jest 27s default test runner

- .gitignore
- __tests__/spec/update-script.js
- app/assets/sass/application.scss
- cypress/integration/1-watch-files/watch-views.cypress.js
- cypress/plugins/index.js
- cypress/scripts/run-as-package.js
- lib/build/check-files.js
- lib/build/tasks.js
- lib/extensions/extensions.js
- lib/usage_data.js
- lib/utils.js
- package.json
- server.js
- start.js
See Issue: https://github.com/alphagov/govuk-prototype-kit/issues/1335
- Allow the kit to be installed as a package
- Integration tests now run against a release archive
- A script has been added to allow Integration tests to simulate running the kit as a package dependency
> Allow running the kit either as a project or as an npm package

- __tests__/spec/update-script.js
There is an unfortunate race condition in the test 'it downloads the latest release of the prototype kit folder', because the update script relies on the prototype kit docs app to direct it to the latest release of the prototype kit, but the tests rely on the GitHub API for the same information. When a release has been made on GitHub but the docs app has not yet finished deployment, the tests will expect a newer version of the kit than the update script will fetch. I couldn't really think of a way around this, and besides I was already unhappy with the fact that the tests were implicitly testing a function of the docs app, so instead this PR loosens the requirements of the test slightly; now we just assert that the script gets the latest release from the prototype kit website.
This fixes …
> Fix race condition in fetch test for update script

- __tests__/spec/update-script.js
I spotted this bug in a [recent failed test run](https://github.com/alphagov/govuk-prototype-kit/runs/6794710853?check_suite_focus=true).
> Fix error message for runScriptSyncAndExpectSuccess

- __tests__/spec/utils.js
- package-lock.json
- package.json
- scripts/create-release-archive
- scripts/create-release-archive.test.js
We need to be able to produce tarball release archives for testing the
kit as a package (as npm will not install from a zip archive).
> Add support for tarballs to create-release-archive script

- docs/documentation/backwards-compatibility.md
> Update v6 docs to refer to 'version 7 and above'

- __tests__/spec/update-script.js
- update.sh
This is useful for testing, you can point it to a release archive you've made yourself with
```
ARCHIVE_FILE=/path/to/govuk-prototype-kit-f00bar.zip update.sh
```
and it will use that to do the update without you having to create the update folder or copy any files.
> Add option to set ARCHIVE_FILE for update script

- cypress.json
- cypress/integration/1-watch-files/watch-custom-styles.cypress.js
- cypress/integration/1-watch-files/watch-images.cypress.js
- cypress/integration/1-watch-files/watch-routes.cypress.js
- cypress/integration/1-watch-files/watch-styles.cypress.js
- cypress/integration/1-watch-files/watch-views.cypress.js
- cypress/integration/utils.js
Increase the default timeouts in the integration tests by specifying them in the cypress config file.  This also makes the tests cleaner as the override timeout option can be removed from the cypress commands.
> Set Integration test default timeouts

- app/assets/sass/application-ie8.scss
- app/assets/sass/unbranded-ie8.scss
- lib/_update_scss/index.js
- lib/_update_scss/update_scss.js
- lib/_update_scss/update_scss.test.js
- lib/middleware/authentication/authentication.js
- lib/middleware/authentication/authentication.test.js
- update.sh
See https://github.com/alphagov/govuk-prototype-kit/issues/1377
Changes:
Create update kit script to perform the removal of the ie8 sass files
Add new post step in update script to execute the update kit script
Remove any references to the ie8 sass files
> Remove support for ie8 styles

- scripts/create-release-archive
- scripts/create-release-archive.test.js
If `--destDir` is a relative path then the create-release-archive script will put the release in the wrong place, or won't be able to create it because the expected directory doesn't exist.
Fix the script so it resolves the file argument to zip/7z.
> Fix bug with release archive script when destDir is a relative path

- __tests__/spec/release-archive.js
- __tests__/spec/update-script.js
- __tests__/util/index.js
- cypress/scripts/run-from-release.js
- scripts/create-release-archive
The run-from-release script used to silently ignore a newer release archive if there was already a test prototype in the directory; which in hindsight isn't very helpful. Instead we let `mkPrototypeSync` overwrite existing files. There's still a chance that I might get my test prototype in a weird state, but there's a better chance now that it will actually run the code I just wrote.
This PR also switches the tests to use tar for creating test release archives, partly in a bid to make the tests slightly faster, and also to allow the overwrite behaviour without having to use the 'dangerous' overwrite option for `unzip`.
> Allow updating test prototype in tmp folder

- __tests__/spec/install.js
- __tests__/spec/release-archive.js
- __tests__/spec/start.js
- __tests__/spec/update-script.js
- __tests__/util/globalSetup.js
- __tests__/util/index.js
- package-lock.json
- package.json
It turns out that if you start the `create-release-archive` script running five times with the same arguments, it will happily start running five process to make the same archive five times. This is usually bad for your computer. Unfortunately, this is exactly what running Jest on a local machine does; I found that every time I ran the tests my computer would just freeze up (even music would stop playing) as it chewed through creating all the release archives.
This PR tries to stop this from happening, by making all the process use the same release archive. When one of the tests asks for a release archive that doesn't exist, it first acquires a lockfile, which tells any other tests that want the same release archive that they should wait for the first test to finish. Unfortunately, the …
> Stop unit tests from creating release archive more than once

- .github/workflows/test.yaml
- cypress.json
We want Cypress to have long timeouts and do lots of retries when running tests on CI, but when running tests locally it is a little annoying. This commit moves the definition of the config 
variables to environment variables in the CI pipeline, rather than in the global configuration file. See Cypress docs [[1]] for details on how this works.
[1]: https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_
> Set Cypress timeouts for CI only

- .gitignore
- cypress/fixtures/custom-styles.html
- cypress/fixtures/larry-the-cat.html
- cypress/fixtures/sass/custom-styles.scss
- cypress/integration/1-watch-files/watch-custom-styles.cypress.js
- cypress/integration/1-watch-files/watch-images.cypress.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- lib/build/tasks.js
The Cypress tests have been very flaky in CI, especially recently. This PR tries to make them more reliable. By waiting for Browsersync to reload the page after the files in the app folder have been changed, we can be sure of when the change has made it to the public folder.
Note that for the watch images test, Browsersync doesn't put its reloading script on our 404 pages or on images, so this commit has to add a page fixture for displaying the image. For the custom styles test I also decided to take the same approach, as it felt more natural to test (easier to do the cleanup) and more in line with what a user might do.
While doing this, I found that our Browsersync setup isn't behaving exactly we would expect. I don't think these are recent regressions though, so I added workarounds to …
> Try and make the integration tests less flaky

- .github/workflows/test.yaml
- lib/utils.js
The session-data-defaults should be accessed correctly when the kit is used as a package.
> Allow data defaults to be accessed correctly when kit is a package

- .github/workflows/test-heroku.yaml
Heroku tests have failed in the past because we haven't been able to
download the binaries for Cypress, use the caches to reduce the chances
of this happening in future.
> Add caching for Cypress binary

- __tests__/spec/update-script.js
- internal_docs/releasing.md
- update.sh
We want to make it easier to work with the update script by making it so that the code only has to deal with one target version. See https://github.com/alphagov/govuk-prototype-kit-docs/issues/26 for more details.
This PR changes the update script to target version 12.1.1 (without changing any of the upgrade logic).
> Change update.sh to pin the version of the kit to upgrade to

- CHANGELOG.md
There are a couple of major changes [[1], [2]] that we've made recently that we forgot to add to the changelog, let's fix that.
[1]: https://github.com/alphagov/govuk-prototype-kit/issues/866
[2]: https://github.com/alphagov/govuk-prototype-kit/issues/1394
> Update changelog with recent major changes

- server.js
this fixes #1455 
it loads after user routes in case someone wants to use this path themselves - theirs will override this
> Redirect old local docs link to the docs site

- CHANGELOG.md
- app/views/layout.html
- package-lock.json
- package.json
Closes #1442 
This also adds the new pagination component to `app/views/layout.html`
**I don't think the update process covers this change, we may need to think about that**
[The release notes mention "Replace deprecated govuk-header__link--service-name class in the header"](https://github.com/alphagov/govuk-frontend/releases/tag/v4.2.0) - we have a reference to this in cypress, I'm not sure if it needs updating?
> Update to GOVUK Frontend v4.2.0

- cypress/scripts/run-as-package.js
- cypress/scripts/run-from-release.js
We don't want the run from release/package scripts to throw if the child process exits with a non-zero status, because then we get unnecessary chaff in our CI logs. Instead just copy the status to our own exit code.
> Squelch errors from run from release/package scripts when npm start is stopped by a signal

- cypress/plugins/index.js
Fix the issue where a cypress test fails to replace text in a file and an unexpected error occurs.
> Cypress not reporting replace text failures

- CHANGELOG.md
- cypress/integration/1-watch-files/watch-javascripts.cypress.js
- lib/build/tasks.js
When working on adding tests for #1481 as suggested by https://github.com/alphagov/govuk-prototype-kit/pull/1481#discussion_r930884251, I noticed that the kit wasn't behaving as expected; when changing the contents of application.js, the page would not be reloaded.
This PR fixes the nodemon config to restore the expected behaviour, as well as adding the tests.
> Fix page reloads when prototype assets are changed

- __tests__/spec/build.js
- __tests__/spec/sanity-checks.js
- lib/build/tasks.js
This is a merge of the PR: https://github.com/alphagov/govuk-prototype-kit/pull/1429 and main.
An update of the jest tests were also required. 
There is currently a known issue with dart sass and jest which calls the sass.compile function to throw in the tests.
The jest sanity-check tests execute the sass.compile function even though it's not the outcome of the sass compile they are testing.  Stubbing the sass.compile function allows the tests to run without throwing any errors caused by the dartsass and jest incompatibility. 
The exception to this is the sanity-check test that actually tests compiling the sass itself.  As there is a compatability issue, and that this functionality is tested sufficiently within the integration tests for watching a css change and checking that it compiles …
> Use new Sass API for compiling stylesheets

- cypress/integration/1-watch-files/watch-javascripts.cypress.js
On node 12 within the CI the integration test watching the javascript file often fails.  I found by adding a one second delay to the test, it passes.
> Fix the node 12 failing watch javascript integration test with a delay.

- __tests__/spec/update-script.js
This should shave off a few seconds on tests, especially on Windows.
> Use fs-extra's copy instead of shelling out to cp

- internal_docs/releasing-from-a-support-branch.md
We are planning to do a support release of the prototype kit soon.
I think we can base our process to do this on what the Design System team do for GOV.UK Frontend [[1]]. This PR copies their documentation to our repo, with a few changes as necessary to make it fit the prototype kit.
Please treat this as just a starting suggestion though, comments and changes are welcome.
[1]: https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing-from-a-support-branch.md
> Add internal docs on releasing from a support branch

- .github/workflows/test.yaml
[Node 18 will become the current LTS 25/10/2022](https://nodejs.org/en/about/releases/)
> Add Node 18 to tests

- lib/config.js
- lib/config.test.js
- lib/extensions/extensions.js
- lib/middleware/authentication/authentication.js
- lib/path-utils.js
- lib/utils.js
- listen-on-port.js
When using the kit as a package, the file app/config.js may not be present. This commit makes it easier for code in lib to import app/config.js by adding a convenience module lib/config.js, that imports the user's file if it exists, and gives an empty object if it doesn't.
I ran into this issue when working on #1518, I'm raising the change in this separate PR to give people a chance to comment on this detail.
> Fix imports of app/config

- .github/workflows/test-download.yaml
- cypress.json
- cypress/download-tests/1-download-latest-release/download.cypress.js
- cypress/plugins/index.js
- cypress/support/commands.js
- package-lock.json
- package.json
Tests to download and extract the latest zip file of the prototype kit.
Please note that as cypress has an issue testing a download from an external page, I have created a custom cypress command to retrieve the href of the download and then download the file manually.
Note also that the download test runs in a seperate action.
> Add cypress download tests v13

- bin/cli
We want to help users avoid committing files that shouldn't be committed; this commit makes it so the install script copies our `.gitignore` file into the user's project.
> Add gitignore to prototype starter files

- package-lock.json
- package.json
Stop npm from complaining when we run tests on Node 18.
> Add Node v18 to supported engines

- bin/cli
It probably isn't useful for users to have the changelog of the kit when in their own prototype when they start one, we historically haven't done this. This commit stops the install command from copying `CHANGELOG`.
> Remove changelog from prototype starter files

- .npmrc
- bin/cli
- prototype-starter/npmrc
npm will never pack a file called `.npmrc` [[1]], so we need to call it `npmrc` in our prototype starter and rename it during install with our script.
[1]: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files
> Copy .npmrc to prototype starter files as npmrc

- CHANGELOG.md
- cypress/e2e/3-link-page-tests/link-page-utils.js
- cypress/fixtures/extensions/extension-bar/filters.js
- cypress/fixtures/extensions/extension-bar/package-lock.json
- cypress/fixtures/extensions/extension-foo/filters.js
- cypress/fixtures/extensions/extension-foo/package-lock.json
- cypress/fixtures/routes.js
- index.js
- lib/filters/api.js
- lib/filters/coreFilters.js
- lib/filters/filters.test.js
- lib/routes/api.js
- lib/routes/api.spec.js
- lib/routes/extensions.js
- lib/routes/prototype-admin-routes.js
- lib/utils.js
- prototype-starter/app/filters.js
- prototype-starter/app/routes.js
- server.js
Allowing the user to create a router.
We explored ideas around more fine grained control instead of providing router functionality but I've reconsidered and think that's better to grow over time alongside providing routers.  We can deprecate the routers at a later date if we want to replace them with more fine grained methods.
> Setup router api

- CHANGELOG.md
- __tests__/spec/sanity-checks.js
- __tests__/util/index.js
- bin/cli
- lib/routes/prototype-admin-routes.js
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v12.2.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v7.0.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v7.1.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v8.0.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v8.2.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v8.5.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v9.0.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v9.11.1.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v9.12.0.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v9.12.1.html
- lib/upgradeToV13/known-old-versions/app-views-layout.html/v9.15.0.html
- package.json
(updated)
New interface is:
`npx govuk-prototype-kit create` - creates a prototype in the current directory
`npx govuk-prototype-kit create /tmp/abc` - creates a prototype an absolute location
`npx govuk-prototype-kit create ../abc` - creates a prototype a relative location 
`npx govuk-prototype-kit create abc` - creates a prototype in a relative location
`npx govuk-prototype-kit create --version 13.0.0` - creates a specific version of a prototype in the current directory
`npx govuk-prototype-kit create --version 13.0.0 abc` - creates a specific version of a prototype in a relative location
> Interface update

- cypress/e2e/6-management-tests/create-new-page-from-template.cypress.js
- lib/assets/sass/internal/manage-prototype.scss
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/index.njk
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/template-install.njk
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/templates.njk
- lib/routes/prototype-admin-routes.js
- listen-on-port.js
Includes:
- add a link to the prototype
- update start up message to match the 'manage' wording elsewhere
- Update template pages with new text
> Manage pages updates

- bin/cli
- package.json
- prototype-starter/package.json
Splits the process of creating a new prototype into two with copying the starter files done after the version of the kit to be used has been installed. This makes sure the user doesn't end up with starter files that require features not available to the installed kit version. This is similar to what the create-react-app tool does [[1]].
Fixes #1616.
[1]:
https://github.com/facebook/create-react-app/blob/main/packages/create-react-app/createReactApp.js
> Ensure that create script installs same version of starter files and kit

- CHANGELOG.md
- internal_docs/releasing.md
- lib/config.js
- lib/filters/api.js
- lib/routes/api.spec.js
- lib/sessionUtils.js
- lib/sessionUtils.test.js
- lib/utils.js
- server.js
Prepare V13 for a refactor to allow plugins/extensions to be added without restarting the application:
- Create a sessionUtilities from utils for session data to prevent a circular reference when refactoring later.
- Add support for globals.
- Catch and handle errors in server and filter api.
- Fix the api tests so the fake router is mocked correctly.
- Fix the numbering in the release docs.
> V13 pre refactor

- bin/cli
- lib/exec.js
Use spawn instead of exec so we can inherit stdio. This makes for a nicer user experience when running `npx govuk-prototype-kit create`, as they can see the full colourful output from npm.
> Show output from npm install when running create script

- lib/build/tasks.js
Make sure first line is separated from second by a newline character.
> Fix formatting of .tmp/sass/_extensions.scss

- __tests__/util/index.js
- bin/cli
We don't want to accidentally end up with development code installed in system Node installation after running tests.
> Stop installing govuk-prototype-kit globally in tests

- .github/workflows/test-download.yaml
- .github/workflows/test.yaml
- .npmrc
- bin/cli
- cypress/scripts/run-starter-prototype.js
- lib/build/tasks.js
- package-lock.json
- package.json
Stop showing users an error if they run the kit on Windows without using Bash.
Bash is no longer a requirement of running our tests or the kit, so this PR changes our tests to use the default shells on Windows rather than forcing the use of Bash.
We also change the `.npmrc` file the user receives so that it does not try and use bash for `npm run` on Windows.
> Support cmd.exe and PowerShell

- CHANGELOG.md
- bin/cli
We want to make sure users have NODE_ENV=production set when their prototypes are hosted online, because that controls a lot of important behaviour including the password control and HTTPS redirects. To make this easier, this commit adds a command to the cli tool that sets NODE_ENV and then does the build and run. We also add these commands to the starter files package scripts.
---
This is part of resolving #1202, although it keeps the behaviour of `npm start` the same for now.
> Add serve and dev scripts

- govuk-prototype-kit.config.json
- lib/routes/prototype-admin-routes.js
We decided to insist on templates having a type, I added a console warning but didn't actually omit them from the list.  As a result we didn't actually include the type on our own templates.
This PR actually omits templates without a "nunjucks" type and sets our templates to "nunjucks".
> Setting template type

- __tests__/util/index.js
Account for spaces in process.execPath
> Fix tests on windows

- CHANGELOG.md
- bin/cli
- lib/config.js
- lib/config.test.js
Change the default configuration of the kit so that when the kit is run in production (`NODE_ENV=production`) the cookie session store is used instead of the memory session store. The impact of this is that session data will default to be preserved between server restarts, and the user will not see a warning from `express-session` in their server logs every server restart.
This PR still defaults to using the memory session store when running the kit locally, and the configuration can still be overridden.
> Change default session store to cookie store when in production mode

- CHANGELOG.md
- __tests__/util/index.js
- bin/cli
- package.json
- scripts/create-prototype-and-start.js
We want to make sure that whatever service a user might be running their prototype online, they use the production scripts and configuration. Unfortunately, there isn't a standard way to detect whether a project is running in production or not; not all services set NODE_ENV [[1]], not all services will read a Procfile, etc. The only surefire way we can think of is to make it so that running `npm start` in a prototype runs the production code by default.
[1]: https://github.com/alphagov/govuk-prototype-kit/issues/1202
Unfortunately, this is a breaking change, as previously we told users to run `npm start`. We want to catch what we suspect will be a common case, where the user runs `npm start` having been used to that from before, and then ends up with a prototype that isn't working and no …
> Make serve default command

- cypress/e2e/6-management-tests/install-available-plugin.cypress.js
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/plugin-install-or-uninstall.njk
and change the start command to npm run dev
as discussed with @NoraGDS 
Preview (ignore broken fonts)
> add ctrl c command

- listen-on-port.js
Put the URL of the main page last, so it is most prominent.
Also, only show the start message when running prototype locally.
---
Example:
```
/tmp/govuk-prototype-kit-test at 16:31:56
% npm start
> start
> govuk-prototype-kit start
GOV.UK Prototype Kit 0.0.1-beta.1
starting...
You can manage your prototype at:
http://localhost:3000/manage-prototype
The Prototype Kit is now running at:
http://localhost:3000
```
> Change order of start messages

- CHANGELOG.md
- lib/build/tasks.js
- lib/config.js
- lib/config.test.js
- lib/path-utils.js
- lib/sessionUtils.js
- package-lock.json
- package.json
- server.js
This PR removes support for the cookie session data store, and uses a [file store](https://www.npmjs.com/package/session-file-store) instead.
When running the kit locally this will preserve session data between restarts, which is useful for users when they are editing their routes file a lot.
When running online with a PaaS such as Heroku we expect for most service providers the storage will be ephemeral, so we can't guarantee the data will be preserved there. There is a possibility that some service providers might make it difficult for the kit to save data to disk, but since we're doing this already with compiled CSS files and the like I think if that becomes an issue session storage will not be the only blocker.
File storage is potentially slower and more resource-intensive than memory …
> Use file store for session data

- cypress/plugins/index.js
- package.json
Fix timeouts in file existence checks so they work correctly.
Also allow npm script run:package to work when system temp folder is not accessable.
> Fix file existence checks in tests

- __tests__/spec/build.js
- __tests__/spec/force-https-redirect.js
- __tests__/spec/sanity-checks.js
- lib/build/tasks.js
- lib/extensions/extensions.js
- lib/path-utils.js
- server.js
Previously integration tests were running the kit incorrectly, with `projectDir` being equal to the kit repo folder.
This was result in some weird behaviours: the `.tmp` folder was being created in the repo directory rather than the project directory; tests of `govuk-frontend` assets were testing the versions in the repo, not the version installed in the project.
> Fix integration tests so they run in test folder rather than in repo

- .github/workflows/lint.yaml
- .github/workflows/test-download.yaml
- .github/workflows/test-heroku.yaml
- .github/workflows/test.yaml
Updates the version of Node used by the action from 12 to 16, silencing the warnings from GitHub Actions.
> Bump @actions/checkout from 2 to 3

- lib/migrator/fileHelpers.js
Some files may not have been consciously changed by the user but may have been reformatted by a user's editor.
This change is to prevent these files as being identified as changed.
> Ignore whitespace differences in migration

- bin/cli
- package-lock.json
- package.json
- server.js
Older versions of the kit came with support for GOV.UK Notify out-of-the-box. We don't want to include extra dependencies going forwards, but to avoid breakage let's keep that package around when migrating.
Closes #1701.
> Add notifications-node-client to dependencies for migrated prototypes

- lib/build/tasks.js
- package-lock.json
- package.json
We have been seeing some weird bugs with watching the `.env` file, which this change fixes by simplifying how we use nodemon.
<details>
<summary>More details on the issue and hypothesis</summary>
The issue I was seeing was that on my machine (macOS), when a .env file was present, nodemon would restart the server whenever a page was visited because the session store JSON files were updated. What’s weird about that is that while that isn’t the behaviour we want, it’s the behaviour described by the nodemon config. But when there was no .env file, it wasn’t detecting the changes to those .tmp/session/*,json files. On Ben’s machine (Linux), we got a different behaviour, it wouldn’t detect the changes to the session JSON files, whether or not .env was present, but it also didn’t detect changes …
> Fix nodemon configuration

- bin/cli
I noticed while looking at the migration stuff that the `.npmrc` and `.gitignore` files had extra lines at the start of the file, which we don't want.
> Remove leading newlines from files generated by create script

- lib/nunjucks/govuk-prototype-kit/includes/stylesheets-extensions.njk
- lib/nunjucks/govuk-prototype-kit/includes/stylesheets.html
- lib/nunjucks/govuk-prototype-kit/layouts/unbranded.html
- server.js
When we added `application.css` to the plugins system [[1]], we accidentally broke the unbranded layout. There isn't an alternative quick fix because of the way the unbranded layout hooks into and basically duplicates `application.css`, so we're just going to back out that change and revisit after v13.
This PR removes `application.css` from extensionsConfig, and adds it to the stylesheets template include. Now you don't need to have `application.css` included in every page.
[1]: https://github.com/alphagov/govuk-prototype-kit/blob/bf4474e0b05957465c91b87d76e055250c0fd06c/server.js#L56
Fixes #1705.
> Fix unbranded template

- .github/workflows/test.yaml
- CHANGELOG.md
- package-lock.json
- package.json
Update engines directive in package.json to show that we support Node 18 LTS. Add tests on Node 18 to make sure that we do.
> Allow Node 18 to be used (v12)

- lib/nunjucks/govuk-prototype-kit/includes/homepage-top.njk
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/manage-prototype-not-available.njk
- lib/nunjucks/govuk-prototype-kit/layouts/govuk-branded.html
- lib/routes/prototype-admin-routes.js
- listen-on-port.js
- server.js
When not in dev mode:
- Starting banner displaying management pages address is not displayed
- Links to the management pages are removed
- Attempts to access the management pages (excluding password and clearing data) will display a page displaying a message indicating the pages are not available.
> Display a message on management pages when not dev mode

- lib/assets/sass/unbranded.scss
- lib/build/tasks.js
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/password.njk
I noticed that one of the text lines wasn't formatted correctly on the password page, because it was missing the `govuk-body` class. Digging deeper, it seems that we used to expect that the GOV.UK frontend global styles would work for pages using the 'unbranded' stylesheet, but it stopped in the rework for v13.
The issue is that we import the govuk-frontend settings in the unbranded template, before we set the govuk-global-styles variable to true. Previously this was fine because we were setting that variable strongly, however in v13 we added the `!default` thingy [[1]], because we want users to be able to override the value in `settings.scss`. I think this behaviour is unavoidable, but luckily there is a workaround; we were only importing the settings to get …
> Fix global styles for unbranded layout

- package-lock.json
Bumps socket.io, socket.io-client, socket.io-parser.
Resolves https://github.com/advisories/GHSA-qm95-pgcg-qqfq.
> Bump socket.io packages to close security alert

- cypress/e2e/dev/6-management-tests/management-available.cypress.js
- cypress/e2e/prod/2-management-tests/management-not-available.cypress.js
See https://github.com/alphagov/govuk-prototype-kit/issues/1695
- Acceptance tests to make sure the manage prototype pages are not available in production
> Manage pages availability tests

- .github/workflows/test.yaml
- __tests__/spec/migrate.js
- bin/cli
- lib/build/tasks.js
- lib/migrator/fileHelpers.js
- lib/migrator/fileHelpers.spec.js
- server.js
Avoid situations where we might have mixed line-endings, use unix line-endings everywhere (including in our CI tests).
> Use unix line-endings everywhere

- bin/cli
We've had reports from users that the .tmp folder is shown as not ignored by their IDE (IntelliJ types it seems), even though that folder contains a gitignore. Let's add `.tmp` to the starter .gitignore to stop people being confused by their IDE, but keep the `.tmp/.gitignore` behaviour to cover situations where the `.gitignore` file is missing
for some reason. This is a bit belt-and-braces, but doesn't really have a downside.
> Add .tmp folder to starter .gitignore

- cypress/e2e/smoke/0-smoke-tests/index-page.cypress.js
- lib/extensions/extensions.js
We found when testing v13 beta 2 (0.0.1-beta.2 on npm) that the GOV.UK Frontend fonts weren't working, even though the same code worked when creating a prototype linked to the local files.
This is because the check for whether the 'legacy' GOV.UK Frontend fixes are needed was using a hardcoded path into `node_modules`, which depends on how the node_modules folder is laid out. When installing the kit with a link to local files the `govuk-frontend` folder is at a different level. Making the path relative to the project dir fixes this.
> Fix loading of front-end legacy assets

- lib/extensions/extensions.test.js
- package-lock.json
- package.json
Closes #1737 
---
Note that I've put a fairly lax requirement on the version of govuk-frontend; we could tighten this up to be greater than version 3, less than version 5, and in future release another version when we've verified what changes we need to make (if any) to support v5. But right now I'm not expecting v5 to require changes to the kit itself, as we've made much of the plugin architecture loose such that the initialisation code required is in the plugin package, not the kit.
Alternatively we could change the version requirement to '*', so users can use any version of govuk-frontend, although I think we'd prefer they use the better colour scheme and new link styles I don't think there's any major impediment to using the kit with older versions of govuk-frontend.
Of course, …
> Make govuk-frontend a peer dependency

- .github/workflows/test-acceptance.yaml
- __tests__/util/index.js
- cypress/e2e/smoke/0-smoke-tests/index-page.cypress.js
- cypress/scripts/run-starter-prototype.js
- package.json
Changes Cypress tests so they run against a prototype that is setup similar to how users will have the kit installed.
Because we're using `--version local` for tests, npm is installing a folder, and by default will just create a symlink to that folder, rather than installing the package and all dependencies [[1]]. This means the `node_modules` folder is laid out differently to how it would be for real users, which can cause issues (see ticket #1741 for example). We can change the behaviour however by setting the `install-links` config variable to true [[2]]. This PR adds a line to set this in the Cypress server start script, meaning that the test prototype is installed in a more representative fashion.
As a result we can also improve the tests for checking whether the GOV.UK Frontend …
> Make acceptance tests more realistic

- .github/workflows/test.yaml
- CHANGELOG.md
- package-lock.json
- package.json
Node 12 has reached end of life (EOL), and Node 14 will reach end of life within the lifetime of GOV.UK Prototype Kit 13. Users shouldn't be using EOL versions of Node, as they do not receive security fixes. Let's stop supporting these versions, to reduce our maintenance burden. This commit removes them from the test matrix and the engines directive of the package.json.
Part of #1124.
> Drop support for Node.js 12, 14

- cypress/e2e/dev/6-management-tests/install-available-plugin.cypress.js
The cypress test needs to be updated as the latest step by step version is now 2.1.0
> Fix step by step plugin test

- __tests__/fixtures/test-v11-prototype/app/assets/sass/application.scss
- __tests__/spec/migrate.js
- lib/migrator/index.js
- lib/migrator/migrationSteps.js
- lib/migrator/migrationSteps.spec.js
Also tidy, tests and add code to the test application.scss after the line to designate user code, to prove the code is retained when the top of the file is removed.
> Report fewer failures in migration script

- lib/migrator/fileHelpers.js
- lib/migrator/index.js
- lib/migrator/migrationSteps.js
- lib/migrator/migrationSteps.spec.js
- Split up the updateIfUnchanged migration step to make it easy to maintain and simplify tests to match.
- Add deleteIfUnchanged step to simplify steps.
- Add deleteEmptyDirectories step so that functionality can be moved into migrationSteps file with the other steps.
> Remove sass includes with patterns

- known-plugins.json
- lib/routes/prototype-admin-routes.js
- package.json
HMCTS Frontend hasn't been updated for 2 years [[1]], and is archived on GitHub [[2]]. We probably don't want to point users towards it.
[1]: https://www.npmjs.com/package/@hmcts/frontend
[2]: https://github.com/hmcts/frontend
> Remove @hmcts/frontend from available plugins list

- lib/utils.js
Default port can no longer be set by changing server.js, let's just remove this message. In future we should add something to the docs on setting port numbers, and then we can link users to that.
> Update message about setting default port

- npm-shrinkwrap.json
Quick PR to update to [**GOV.UK Frontend v4.4.0**](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.0)
Follows on from:
* https://github.com/alphagov/govuk-prototype-kit/pull/1654
> Update to `govuk-frontend@4.4.0` for tests

- __tests__/spec/migrate.js
- prototype-starter/app/filters.js
- prototype-starter/app/routes.js
Something I discussed with @nataliecarey a while back but forgot about, not urgent but nice to have.
This splits the `require` lines in the starter files in 2 - one to get `govuk-prototype-kit` and another for whatever the relevant file needs (eg `router`).
This means `govukPrototypeKit` is available for users which seems flexible and future proof
> Split require lines in starter files

- __tests__/spec/migrate.js
- prototype-starter/app/assets/javascripts/application.js
- prototype-starter/app/assets/sass/application.scss
- prototype-starter/app/routes.js
- prototype-starter/app/views/layouts/main.html
closes #1760 
add links to documentation in starter files:
- app/assets/javascripts/application.js
- app/assets/sass/application.scss
- app/routes.js
- app/views/layouts/main
> Link to docs

- README.md
- internal_docs/releasing-from-a-support-branch.md
- internal_docs/releasing.md
- lib/assets/sass/unbranded.scss
- lib/middleware/authentication/authentication.js
- lib/middleware/authentication/authentication.test.js
- lib/migrator/index.js
- lib/nunjucks/govuk-prototype-kit/internal/views/manage-prototype/index.njk
- lib/usage-data-prompt.txt
- server.js
update various references in code and documentation
leaves references in:
- Changelog as it is a historical record and the redirects will catch it
- migration scripts and tests where the reference needs to match old code
> Update domain from heroku to service.gov.uk

- .github/ISSUE_TEMPLATE/tech-debt.yaml
Adds copy of tech debt issue template form from GOV.UK Frontend repo:
https://github.com/alphagov/govuk-frontend/blob/a5c3b32c2f426a4b49c16546fa83692b0821ebc3/.github/ISSUE_TEMPLATE/tech-debt.yaml
> Add tech debt issue form

- CHANGELOG.md
- lib/migrator/index.js
- lib/migrator/known-old-versions/app-assets-sass-application-ie8.scss/v7.0.0.scss
- lib/migrator/known-old-versions/app-assets-sass-unbranded-ie8.scss/v9.5.0.scss
Version 13 does not support IE8, so there is never any value in keeping the IE8 Sass files. This PR changes the migration script so that those files are always deleted.
> Always delete IE8 Sass files when migrating existing prototype

- CHANGELOG.md
- lib/templates/content.html
- lib/templates/question.html
closes #1187 
Headings in services should generally be `govuk-heading-l`.
Changed:
- question page
- content page
The others seem ok at XL
> Fix heading sizes in templates

- CHANGELOG.md
- lib/nunjucks/govuk-prototype-kit/backup-homepage.html
- server.js
Includes changes from #1688.
---
> Update content of backup homepage

- lib/routes/prototype-admin-routes.js
Any plugin with a dependency reference starting with 'file:' will have the upgrade option in the manage plugins page omitted.
> Fix upgrade bug on test plugins

- .github/workflows/test-acceptance.yaml
- cypress/e2e/prod/1-home-page-tests/home-page-in-production.cypress.js
- cypress/e2e/prod/2-management-tests/management-not-available.cypress.js
- cypress/e2e/prod/2-management-tests/password-page.cypress.js
- cypress/e2e/utils.js
- cypress/events/index.js
See: [Add tests for passwprd page](https://github.com/alphagov/govuk-prototype-kit/issues/1609)
- Update git workflow env variables for production tests to force authentication page
- Add cypress authenticate utility function to authenticate using the password page
- Update cypress prod tests to call cypress authenticate utility function
- Add a valid password test
- Add an invalid password test
> Test password page

- CHANGELOG.md
- __tests__/spec/migrate.js
- lib/migrator/fileHelpers.js
- lib/migrator/index.js
- lib/migrator/logger.js
- lib/migrator/logger.test.js
- lib/migrator/migrationSteps.js
This PR makes the logging of paths by the migration script more consistent, closing #1816.
It also works to ensure that the user's home path won't end up in `migrate.log`, so their computer username is now less likely to leak.
> Stop user's home path from being printed in migration script log

- CHANGELOG.md
- lib/sessionUtils.js
- lib/utils.js
- lib/utils.test.js
session-file-store logs every time it prunes files for expired sessions, but this isn't useful for our users, so let's just swallow those messages.
Closes #1812.
> Stop showing messages from session-file-store about deleting expired sessions

- CHANGELOG.md
- cypress/e2e/dev/6-management-tests/create-new-page-from-template.cypress.js
- lib/routes/prototype-admin-routes.js
- lib/utils.js
- server.js
See: [You can create a page from a template with no name](https://github.com/alphagov/govuk-prototype-kit/issues/1810)
Added validation and acceptance tests for:
- Path already exists
- Path not entered
- Path only containing spaces
- Path with only a single slash
- Path missing a starting slash
- Path ending in a slash
- Path containing consecutive slashes
- Path containing a search parameter
- Path containing spaces
- Path including invalid characters
> Improve path validation of templated created pages

- lib/migrator/migrationSteps.js
- lib/migrator/migrationSteps.spec.js
See: [Migration script does not always migrate app/views/includes/{head, scripts}.html](https://github.com/alphagov/govuk-prototype-kit/issues/1817)
> Migration will now report head and script failures

- npm-shrinkwrap.json
This PR bumps the version of GOV.UK Frontend used in local development.
Note that this release includes an important accessibility fix.
- [Release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.1)
- [Changelog](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md)
- [Commits](alphagov/govuk-frontend@v4.4.0...v4.4.1)
> Bump govuk-frontend from 4.4.0 to 4.4.1

- CHANGELOG.md
- __tests__/spec/sanity-checks.js
- bin/cli
Ticket: https://github.com/alphagov/govuk-prototype-kit/issues/1670
This will make the initial commit as the current user if they have set up a email address etc. in git, if they haven't set that up it will be committed as the Prototype Kit with the team email address - this is mostly for CI but it would also be useful for a user who has just set up a new computer and hasn't set up git properly yet.
As each of the test clients have git installed I have manually tested on an Ubuntu VM without git.  It works.
> Create a git repository for new prototypes (when git is present)

- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/plugins/plugins.js
To make unit tests easier to write, the handlers for each route have been moved into a separate manage-prototype-handlers.js file and unit tests have been written to test these handlers .
> Increase manage prototype unit tests

- __tests__/spec/sanity-checks.js
- bin/cli
- bin/utils/argv-parser.js
- bin/utils/argv-parser.spec.js
- lib/exec.js
- lib/exec.test.js
The core of this update is to allow the user to opt-out of creating a git repo with the `--version-control=none` command.
To get to that I had to pass argv options through from `create` to `init`, I realised we weren't supporting quote marks and speech marks around options so I've added support for those and used it when passing options through to allow for multi-word options.  I added tests for this.
I also found it hard to deal with error messages when using `exec` while debugging so I added more details on errors from `exec`.  I added tests for this.
I tested with @joelanman on Windows and Mac with and without git, these tests showed up a scenario where the user had `git` but not `which` so I changed the code around to succeed in this circumstance.
We also found that it's quite easy to …
> Allowing the user to opt-out of version control

- npm-shrinkwrap.json
Bumps json5 in dev dependencies to quiet audit warnings.
This was done by running `npm audit fix`.
> Bump json5 in dev dependencies to quiet audit warnings

- cypress/e2e/dev/1-watch-files/watch-config.cypress.js
- cypress/e2e/dev/1-watch-files/watch-custom-styles.cypress.js
- cypress/e2e/dev/1-watch-files/watch-images.cypress.js
- cypress/e2e/dev/1-watch-files/watch-javascripts.cypress.js
- cypress/e2e/dev/1-watch-files/watch-routes.cypress.js
- cypress/e2e/dev/1-watch-files/watch-styles.cypress.js
- cypress/e2e/dev/1-watch-files/watch-views.cypress.js
- cypress/e2e/dev/2-page-component-tests/checkboxes.cypress.js
- cypress/e2e/dev/3-link-page-tests/branching-journey.cypress.js
- cypress/e2e/dev/3-link-page-tests/change-answers.cypress.js
- cypress/e2e/dev/3-link-page-tests/link-index-to-start.cypress.js
- cypress/e2e/dev/3-link-page-tests/link-page-utils.js
- cypress/e2e/dev/3-link-page-tests/simple-journey.cypress.js
- cypress/e2e/dev/4-step-by-step-tests/step-by-step-journey.cypress.js
- cypress/e2e/dev/5-plugin-tests/install-plugin-test.cypress.js
- cypress/e2e/dev/5-plugin-tests/multi-combined-plugin-test.cypress.js
- cypress/e2e/dev/5-plugin-tests/multi-plugin-test.cypress.js
- cypress/e2e/dev/5-plugin-tests/single-plugin-test.cypress.js
- cypress/e2e/dev/6-management-tests/change-service-name.cypress.js
- cypress/e2e/dev/6-management-tests/clear-data-page.cypress.js
- cypress/e2e/dev/6-management-tests/create-new-page-from-template.cypress.js
- cypress/e2e/dev/6-management-tests/edit-home-page.cypress.js
- cypress/e2e/dev/7-layout-tests/default-layout.cypress.js
- cypress/e2e/plugins/0-plugins-tests/install-available-plugin.cypress.js
Cypress best practice is not to use an `after` hook unless it is strictly necessary [[1]]. This commit refactors all our acceptance tests so that any state setup is done before, not after, the spec. As well as making it easier to see what the state was for a failed test, it also should hopefully mean we can spend less time waiting for the kit to restart.
The downside is that it's more work to isolate each test from each other, as you have to make sure you reset everything that *could* affect the test in the `before` hook, even if you don't change that file in the test itself. As an exercise it does help to improve one's understanding of the test and the kit though!
[1]: https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks
> Simplify Cypress before and after hooks

- CHANGELOG.md
- bin/cli
- bin/utils/argv-parser.js
- bin/utils/index.js
- migrator/file-helpers.js
This commit also includes improvements to the interface between the `create` and `init` commands.
> Creation messaging

- .github/workflows/test-acceptance.yaml
- cypress/e2e/plugins/0-plugins-tests/install-available-plugin.cypress.js
- lib/assets/javascripts/manage-prototype/manage-plugins.js
- lib/dev-server.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/nunjucks/views/manage-prototype/plugin-install-or-uninstall.njk
- lib/nunjucks/views/manage-prototype/plugins.njk
- lib/plugins/plugins.js
This is based and expanded from some of the experimental ideas that Laurence had worked on prior to leaving the team.  This PR is here so that the work is not lost.  Some of the unfinished work has been expanded to give the functionality to install a specific plugin version as will be required soon.
The following changes are included:
- Allow the install of a specific plugin version using the UI by linking directly to the install action page including a version in the query string.
- Add validation to check the specific version exists.
- Update plugins unit tests to test for this new functionality.
- Update plugins acceptance tests to test this new functionality.
- Tidy up the declaration of body, query, and params properties within the unit tests for plugins.
> Install a specific plugin version

- CHANGELOG.md
The change log was updated incorrectly durring a merge for https://github.com/alphagov/govuk-prototype-kit/pull/1915
This moves the entry to the correct position in the file.
> Correct the change log

- bin/cli
When we released `v13.2.0` and `v13.2.1` we knew we had to work with situations where an older installer creates a new version of the kit.  What we implemented  in `v13.2.0` worked with a new installer but not an old installer, what we implemented in `v13.2.1` works with an old installer but not with a new installer.  This version recognises that `create` and `init` need to be handled separately even though they're in the same file because they can be run from different versions.
To test the current live version:
`npx govuk-prototype-kit@13.2.1 create ~/somewhere`
To test this version:
`npx govuk-prototype-kit@github:alphagov/govuk-prototype-kit#fix-create-message create --version=alphagov/govuk-prototype-kit#fix-create-message ~/somewhere`
You can also mix older versions and newer …
> Fixing create message

- CHANGELOG.md
- lib/assets/javascripts/manage-prototype/manage-plugins.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
This fix resolves the following:
The **13.1.0** status request from the browser is: **/manage-prototype/plugins/status**
The **13.2.3** route **/manage-prototype/plugins/:mode** is matching the request where a mode of 'status' is not the expected 'install, uninstall, or upgrade'.
This causes the error status to be returned which triggers the error to be displayed.
> Allow smooth upgrade from 13.1.0 to 13.2.4

- cypress/e2e/plugins/1-available-plugins-tests/available-plugins.cypress.js
See: 
- [Create task list plugin](https://github.com/alphagov/govuk-prototyp-kit/issues/1913)
- [Move templates and patterns to plugins](https://github.com/alphagov/govuk-prototype-kit/issues/1653)
Note, this is dependent on [Move Common templates to the Common templates plugin](https://github.com/alphagov/govuk-prototype-kit/pull/1923)
> Add acceptance tests for task-list plugin

- cypress/e2e/plugins/2-prototype-kit-plugin-tests/prevent-uninstalling-kit-from-ui.cypress.js
- lib/manage-prototype-handlers.js
Currently it is possible to uninstall the kit directly from a supplied link.  This blocks that action.
Please note this is dependent on [Refactor plugin tests](https://github.com/alphagov/govuk-prototype-kit/pull/1940)
> Prevent uninstalling kit from ui

- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- cypress/e2e/plugins/plugin-utils.js
- lib/assets/javascripts/manage-prototype/manage-plugins.js
- This makes the plugins tests more stable by making sure the step-by-step plugin is unistalled before the tests begin.
- Additional logging within the tests themselves was added so the timing of the tests can be observed to be in sync with the kit.
- A delay in the front end of two seconds after receiving the completed status gives the kit extra time to have updated the installed plugins prior to giving the user the option to return to the plugins page.
> Fix plugin install acceptance tests

- cypress/e2e/dev/1-watch-files/watch-javascripts.cypress.js
The original cypress test for watching the update of the application.js file was occasionally problematic as it was testing for the browser sync and not just for the symptom caused by the javascript updating.  The new test just waits for the heading in the page to change which will only happen when the changed application.js script is executed.
> Let cypress test the symptom and not the implementation

- __tests__/spec/install.js
- known-plugins.json
- lib/manage-prototype-handlers.js
- lib/plugins/plugins.js
See [Make Notify client a Plugin](https://github.com/alphagov/govuk-prototype-kit/issues/1710)
- Added notifications-node-client to the list of known plugins
- Allow known plugins to be installed without a plugin config
- Simplify some of the functionality
- Rename some functions to make them easier for the new starters
- Allow install.js test to pass in windows node 18.x (This shouldn't have been affected by this change, but was)
> Make notifications node client available

- CHANGELOG.md
- __tests__/spec/migrate.js
- bin/cli
This should fix #1898 
previously: calls to npx, which then executes the cli file (not always allowed)
changed to: a call to node (which is allowed) to run the cli file
I think the logic is also easier to follow - previously npx was executing code in node_modules but that was not clear
> Fix permissions bug on managed devices by calling node directly

- CHANGELOG.md
- __tests__/spec/migrate.js
- bin/cli
The changes made to support GDS Managed Laptops creates a new external interface for the kit code which we'd like to avoid if we can.  This reverts it while we look at our options.
> Rollback package scripts

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
New features:
- GOV.UK Notify client is now available as a plugin. You can install it from the Plugins page in the Manage your prototype section.
- We have moved all of the templates to plugins to have more flexibility in the future. 
- When you create a new prototype the common templates are installed by default.
- When you update an existing prototype, you can install the common templates from the Templates page. 
- Task list is now a separate plugin.
> Preparing for release 13.3.0

- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
See: [Don't require a leading slash when creating a page from a template](https://github.com/alphagov/govuk-prototype-kit/issues/1660)
- Made changes to the manage prototype handler
- Updated the unit tests
> Remove require leading slash

- cypress/e2e/dev/1-watch-files/watch-settings-styles.cypress.js
- lib/build.js
- lib/dev-server.js
- prototype-starter/app/config.json
See [Adding a settings.scss file requires a manual restart](https://github.com/alphagov/govuk-prototype-kit/issues/1945)
- Watch for the creation of the settings.scss file and add the include statement to the proxy sass file for settings.scss
- Watch for the deletion of the settings.scss file and remove the include statement from the proxy sass file for settings.scss
- Add a cypress test to make sure the functionality above works and the page updates as expected with the changes
> Auto restart when settings created and removed

- lib/assets/javascripts/kit.js
- lib/assets/javascripts/manage-prototype/manage-plugins.js
- lib/assets/javascripts/manage-prototype/manage-plugins.test.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/nunjucks/views/manage-prototype/plugin-install-or-uninstall.njk
- npm-shrinkwrap.json
- package.json
Fixes the following:
- Installs, Upgrades, and Uninstalls will complete successfully even on a slow connection
- Multiple windows and tabs can be used to simulataneously initiate multiple Installs, Upgrades, and Uninstalls
- Each action above within each window or tab is subject to a 30 second timeout on the front end. 
- Added unit tests for front end javascript
> Make sure install, upgrade and uninstall complete successfully.

- lib/dev-server.js
When we're developing the kit we use a symbolic link to load our version of the kit into a "companion kit" (any prototype that uses the dev version).  We don't get the benefit of auto restarting when we make changes.  This PR solves that.
If it detects a symbolic link in the `node_modules` directory (including scoped packages) it will watch them for changes and reload the app when `.js` or `.json` files change.
Average users won't have this behaviour as they won't be using symbolic links in their node modules.
> Watching dependencies that are symbolic links.

- bin/cli
- scripts/refresh-companion-kit
On my machine I always get a symlink when I run `create` with `--version=local` but we've had a few people report that it doesn't happen for them.  This introduces `--version=local-symlink` to make sure you're working with a symlink.
I've added this on top of a previous PR (https://github.com/alphagov/govuk-prototype-kit/pull/2015) which watches for changes in symlinked dependencies.
Together these two changes make working on the kit more reliable and smoother.
> Making symlinks more reliable when working on the kit

- lib/session.js
- lib/utils/index.js
- Using working directory path to create session name now (as the service name was frequently causing clashes)
- Suppressed the number of duplicate error messages logged
- Replaced standard sesssion-file-store warning with a custom warning message which is more useful to the user
> Fixing errors about session file store (issue 1733)

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
New Prototype Kit release: 13.4.0
New features:
- When you create a page from a template, you do not need to use a leading slash.
- When you create or remove the settings.scss file, the page styling will update automatically.
- You can now install, upgrade and uninstall different prototype kits at the same time using multiple tabs and windows.
- You can complete an install, upgrade and uninstall with a slow connection.
> Preparing release 13.4.0

- lib/build.js
- lib/config.js
- lib/config.test.js
- lib/dev-server.js
- lib/manage-prototype-handlers.js
- lib/plugins/plugins.js
- lib/utils/performance.js
To use this you can either edit the `config.json` or set environment variables.  I recommend using the environment variables.  Example usage:
Turn on all fine-grained performance logs:
```
LOG_PERFORMANCE=true npm run dev
```
Log performance summaries every 10 seconds and one performance summary when the dev server has started:
```
LOG_PERFORMANCE_SUMMARY=10000 npm run dev
```
Log performance summaries every 10 seconds (and one performance summary when the dev server has started) as well as all fine-grained performance logs:
```
LOG_PERFORMANCE=true LOG_PERFORMANCE_SUMMARY=10000 npm run dev
```
Only show fine-grained performance logs for one area (matching by partial strings, case sensitive):
```
LOG_PERFORMANCE=true LOG_PERFORMANCE_MATCHING=generateAssetsSync npm run dev
```
Only show …
> Added performance logging.

- CHANGELOG.md
- __tests__/fixtures/test-v11-prototype/app/views/nested-test-folder/unbranded-test.html
- __tests__/spec/migrate.js
- lib/utils/index.js
- migrator/index.js
- migrator/migration-steps.js
- migrator/migration-steps.spec.js
- migrator/migrator.spec.js
See [Migration script doesn't update extends lines](https://github.com/alphagov/govuk-prototype-kit/issues/1842)
- All occurences of "layout_unbranded.html" within the nunjucks files in the users app folder will be replaced with "govuk-prototype-kit/layouts/unbranded.html" during the migration process.
> Update extends unbranded correctly during migrate

- CHANGELOG.md
- cypress/e2e/dev/6-layout-tests/title-variable.cypress.js
- lib/nunjucks/govuk-prototype-kit/layouts/govuk-branded.njk
- lib/nunjucks/views/manage-prototype/layout.njk
- prototype-starter/app/views/index.html
@frankieroberto [contributed a PR for this](https://github.com/alphagov/govuk-prototype-kit/pull/1976) with the comment "One possible implementation for https://github.com/alphagov/govuk-prototype-kit/issues/1975."
I have taken that PR, added tests and changed the behaviour slightly.  It now works as follows:
- You can override the `pageTitle` block (as we have recommended so far) which gives you full control over the page title.
- You can set a `title` variable and the `title` will have ` - <serviceName> - GOV.UK Prototype Kit` added to the end of it
- You can set a `title` variable and a `titleOrganisation` the `title` will have ` - <serviceName> - <titleOrganisation>` added to the end of it
Next steps:
- @frankieroberto can you check my PR and make sure it's in line with your …
> Make it easier to set a page title

- cypress/e2e/plugins/1-available-plugins-tests/available-plugins.cypress.js
The dist-tags in npm for common-templates no longer mention version 1.0.0 since 1.1.1 was published.
> Fix tests as common templates dist-tags have lost version 1.0.0

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2030: Make it easier to set a page title](https://github.com/alphagov/govuk-prototype-kit/pull/2030)  
Set pageName variable on a page and the kit will make a GOV.UK page title for you.  
- For example `{% set pageName="My example page" %}`
- [#2035: Support html and njk extensions](https://github.com/alphagov/govuk-prototype-kit/pull/2035)  
Allows .html and .njk to be used interchangeably:
- The default for creating views from templates will be .html, but .njk will be used if the app/config.json contains `"useNjkExtensions": true`.
- If two views are in the same location with the same name but with different suffixes (html or njk), the default suffix (determined by the existence of the useNjkExtensions setting above) will be matched first followed by the alternative.
- [#2039: …
> Release to v13.5.0

- server.js
Having looked at the test url removing disallow * from robots has allowed specification of no-index which is now being recognised by Google URL Tools.
> removed robots.txt to test with google tools

- lib/usage-data.js
When running some accessibility tests this line of dashes was unhelpful when using a screenreader.
In this PR I replace the line of dashes with an underline format.
> Using formatting for underline rather than additional characters.

- cypress/e2e/plugins/0-mock-plugin-tests/single-plugin-test.cypress.js
- cypress/fixtures/plugins/plugin-foo/govuk-prototype-kit.config.json
- cypress/fixtures/plugins/plugin-foo/scripts/foo-module.js
- cypress/fixtures/plugins/plugin-foo/scripts/foo-submodule.js
- cypress/fixtures/plugins/plugin-foo/views/foo.njk
- lib/nunjucks/govuk-prototype-kit/includes/scripts.njk
- lib/plugins/plugins.js
- lib/plugins/plugins.test.js
See: [Allow type="module" on Plug-In scripts](https://github.com/alphagov/govuk-prototype-kit/issues/2078)
- Implemented functionality to add type="module"
- Added/amended unit tests as required
- Added a cypress test to prove a script of type module can import another script successfully
> Plugin authors can now use scripts with type module

- CHANGELOG.md
- __tests__/utils/index.js
- bin/utils/index.js
- cypress/e2e/utils.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- scripts/performance-test-prepare
See: [Discrepancy between local and installed versions of the kit](https://github.com/alphagov/govuk-prototype-kit/issues/2096)
- All executed `npm install` commands now have the additional `--save-exact` option to make sure only the exact version is installed.
> Make sure exact versions of plugins are installed from the kit

- CHANGELOG.md
- cypress/e2e/plugins/1-available-plugins-tests/view-template-with-default-layout.cypress.js
- lib/manage-prototype-handlers.js
See: [If app/views/layouts/main.html is missing, viewing templates in Manage Prototype does not work](https://github.com/alphagov/govuk-prototype-kit/issues/2119)
> View templates with default layout

- migrator/index.js
- migrator/migration-steps.js
- migrator/migration-steps.spec.js
- migrator/migrator.spec.js
See the fix migration task within: [Layouts don't always work when a prototype is migrated](https://github.com/alphagov/govuk-prototype-kit/issues/2072)
- Move updating layouts into a separate migration script
- Add unit and integration tests
> Fix migration script for layouts

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
We’ve made a fix to the process to migrate old prototypes to v13 where the prototype has a customised layout. 
We’ve also made a fix to ensure that prototypes run properly online.
> Release - 13.6.1

- CHANGELOG.md
- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- lib/assets/javascripts/manage-prototype/manage-plugins.js
- lib/assets/javascripts/manage-prototype/manage-plugins.test.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/nunjucks/views/manage-prototype/plugin-install-or-uninstall.njk
- npm-shrinkwrap.json
- package.json
- server.js
See: [Fix our CSRF vulnerability](https://github.com/alphagov/govuk-prototype-kit/issues/2129)
- Replace CSURF implementation with CSRF-CSRF implementation
- Make sure cookie-parser middleware is after express-session middleware as recommended [here](https://socket.dev/npm/package/csrf-csrf#user-content-sessions)
- Fix unit tests
- Fix acceptance tests
> Prevent CSURF deprecated warning

- CHANGELOG.md
- __tests__/spec/errors.js
- cypress/e2e/dev/7-error-page-tests/fatal-error.cypress.js
- cypress/e2e/dev/7-error-page-tests/server-error.cypress.js
- cypress/fixtures/completely-broken-routes.js
- lib/config.js
- lib/errorServer.js
- lib/nunjucks/views/error-handling/server-error.njk
- listen-on-port.js
An implementation of https://github.com/alphagov/govuk-prototype-kit/issues/2090
> Show an error in the browser when the kit couldn't start

- lib/config.js
- lib/config.test.js
- lib/dev-server.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/utils/index.js
- lib/utils/verboseLogger.js
This is mostly intended for internal use but could be used by any user.  Setting `showPrereleaseUpgrades: true` in a prototype's `config.json` will mean that they will be prompted to upgrade to the latest release* whether or not it has the `latest` tag.
This would be used for many Alpha, Beta and Release Candidate releases.
The primary purpose of this ticket is to allow the Prototype Kit team to test Release Candidates in the UI before deciding to release them to everyone, it allows developers of other plug-ins the same functionality and it allows users who are wanting to receive pre-release plugins (which might not work as expected) to see the changes that are on their way to being released.
This will be particularly helpful if plugins (like `govuk-frontend`) release prereleases when …
> Allow installation of prereleases.

- CHANGELOG.md
- bin/cli
- bin/utils/index.js
- lib/exec.js
Adding a check for node version before running the kit.  Content needs reviewing (@joelanman).
> Node version checking

- CHANGELOG.md
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/remove-govuk-frontend.cypress.js
- cypress/events/index.js
- lib/config.js
- lib/config.test.js
- lib/manage-prototype-handlers.js
As mentioned in https://github.com/alphagov/govuk-prototype-kit/issues/2171 we don't have an optimal UI experience for uninstalling `govuk-frontend` right now so we are removing the button.  The kit still works without `govuk-frontend` as long as no other plugins expect it to be there.
In this PR I've made the button available when a feature flag is set - either `allowGovukFrontendUninstall` in the `config.json` or `ALLOW_GOVUK_FRONTEND_UNINSTALL` in the environment variables.  This is mostly to preserve the functionality and tests so that we can prove that the kit works without frontend.  It can be used by users too but we shouldn't be recommending that they use it.
> Hiding govuk-frontend uninstall until we deal with dependent plugins

- scripts/clean-publish-before-script.sh
- scripts/release-rc.sh
The script can be used to create a "Release Candidate" release tagged as "snapshot".  The command is used as follows:
```
./scripts/release-rc.sh main 13.7.0-rc.0
```
The command above will release version from `main` branch called `13.7.0-rc.0` which is tagged as `snapshot`.
> Adding RC release script

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2101: Show an error in the browser when the kit couldn't start](https://github.com/alphagov/govuk-prototype-kit/pull/2101)
- [#2142: Node version checking](https://github.com/alphagov/govuk-prototype-kit/pull/2142) - We now make sure you are using a compatible version of Node.JS before creating, running or migrating a kit.
- [#2163: Replace chalk with ansi-colors as it is installed as a dependency](https://github.com/alphagov/govuk-prototype-kit/pull/2163)
- [#2150: Prevent CSURF deprecated warning](https://github.com/alphagov/govuk-prototype-kit/pull/2150)
- [#2130: Create our own file store functionality in place of the session-file-store package](https://github.com/alphagov/govuk-prototype-kit/pull/2130)
- [#2172: Hiding govuk-frontend uninstall until we deal with dependent …
> Preparing release 13.7.0

- __tests__/spec/sanity-checks.js
- __tests__/utils/index.js
- bin/cli
- migrator/file-helpers.js
- migrator/index.js
- migrator/logger.js
We use three different tools to access the file system:
`fs` - the core file system API which uses callbacks
`fs.promises` - the core file system API but using promises instead of callbacks
`fs-extra` - a node module, not part of node core which provides additional tools for interacting with file systems
A while ago we used to use `fs` for all of the above, then we started using `fs`, `fsp` and `fse` respectively but not all the code has been updated.  This makes our naming consistent across the codebase.
> Using consistent names for fs, fse and fsp.

- CHANGELOG.md
- __tests__/spec/errors.js
- cypress/e2e/errors/1-error-page-tests/fatal-error.cypress.js
- cypress/e2e/errors/1-error-page-tests/server-error.cypress.js
- lib/assets/sass/prototype.scss
- lib/errorServer.js
- lib/nunjucks/nunjucksLoader.js
- lib/nunjucks/views/error-handling/server-error.njk
- lib/utils/errorView.js
- npm-shrinkwrap.json
- package.json
- server.js
See: [Improve the design of errors](https://github.com/alphagov/govuk-prototype-kit/issues/2019)
- Parse error messages and format for display within the error page
- Amend Cypress tests
- Amend Unit tests
> Improve the design of the error screen

- CHANGELOG.md
- __tests__/spec/errors.js
- lib/errorServer.js
- lib/sync-changes.js
- lib/sync-changes.test.js
- lib/utils/errorView.js
See: [Screen flickers when installing updates](https://github.com/alphagov/govuk-prototype-kit/issues/2196)
- Add error flag file to indicate when prototype flips between error and no error on restart
- Amend error handling unit tests
- Add sync changes unit tests
> Prevent screen flickering when installing plugins updates

- cypress/e2e/errors/1-error-page-tests/fatal-error.cypress.js
- lib/assets/sass/prototype.scss
- lib/nunjucks/views/error-handling/server-error.njk
Improves error page design:
- fixes focus and focus indicators for keyboard users
- fixes toggle of full error for screen reader users
- toggles button text between 'Hide full error' and 'Show full error'
- tweak vertical margins slightly to match design
@BenSurgisonGDS does any of this need additional tests?
> Error page design

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
We’ve improved our design for error pages and the page now automatically updates when you fix the error.
We’re still making improvements to these pages. If you have any feedback, please let us know in the replies.
> preparing for release of version 13.8.0

- CHANGELOG.md
- lib/nunjucks/govuk-prototype-kit/layouts/unbranded.njk
This restores unbranded pages to be styled as they used to be.
As the unbranded layout no longer extends the govuk-branded layout, the overriding block for stylesheets is not rendered.
> Fixed unstyled unbranded issue

- CHANGELOG.md
- known-plugins.json
- npm-shrinkwrap.json
- package.json
- [#2206: plugin validator tool](https://github.com/alphagov/govuk-prototype-kit/pull/2206) - We've created a tool to help test plugins for the Prototype Kit. It's only for internal use at the moment, but we're planning to make it public soon.
> Inital commit for release 3.9.0

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
[#2220: Specify plugin dependencies](https://github.com/alphagov/govuk-prototype-kit/pull/2220)
> Prepare for release 13.10.0

- CHANGELOG.md
- cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-via-ui-test.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-installation-mismatch.cypress.js
- cypress/e2e/utils.js
- lib/dev-server.js
- lib/manage-prototype-handlers.js
- lib/plugins/packages.js
- lib/plugins/plugins.js
See: [13.10.0 fails to start when dependency missing from node_modules](https://github.com/alphagov/govuk-prototype-kit/issues/2248)
- Fixed by making sure a plugin is deemed installed only if the package.json for the plugin exists where it is expected.
- This should also fix the issue [Plugin page fails after updating to 13.10.0 ](https://github.com/alphagov/govuk-prototype-kit/issues/2249)
> Fix plugin page failure after updating to 13.10.0

- __tests__/spec/sanity-checks.js
- bin/cli
- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/allow-upgrade-in-url.cypress.js
- cypress/e2e/plugins/plugin-utils.js
- cypress/events/index.js
- lib/assets/javascripts/manage-prototype/manage-plugins.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/nunjucks/views/manage-prototype/index.njk
- lib/nunjucks/views/manage-prototype/plugins.njk
- migrator/file-helpers.js
- migrator/index.js
- migrator/migration-steps.js
- migrator/migration-steps.spec.js
- migrator/migrator.spec.js
- migrator/update-steps.js
- migrator/update-steps.spec.js
Pre-Release available to test the upgrade flow.  I intentionally released one version before catering for the upgrade and one version after so the impact of the change could be tested.  
`13.10.2-rc.1` - the final version of this PR
`13.10.2-rc.0` - an earlier version of this PR which shows how the upgrade breaks (when upgrading to this version)
I've also added an environment variable to turn off checking the interim state check for install/upgrade because it fails every time on my machine.
> Renamed upgrade to update

- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-update-when-a-dependency-is-now-required.cypress.js
- lib/manage-prototype-handlers.js
- lib/nunjucks/views/manage-prototype/plugin-install-or-uninstall.njk
- lib/plugins/packages.js
- lib/plugins/packages.spec.js
- lib/utils/requestHttps.js
See: [When updating a plugin relevant dependencies should be installed (the same UX as installing a plugin)](https://github.com/alphagov/govuk-prototype-kit/issues/2242)
This PR includes:
- Update functionality for dependent plugins without taking into account versions for the time being.
- Amendments to the unit tests for the above
> Upgrading plugins with dependencies

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2257: Renamed upgrade to update](https://github.com/alphagov/govuk-prototype-kit/pull/2257)
- [#2245: Upgrading plugins with dependencies](https://github.com/alphagov/govuk-prototype-kit/pull/2245)
> Preparing for release 13.11.0

- CHANGELOG.md
- lib/nunjucks/views/manage-prototype/template-post-install.njk
To make this consistent with the plugin journey, add a link so users can easily return to the Templates page after creating pages
> Add back to templates link

- lib/dev-server.js
- lib/nunjucks/nunjucksLoader.js
- lib/nunjucks/nunjucksLoader.test.js
- lib/session-file-store.js
See: [Prototype failed due to corrupt session files](https://github.com/alphagov/govuk-prototype-kit/issues/2269)
- Delete corrupt session files to prevent prototype failing to load correctly
> Ignore and destroy corrupt session files

- cypress/e2e/dev/1-watch-files/watch-routes.cypress.js
- cypress/e2e/dev/1-watch-files/watch-views.cypress.js
- cypress/e2e/dev/2-page-component-tests/checkboxes.cypress.js
- cypress/e2e/dev/3-link-page-tests/link-index-to-start.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-via-cli-test.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/multi-combined-plugin-test.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/multi-plugin-test.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/single-plugin-test.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/prevent-uninstalling-kit-from-ui.cypress.js
- cypress/e2e/utils.js
- lib/dev-server.js
- lib/nunjucks/nunjucksLoader.js
- lib/nunjucks/nunjucksLoader.test.js
Make tests more stable by:
- replacing all occurences of `.should('contains.text',` with `.contains`
- adding the property `awaitWriteFinish: true` to chokidar settings
> Make tests more stable

- cypress/e2e/dev/2-page-component-tests/checkboxes.cypress.js
- cypress/e2e/dev/4-step-by-step-tests/step-by-step-journey.cypress.js
- cypress/e2e/dev/5-management-tests/clear-data-page.cypress.js
- cypress/e2e/dev/5-management-tests/no-autodatastore-on-management-pages.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-via-cli-test.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-via-ui-test.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/multi-plugin-test.cypress.js
- cypress/e2e/plugins/0-mock-plugin-tests/single-plugin-test.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/preview-template-view.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/allow-upgrade-in-url.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-installation-mismatch.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-update-when-a-dependency-is-now-required.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/remove-govuk-frontend.cypress.js
- cypress/events/index.js
- lib/dev-server.js
- package.json
See: [Create generic clean-up functions for cypress tests](https://github.com/alphagov/govuk-prototype-kit/issues/2237)
This PR extends the restoreToStarterFiles functionality to also restore to the installed plugins.
> Restore the plugins after each test

- package.json
- scripts/prepare-release
- scripts/utils/create-release-pr
We discussed watching the semi-automated releases and letting them bed in before automating the later stages.  The remaining uncertainty is around the specific commands to run.  This change keeps the existing behaviour but:
1. Watches the PR to see when it's approved
2. Watches the tests to see when they pass, providing the URL to any failed tests so they can be re-run
3. Once the PR is in a releasable state it outputs commands that can be run to complete the release - this allows us to test that those commands would correctly create the release if they were run automatically
This allows us to keep the final release as a manual step but to prove whether the automation would handle it correctly or not.
The big benefit of this change is that we can see and refine the commands before we …
> Added a log of the commands needed to complete the release

- cypress/e2e/styles/1-watch-styles/watch-custom-styles.cypress.js
- cypress/e2e/styles/1-watch-styles/watch-settings-styles.cypress.js
- cypress/e2e/styles/1-watch-styles/watch-styles.cypress.js
- cypress/events/index.js
- lib/build.js
The restore is implemented by copying backed up files at the start of each test.
Please note that this is an interim solution and will hopefully be replaced with the PR: [Use git restore to restore cypress tests](https://github.com/alphagov/govuk-prototype-kit/pull/2286) currently in development which is designed to use a git reset to achieve the above.
> Amend style cypress tests to use standard restore function

- govuk-prototype-kit.config.json
- lib/plugins/plugin-validator.js
- lib/plugins/plugin-validator.spec.js
- package.json
https://github.com/alphagov/govuk-prototype-kit/issues/2296
The format I've chosen is:
```
{
"meta": {
"description": "text goes here",
"urls": {
"documentation": "https://example.com/",
"releaseNotes": "https://example.com/",
"versionHistory": "https://example.com/"
}
}
}
```
I'm allowing for two variables in the URLs
`{{version}}` - the version number of the plugin
`{{kitVersion}}` - the version number of the kit that's running
I'm using both of these variables in the govuk-prototype-kit project which has the meta set to:
```
"meta": {
"description": "Quickly make interactive, accessible and realistic prototypes of GOV.UK services.",
"urls": {
"documentation": "https://prototype-kit.service.gov.uk/?linkFromKit={{kitVersion}}%3A{{version}}",
"versionHistory": …
```
> Adding plugin metadata to validator

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2287: Support sass errors in error pages](https://github.com/alphagov/govuk-prototype-kit/pull/2287)
- [#2297: Adding plugin metadata to validator](https://github.com/alphagov/govuk-prototype-kit/pull/2297)
> Preparing for release 13.12.1 (automated).

- .github/workflows/test-acceptance.yaml
- CHANGELOG.md
- cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-via-ui-test.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/available-plugins.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-installation-mismatch.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-update-when-a-dependency-is-now-required.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/remove-govuk-frontend.cypress.js
- cypress/e2e/plugins/plugin-utils.js
- lib/assets/sass/manage-prototype.scss
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/nunjucks/views/manage-prototype/plugins.njk
- lib/plugins/packages.js
- lib/plugins/packages.spec.js
- lib/plugins/plugin-utils.js
- npm-shrinkwrap.json
See https://github.com/alphagov/govuk-prototype-kit/issues/2298
Changes included:
- Change plugins page as per design and changes as requested
- Support plugin config meta data
- Add `/plugins-installed` route
- Add _search_ and _filter_ behaviour for available plugins
- Update Acceptance tests to handle separate _Installed_ and _Find_ Plugin pages
- Added unit tests for the new post route for search
- Cleaned up some Acceptance tests to allow them to retry correctly
- Added meta data for the jquery proxy config
- Added a proxy config for notify so meta data could be added
Changes not included:
- Pagination will be done in a separate PR
> Build the enhanced plugin page

- CHANGELOG.md
- lib/nunjucks/views/manage-prototype/plugins.njk
also fixes the heading hierarchy - now we have h1, h2, h3, h4
> Only show Clear search link if there's a search

- __tests__/spec/sanity-checks.js
- lib/authentication.js
- lib/build.js
- lib/errorServer.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/manage-prototype-routes.js
- lib/nunjucks/views/error-handling/page-not-found.njk
- lib/nunjucks/views/manage-prototype/layout.njk
- lib/nunjucks/views/manage-prototype/password.njk
- lib/nunjucks/views/manage-prototype/scripts.njk
This should help with the preparation for Frontend v5.
Management and internal pages are now properly isolated:
- Password page
- Manage Prototype section
- 404 page
- Error pages
These pages now fully use the version of Govuk Frontend specified in our package.json regardless of which version the user has installed.
I've also removed the plugin sanity checks - they predated our cypress tests, are hard-coded with details from govuk-frontend and aren't particularly useful anymore.
> Using internal Govuk Frontend more widely

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2318: Only show Clear search link if there's a search](https://github.com/alphagov/govuk-prototype-kit/pull/2318)
- [#2321: Update hint for create page](https://github.com/alphagov/govuk-prototype-kit/pull/2321)
- [#2317: Using internal GOV.UK Frontend more widely](https://github.com/alphagov/govuk-prototype-kit/pull/2317) - this makes error pages, password pages etc. more reliable.
> Preparing for release 13.13.1 (automated).

- lib/assets/sass/manage-prototype.scss
- lib/authentication.js
- lib/build.js
- lib/errorServer.js
- lib/nunjucks/views/error-handling/server-error.njk
This PR fixes a few error page issues
It picks up from changes to isolate GOV.UK Frontend versions in:
* https://github.com/alphagov/govuk-prototype-kit/pull/2317
The error page Sass `$govuk-assets-path` uses **/manage-prototype/dependencies/govuk-frontend**  but we didn't handle error server responses for this route so fonts and background images were missing:
https://github.com/alphagov/govuk-prototype-kit/blob/86fb72a0290af1896dce34472732a778711f6072/lib/assets/sass/manage-prototype.scss#L1
The error page Nunjucks `assetPath` uses **/plugin-assets/govuk-frontend** which would typically route to a plugin version of GOV.UK Frontend rather than one internal to the Prototype Kit
This was handled but with different URLs to the CSS:
```html
<link rel="shortcut icon" sizes="16x16 32x32 48x48" …
```
> Fix error server `/manage-prototype/dependencies`

- scripts/utils/create-release-pr
Allowing stderr because gh outputs there during a success.
> Improve release script

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2336: Fix misleading error when starting a migrated prototype first time](https://github.com/alphagov/govuk-prototype-kit/pull/2336)
> Preparing for release 13.13.2 (automated).

- lib/build.js
This fixes the error behind the misleading error in https://github.com/alphagov/govuk-prototype-kit/issues/2335
> Do not compile sass files with an underscore prefix

- npm-shrinkwrap.json
- package.json
Putting my colinbot hat on 🤖
Updates `govuk-frontend` from 4.5.0 to 4.7.0
- [Release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v4.7.0)
- [Changelog](https://github.com/alphagov/govuk-frontend/blob/v4.7.0/CHANGELOG.md)
- [Commits](https://github.com/alphagov/govuk-frontend/commits/v4.7.0)
Applies to internal pages only as plugins are updated separately since:
* https://github.com/alphagov/govuk-prototype-kit/pull/2118
> Bump govuk-frontend from 4.5.0 to 4.7.0

- lib/sync-changes.js
- lib/sync-changes.test.js
This PR helped me find and fix an issue in https://github.com/alphagov/govuk-prototype-kit/pull/2306
Before that I was stuck with this error in the terminal:
```console
Error: ENOENT: no such file or directory, open '/private/var/folders/2k/ws6lqbf57d75yf8xt7tt_bqc0000gn/T/test-prototype/.tmp/errors.json'
```
My issue had crashed early enough to confirm:
1. The helper `flagError()` can run before **.tmp** directory exists
2. Errors can be written as empty strings by `writeJsonSync(errorPath, { error })`
This PR stops that from happening
> Fix errors.json logging `ENOENT: no such file or directory`

- CHANGELOG.md
- lib/utils/asyncSerialMap.spec.js
- lib/utils/asyncSeriesMap.js
- lib/utils/index.js
- package.json
This is intended to resolve an issue I was facing with a migration yesterday where there was a "too many files open" error for a large prototype.  I'd expect this to be more reliable too as it's less likely to choke slower systems up.
> Open fewer files at once during migration.

- scripts/prepare-release
- scripts/utils/create-release-pr
The changes in this update are:
1. It now does a shallow clone to save time
2. It doesn't trigger a merge, it detects the merge
3. It trims the output in order to accurately detect the npm user (where it failed on the last release)
4. It now completes the release
> Improved the release script

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2342: Open fewer files at once during migration](https://github.com/alphagov/govuk-prototype-kit/pull/2342)
- [#2340: Do not compile sass files with an underscore prefix](https://github.com/alphagov/govuk-prototype-kit/pull/2340)
- [#2334: Making sure Manage Prototype pages use govuk-frontend v4.7.0](https://github.com/alphagov/govuk-prototype-kit/pull/2334)
> Preparing for release 13.13.3 (automated).

- CHANGELOG.md
- lib/nunjucks/views/manage-prototype/scripts.njk
On management pages, `window.GOVUKPrototypeKit` is unavailable when GOV.UK Frontend `init.js` runs
This PR loads `kit.js` first to ensure `window.GOVUKPrototypeKit` is available
Fixes https://github.com/alphagov/govuk-prototype-kit/issues/2348
> Fix GOV.UK Frontend `initAll()` on management pages

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2306: Locate GOV.UK Frontend using `require.resolve()`](https://github.com/alphagov/govuk-prototype-kit/pull/2306)
- [#2349: Fix GOV.UK Frontend `initAll()` on management pages](https://github.com/alphagov/govuk-prototype-kit/pull/2349)
> Preparing for release 13.13.4 (automated).

- CHANGELOG.md
- lib/build.js
- lib/errorServer.js
- lib/govukFrontendPaths.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/nunjucks/nunjucksConfiguration.js
- server.js
This PR fixes https://github.com/alphagov/govuk-prototype-kit/issues/2352 for management pages only
The fix uses `res.send()` with a custom Nunjucks environment as used by [`getTemplatesViewHandler()`](https://github.com/alphagov/govuk-prototype-kit/blob/6043088e7c3428a1c85151390b240d6d85a47423/lib/manage-prototype-handlers.js#L275)
Management pages previously used Express.js `res.render()` with all plugin Nunjucks views available
Without this bugfix, users upgrading to GOV.UK Frontend v5 would see management pages load Nunjucks views from GOV.UK Frontend v5 but fonts, assets, styles and scripts from GOV.UK Frontend v4
> Prevent management pages using "plugin" GOV.UK Frontend views

- CHANGELOG.md
- lib/build.js
This PR suppresses Sass `$legacy` colour palette deprecation warnings logged by GOV.UK Frontend v5 until the following files and packages can be updated from issue https://github.com/alphagov/govuk-prototype-kit/issues/2293:
>* `govuk-prototype-kit/lib/assets/sass/patterns/_pagination.scss`
>* `govuk-prototype-kit-step-by-step/sass/_step-by-step-navigation.scss`
>* `govuk-prototype-kit-step-by-step/sass/_step-by-step-navigation-header.scss`
This completes GOV.UK Frontend v5 plugin support in https://github.com/alphagov/govuk-prototype-kit/issues/2293
The legacy palette was replaced in GOV.UK Frontend v3.0.0:
https://designnotes.blog.gov.uk/2019/07/29/weve-updated-the-gov-uk-colours-and-font/
Support has continued throughout v4.0.0 but is deprecated in v5.0.0
> Suppress Sass warnings for `$legacy` deprecated colour palette

- CHANGELOG.md
- lib/utils/index.js
This PR switches `application.js` to `<script type"module">` to fix:
* https://github.com/alphagov/govuk-prototype-kit/issues/2353
This change defers script load by default and also ensures:
1. ES module `import { Accordion } from` syntax support in GOV.UK Frontend v5
2. Load order compatibility with other plugins that update to ES modules
This follows GOV.UK Frontend to protect browsers without [ES6 modules support](https://caniuse.com/es6-module) from script errors, such as:
* Internet Explorer 11
* Edge 15
* Chrome 60
* Firefox 59
* Safari 9
> Defer prototype `application.js` to load after plugin scripts

- CHANGELOG.md
- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- lib/manage-prototype-handlers.js
- lib/nunjucks/views/manage-prototype/plugins.njk
- lib/plugins/packages.js
- lib/plugins/packages.spec.js
The kit had wrongly indicated that a plugin installed directly from github could be updated.  This caused a user's prototype to crash when they attempted this.  As the kit was only designed to allow updates from the npm registry, this change prevents the update button to appear for those plugins installed locally or from github.  If the user wants to update their plugin installed from github, they'll have to upgrade it manually from the command line as they had installed it in the first place.
> Only allow plugin update functionality when installed from npm

- CHANGELOG.md
- cypress/e2e/plugins/0-mock-plugin-tests/install-plugin-via-ui-test.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/available-plugins.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/install-available-plugin.cypress.js
- cypress/e2e/plugins/1-available-plugins-tests/install-common-templates-plugin-from-templates-page.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-installation-mismatch.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/handle-plugin-update-when-a-dependency-is-now-required.cypress.js
- cypress/e2e/plugins/2-prototype-kit-plugin-tests/remove-govuk-frontend.cypress.js
- cypress/e2e/plugins/plugin-utils.js
Simplify plugins tests with reusable functions that will meke it is easier to change the functionality (In future adding the plugin details page) without affecting the main acceptance test structure.  This also makes it easeir to fix any bugs.
> Simplify and improve acceptance tests

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2355: Prevent management pages using "plugin" GOV.UK Frontend views](https://github.com/alphagov/govuk-prototype-kit/pull/2355)
- [#2356: Only allow plugin update functionality when installed from npm](https://github.com/alphagov/govuk-prototype-kit/pull/2356)
- [#2357: Simplify and improve acceptance tests](https://github.com/alphagov/govuk-prototype-kit/pull/2357)
- [#2358: Suppress Sass warnings for `$legacy` deprecated colour palette](https://github.com/alphagov/govuk-prototype-kit/pull/2358)
- [#2359: Update application.js to `<script type"module">`](https://github.com/alphagov/govuk-prototype-kit/pull/2359)
> Preparing for release 13.13.5 (automated).

- CHANGELOG.md
- lib/plugins/packages.js
- lib/utils/index.js
- lib/utils/utils.test.js
Make sure that anyone on a pre-release version of a plugin will not be given the update button if the latest non-pre-release version is a lower version number.
> Fix plugin update detection

- .github/workflows/test-acceptance.yaml
- .github/workflows/test-heroku.yaml
- .github/workflows/test.yaml
- .nvmrc
- CHANGELOG.md
- bin/cli
- lib/plugins/plugin-validator.spec.js
- npm-shrinkwrap.json
- package.json
As the current LTS version of node.js is 20 and the maintenance version is 18, we should reflect that within the protoype kit.
See here for the current LTS version: https://nodejs.org/en/download
> Support for the new Node LTS (version 20)

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2363: Support for the new Node LTS (version 20)](https://github.com/alphagov/govuk-prototype-kit/pull/2363)
> Preparing for release 13.14.0 (automated).

- CHANGELOG.md
- lib/utils/index.js
- lib/utils/utils.test.js
This fixes the issue detected by a user as below:
This was detected by a user posting the following:
```
Environment:
OSX 12.6.9
npm -v 8.19.3
node -v v18.13.0
Error. Kit will not run with internet connection disabled.
Error message:
Node.js v18.13.0
[nodemon] For missing modules try running `npm install`
Restarting kit...
You can manage your prototype at:
http://localhost:3000/manage-prototype
The Prototype Kit is now running at:
http://localhost:3000/
/Users/ian/Sites/xd/node_modules/govuk-prototype-kit/lib/utils/index.js:273
const [, latestMajor, latestMinor, latestPatch, latestSuffix] = latestVersion.match(matcher)
^
TypeError: Cannot read properties of undefined (reading 'match')
at hasNewVersion (/Users/ian/Sites/xd/node_modules/govuk-prototype-kit/lib/utils/index.js:273:81)
at …
```
> Support no internet connection

- cypress/e2e/prod/2-management-tests/password-page.cypress.js
- cypress/events/index.js
- lib/authentication.js
- lib/authentication.test.js
- lib/config.js
- lib/config.test.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- npm-shrinkwrap.json
- package.json
Several requests have been made for prototypes to support additional temporary passwords that can be given to guest users to use the deployed prototype while maintaining the ability for more permanent users to keep using the main password.
The functionality in this ticket allows for an environment variable PASSWORD_KEYS which is expected to contain a comma separated string that will contain addional environment variable names that can be set for additional passwords.
If the following environment variables exist:
- PASSWORD=password
- PASSWORD_KEYS=PASSWORD_01,PASSWORD_02
- PASSWORD_01=password01
- PASSWORD_02=password02
then any of the passwords password, password01, or password02 can be used.
> Support multiple passwords

- lib/plugins/plugins.js
Add all the keys to the schema comment for the plugin config.
> Fix plugin config schema comment

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2375: Plugin validator should support nunjucks functions](https://github.com/alphagov/govuk-prototype-kit/pull/2375)
> Preparing for release 13.15.1 (automated).

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2380: Only display packages that are plugins](https://github.com/alphagov/govuk-prototype-kit/pull/2380)
> Preparing for release 13.15.3 (automated).

- CHANGELOG.md
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/plugins/plugin-utils.js
- lib/plugins/plugin-utils.spec.js
- lib/plugins/plugins.js
I've had a several requests from people to allow npm modules to load their script, sass files and assets as they would a plugin.
A designer was trying to use the npm module `browser-fs-access` but was having difficulty loading the scripts from node_modules.  This PR adds support for a new json file `/app/plugin-proxy.json` that contains a proxy plugin config for the module that treats the npm module as a plugin which solved his issue neatly:
```
{
"browser-fs-access": {
"scripts": {
"type": "module",
"path": "/dist/index.modern.js"
}
}
}
```
I'm suggesting this be introduced as it will not affect anyone who has not created the `/app/plugin-proxy.json` file with a view to documenting the use of this at a later date.  For now it gets over the issue of wanting something to be a plugin …
> Make any npm module a plugin via a proxy plugin config

- CHANGELOG.md
- lib/filters/core-filters.js
Allow users to simplify entering items when the text and value are the same.
The following: 
```njk
["Rubble", "Oil", "Card"] | formatItems
```
will return: 
```njk
[
{ text: "Rubble", value: "Rubble" },
{ text: "Oil", value: "Oil" },
{ text: "Card", value: "Card" },
]
```
> Add format items filter to core filters

- CHANGELOG.md
- cypress/e2e/dev/5-management-tests/no-autodatastore-on-management-pages.cypress.js
- cypress/e2e/smoke/0-smoke-tests/index-page.cypress.js
- cypress/e2e/utils.js
- lib/nunjucks/views/manage-prototype/scripts.njk
- npm-shrinkwrap.json
- package.json
PR to use **GOV.UK Frontend v5** on management pages including the error server
Plugins can [freely use GOV.UK Frontend v5](https://github.com/alphagov/govuk-prototype-kit/issues/2293) already but internal pages still use v4 and fail some tests
This PR also unblocks status checks on `main` where we know some tests install the latest `govuk-frontend` plugin. Current CSS selectors for the logo were incompatible between v4 and v5 so have been fixed
`.govuk-header__logotype-text` → `.govuk-header__logotype`
> Use GOV.UK Frontend v5 on management pages and tests

- CHANGELOG.md
- lib/manage-prototype-handlers.js
- npm-shrinkwrap.json
- package.json
Updates to GOV.UK Frontend v5.2.0 (including the new crown) to close https://github.com/alphagov/govuk-prototype-kit/issues/2395
Also closes https://github.com/alphagov/govuk-prototype-kit/issues/2392 where `assetPath` wasn't fully set for template previews
> Update to GOV.UK Frontend v5.2.0 on management pages

- lib/session-file-store.js
We store session data in the filesystem using our own session `FileStore` class. Each session is stored as a separate JSON file inside `.tmp/sessions` with an expiry date and the data for session.
As part of the `set` method for the FileStore class, we have some logic which tries to clean up expired sessions from the filesystem.
This loops through all of the files in the session store directory and checks each one in turn to see if the expiry date in the JSON is in the past. If it is, it calls `this.destroy` passing the `storedSessionId`. This happens asynchronously – we map over the files in the directory to create an array of promises, each of which awaits a call to the filesystem to read the JSON.
Unfortunately, `storedSessionId` is scoped to the outer `set` method and is therefore …
> Stop accidentally cleaning up non-expired sessions

- lib/plugins/plugin-validator.js
- lib/session.js
- migrator/file-helpers.js
- migrator/migration-steps.js
- migrator/migration-steps.spec.js
So we don't lose these I've split out some the code issues found by the TypeScript `tsc` compiler
> Various bug fixes and code issues

- CHANGELOG.md
- lib/nunjucks/views/manage-prototype/plugins.njk
I was having a quick look to see if any issues were listed in developer tools for #2393 and noticed this was being flagged.
The search input on the plugin list page does not have a programatically label because the label is not currently associated with the input.
Rather than using the separate `govukLabel` macro, pass the label options to the  `govukInput` macro and let it take care of associating the label for us.
We can also use the `govuk-label--s` modifier rather than a font weight override.
> Associate the plugin search input with its label

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2327: Use GOV.UK Frontend v5 on management pages and tests](https://github.com/alphagov/govuk-prototype-kit/pull/2327)
- [#2394: Update Browsersync to resolve `axios` vulnerability](https://github.com/alphagov/govuk-prototype-kit/pull/2394)
- [#2395: Update to GOV.UK Frontend v5.2.0 on management pages](https://github.com/alphagov/govuk-prototype-kit/pull/2395)
- [#2398: Associate the plugin search input with its label](https://github.com/alphagov/govuk-prototype-kit/pull/2398)
- [#2399: Stop accidentally cleaning up non-expired sessions](https://github.com/alphagov/govuk-prototype-kit/pull/2399)
> Preparing for release 13.16.1 (automated).

- __tests__/utils/index.js
- bin/utils/argv-parser.js
- lib/govukFrontendPaths.js
- lib/plugins/plugin-validator.js
- lib/plugins/plugins.js
- lib/utils/index.js
Additional documentation to help reduce bugs when working with config and plugin management code
> Add JSDoc to document plugin configs etc

- CHANGELOG.md
- lib/assets/sass/includes/_error-page.scss
- lib/assets/sass/manage-prototype.scss
- lib/errorServer.js
- lib/govukFrontendPaths.js
- lib/manage-prototype-handlers.js
- lib/manage-prototype-handlers.test.js
- lib/nunjucks/views/error-handling/server-error.njk
- lib/nunjucks/views/manage-prototype/layout.njk
- npm-shrinkwrap.json
- package.json
Updates the prototype kit to govuk-frontend 5.10.2 and apples the brand refresh to the management pages.
Resolves https://github.com/alphagov/govuk-prototype-kit/issues/2430
This also updates a few things within protptypes themselves:
- Applies the brand updates to template previews if the rebrand config options are present
- Applies the brand updates to error pages if the rebrand config options are present
- Sets the govuk frontend asset path to `assets/rebrand` instead of `assets` if the rebrand config options are present, and amends this in the template for management pages to ensure that they're always using the rebrand assets. This resolves both https://github.com/alphagov/govuk-prototype-kit/issues/2431 and https://github.com/alphagov/govuk-prototype-kit/issues/2427.
As part of the …
> Apply brand updates manage prototype pages

- CHANGELOG.md
- npm-shrinkwrap.json
Fixes high severity vulnerability audit warnings, no version changes are breaking changes, and the tests all pass
Before:
```
axios  1.3.2 - 1.7.3
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
fix available via `npm audit fix`
node_modules/wait-on/node_modules/axios
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
fix available via `npm audit fix`
node_modules/body-parser
node_modules/express/node_modules/body-parser
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable …
```
> Update dependencies to resolve npm audit warnings

- CHANGELOG.md
- lib/nunjucks/views/manage-prototype/index.njk
It used to go to Find plugins, it should go to Installed Plugins where you click the update button
fixes #2409
> Fix kit version update link

- .github/workflows/test-acceptance.yaml
- .github/workflows/test-heroku.yaml
- .github/workflows/test.yaml
- .nvmrc
- CHANGELOG.md
- bin/cli
`package.json` already allowed to run on Node 22, but `bin/cli.js` would log a warning if you used that version, so updates to allow Node 22 as well.
Also updates the tests to ensure things work OK on Node 22.
Pretty much followed the changes in [this commit](https://github.com/alphagov/govuk-prototype-kit/commit/4eb6041f7574b58626efe2a66fb8d8dd4d990cf5), except for:
- `package.json` and `npm-shrinkwrap.json` which already allowed 22
- `lib/plugins/plugin-validator.spec.js` which didn't need updating
To ease the maintenance in the future, we may want to look into updating `bin/cli.js` to allow any LTS after Node 22 (ie. even numbers after Node 22). We'd need to get some understanding on whether Node may suddenly remove features which may break the kit, as well as figure how to test …
> Add support for Node 22

- CHANGELOG.md
- lib/assets/sass/manage-prototype.scss
- lib/assets/sass/patterns/_pagination.scss
- lib/build.js
- npm-shrinkwrap.json
- package.json
Avoid Sass logging warnings in the console when compiling the stylesheets. These were a mix of:
- warnings from GOV.UK Frontend
- warnings from Sass itself
For GOV.UK Frontend, the only warning was about the use of `$legacy` when calling `govuk-colour`. As the parameter is not used by the function anymore, it's been removed from the calls, leading to GOV.UK Frontend no longer outputing any warnings.
For Sass, the `npm-shrinkwrap.json` file is made part of the package, ensuring dependencies are installed at the versions that were available at the point of release (and against which the tests for the release ran). This'll prevent `npm install` from fetching the latest version compatible with the one declared in `package.json`, which may be introducing warnings, or bugs from new features (or …
> Avoid warnings in the console when Sass files get compiled

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- [#2434: Apply brand updates manage prototype pages](https://github.com/alphagov/govuk-prototype-kit/pull/2434)
- [#2443: Add support for Node 22](https://github.com/alphagov/govuk-prototype-kit/pull/2443)
- [#2439: Replace custom nav on management pages with service navigation](https://github.com/alphagov/govuk-prototype-kit/pull/2439)
- [#2408: Fix kit version update link](https://github.com/alphagov/govuk-prototype-kit/pull/2408)
- [#2420: Fixing the default homepage](https://github.com/alphagov/govuk-prototype-kit/pull/2420)
- [#2425: Fix open redirect vuln in login page](https://github.com/alphagov/govuk-prototype-kit/pull/2425)
- [#2437: Fix version logic for showing whether a plugin has updates](https://github.com/alphagov/govuk-prototype-kit/pull/2437)
- [#2442: Avoid warnings in …
> Preparing for release 13.17.0 (automated).

- CHANGELOG.md
- cypress/e2e/dev/5-management-tests/change-service-name.cypress.js
- lib/manage-prototype-handlers.js
- lib/nunjucks/views/manage-prototype/layout.njk
Update Manage your prototype pages to use the new style header and servicename placement.
I'm also suggesting using productName as it makes sense to me to clarify this isn't GOV.UK
These changes do not affect user's prototype pages.
It would be nice (and follow guidance) to have each section in the nav selected on the relevant pages, but I'm not sure how hard that is.
> Update manage prototype header

- npm-shrinkwrap.json
- package.json
Updates inquirer from 8.2.6 to 12.9.3 in order to address a minor vulnerability in tmp, which is a dependency of external-editor, which _was_ a dependency of inquirer.
This is a significant jump in versions however the major versions have been stepped through locally to test and their release notes checked. E2e tests are passing on this PR.
The one point of concern was that we are importing inquirer via CommonJS whilst [in 9.0.0 they identified it as an es module only](https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%409.0.0). However [10 and beyond also include a CommonJS export](https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%4010.0.0) so it works fine.
> Update inquirer to 12.9.3
